### jabber
### 'Jabber,Pengirim,Online', data
### 'Jabber,Pengirim,Inbox', data
### 'Jabber,Pengirim,Error', err
### 'Jabber,Pengirim,Subscribe', data
### 'Jabber,Pengirim,Open', data
### 'Jabber,Pengirim,Connect', data
### 'Jabber,Pengirim,Outbox', data






### Daftar koneksi jabber
GET http://localhost/api/jabber/v2

### Hapus koneksi jabber
DELETE http://localhost/api/jabber/v2/:id

### Buat koneksi jabber
POST http://localhost/api/jabber/v2/connect
Content-Type: application/json

{
    "pengirim": "ndiing",
    "jid": "ndiing@jabb.im",
    "password": "S2N#Wcm8rnKbpsg",
    "host": "jabb.im"
}

### Buat koneksi jabber, lebih dari 1, gunakan pengirim/id yang beda
POST http://localhost/api/jabber/v2/connect
Content-Type: application/json

{
    "pengirim": "ndiing_center_1",
    "jid": "ndiing_center_1@jabb.im",
    "password": "@8d.yAkRiMA7Qpj",
    "host": "jabb.im"
}

### Kirim pesan ke penerima jabber
GET http://localhost/api/jabber/v2/outbox?penerima=ndiing2@jabb.im&pesan=message

### Kirim pesan ke penerima jabber sesuai pengirim/id jika kosong maka dikirim sesuai urutan
GET http://localhost/api/jabber/v2/outbox?penerima=ndiing2@jabb.im&pesan=message&pengirim=ndiing

### Kirim pesan ke penerima jabber / dapat digunakan di (Web SMS Sender)
GET http://localhost/api/jabber/v2/outbox?penerima=[to]&pesan=[message]

### Kirim pesan ke penerima jabber sesuai pengirim/id jika kosong maka dikirim sesuai urutan / dapat digunakan di (Web SMS Sender)
GET http://localhost/api/jabber/v2/outbox?penerima=[to]&pesan=[message]&pengirim=ndiing





### telegram
### 'Telegram,Pengirim,Start', data
### 'Telegram,Pengirim,Contact', data
### 'Telegram,Pengirim,Inbox', data
### 'Telegram,Pengirim,Open', data
### 'Telegram,Pengirim,Connect', data
### 'Telegram,Pengirim,Outbox', data





### Daftar koneksi telegram
GET http://localhost/api/telegram/v2

### Hapus koneksi telegram
DELETE http://localhost/api/telegram/v2/:id

### Buat koneksi telegram
POST http://localhost/api/telegram/v2/connect
Content-Type: application/json

{
    "pengirim": "api_otomax_bot",
    "token": "2049378584:AAH0mEAeNWYSNSQe7flTTwYAwej5im1nJb4"
}

### Buat koneksi telegram, lebih dari 1, gunakan pengirim/id yang beda
POST http://localhost/api/telegram/v2/connect
Content-Type: application/json

{
    "pengirim": "ndiing_bot",
    "token": "1938532379:AAEedETbB6AbfavfTi7iyam0SrLPqWStlR0"
}

###
POST http://localhost/api/telegram/v2/connect
Content-Type: application/json

{
    "pengirim": "ndiing_center_1_bot",
    "token": "2049367740:AAFl5EPPT9D-EBFhuzxqlbf67Yn6tdQAfms"
}

### Kirim pesan ke penerima telegram
GET http://localhost/api/telegram/v2/outbox?penerima=1344008938&pesan=message

### Kirim pesan ke penerima telegram sesuai pengirim/id jika kosong maka dikirim sesuai urutan
GET http://localhost/api/telegram/v2/outbox?penerima=1344008938&pesan=message&pengirim=api_otomax_bot

### Kirim pesan ke penerima telegram / dapat digunakan di (Web SMS Sender)
GET http://localhost/api/telegram/v2/outbox?penerima=[to]&pesan=[message]

### Kirim pesan ke penerima telegram sesuai pengirim/id jika kosong maka dikirim sesuai urutan / dapat digunakan di (Web SMS Sender)
GET http://localhost/api/telegram/v2/outbox?penerima=[to]&pesan=[message]&pengirim=api_otomax_bot





### whatsapp
### 'Whatsapp,Pengirim,Open', data
### 'Whatsapp,Pengirim,Close', data
### 'Whatsapp,Pengirim,Qr', data
### 'Whatsapp,Pengirim,Inbox', data
### 'Whatsapp,Pengirim,Connect', data
### 'Whatsapp,Pengirim,Outbox', data





### Daftar koneksi whatsapp
GET http://localhost/api/whatsapp/v2

### Hapus koneksi whatsapp
DELETE http://localhost/api/whatsapp/v2/:id

### Buat koneksi whatsapp
POST http://localhost/api/whatsapp/v2/connect
Content-Type: application/json

{
    "pengirim": "6281938064470"
}

### Buat koneksi whatsapp, lebih dari 1, gunakan pengirim/id yang beda
POST http://localhost/api/whatsapp/v2/connect
Content-Type: application/json

{
    "pengirim": "6283845311393"
}

### Kirim pesan ke penerima whatsapp
GET http://localhost/api/whatsapp/v2/outbox?penerima=6281935155404&pesan=message

### Kirim pesan ke penerima whatsapp sesuai pengirim/id jika kosong maka dikirim sesuai urutan
GET http://localhost/api/whatsapp/v2/outbox?penerima=6281935155404&pesan=message&pengirim=6281938064470

### Kirim pesan ke penerima whatsapp / dapat digunakan di (Web SMS Sender)
GET http://localhost/api/whatsapp/v2/outbox?penerima=[to]&pesan=[message]

### Kirim pesan ke penerima whatsapp sesuai pengirim/id jika kosong maka dikirim sesuai urutan / dapat digunakan di (Web SMS Sender)
GET http://localhost/api/whatsapp/v2/outbox?penerima=[to]&pesan=[message]&pengirim=6281938064470





###





###
GET http://localhost/events
