
### Lihat semua sesi
GET http://localhost/api/jabber/v1

### Hapus sesi
DELETE http://localhost/api/jabber/v1/id-sesi-1

### Koneksi
POST http://localhost/api/jabber/v1/id-sesi-1/connect
Content-Type: application/json

{
    "jid": "ndiing@jabb.im",
    "password": "S2N#Wcm8rnKbpsg",
    "host": "jabb.im"
}

### Kirim Pesan
GET http://localhost/api/jabber/v1/id-sesi-1/outbox?pengirim=ndiing2@jabb.im&pesan=pesan

### Event [Online,Inbox,Error,Subscribe,Open,Outbox]
GET http://localhost/api/jabber/v1/id-sesi-1/event

