# Daftar koneksi
### Request
GET http://localhost/api/jabber/v2/

# Hapus koneksi
### Request
DELETE http://localhost/api/jabber/v2/ndiing

# Buat koneksi
### Request
GET http://localhost/api/jabber/v2/connect?pengirim=ndiing&jid=ndiing%40jabb.im&password=S2N%23Wcm8rnKbpsg&host=jabb.im

# Buat koneksi
### Request
POST http://localhost/api/jabber/v2/connect
Content-Type: application/json

{
    "pengirim": "ndiing",
    "jid": "ndiing@jabb.im",
    "password": "S2N#Wcm8rnKbpsg",
    "host": "jabb.im"
}

# Kirim pesan
### Request
GET http://localhost/api/jabber/v2/outbox?penerima=ndiing2%40jabb.im&pesan=Lorem+ipsum+dolor+sit%2C+amet+consectetur+adipisicing+elit.+Est%2C+ipsa%3F&pengirim=ndiing

# Kirim pesan
### Request
POST http://localhost/api/jabber/v2/outbox
Content-Type: application/json

{
    "penerima": "ndiing2@jabb.im",
    "pesan": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Est, ipsa?",
    "pengirim": "ndiing"
}






# Buat koneksi
### Request
GET http://localhost/api/jabber/v2/connect?pengirim=ndiing&jid=ndiing%40jabb.im&password=S2N%23Wcm8rnKbpsg&host=jabb.im

# Buat koneksi
### Request
POST http://localhost/api/jabber/v2/connect
Content-Type: application/json

{
    "pengirim": "ndiing",
    "jid": "ndiing@jabb.im",
    "password": "S2N#Wcm8rnKbpsg",
    "host": "jabb.im"
}


# Buat koneksi
### Request
GET http://localhost/api/jabber/v2/connect?pengirim=ndiing_center_1&jid=ndiing_center_1%40jabb.im&password=%408d.yAkRiMA7Qpj&host=jabb.im

# Buat koneksi
### Request
POST http://localhost/api/jabber/v2/connect
Content-Type: application/json

{
    "pengirim": "ndiing_center_1",
    "jid": "ndiing_center_1@jabb.im",
    "password": "@8d.yAkRiMA7Qpj",
    "host": "jabb.im"
}

