###
GET http://localhost/api/mitratokopedia/v1/

###
DELETE http://localhost/api/mitratokopedia/v1/session1

### OTPRequest
### Request
GET http://localhost/api/mitratokopedia/v1/OTPRequest
?pengirim=session1
&msisdn=6281938064470

### OTPValidate
### Request
GET http://localhost/api/mitratokopedia/v1/OTPValidate
?pengirim=session1
&code=788741

### GetMitraMultiTickerGetDigitalWidget
### Request
GET http://localhost/api/mitratokopedia/v1/GetMitraMultiTickerGetDigitalWidget
?pengirim=session1

### RetailDigitalMainQuery
### Request
GET http://localhost/api/mitratokopedia/v1/RetailDigitalMainQuery
?pengirim=session1
&category_id=1

### GetPromoList
### Request
GET http://localhost/api/mitratokopedia/v1/GetPromoList
?pengirim=session1
&category_id=1

### V13Enquiry
### Request
GET http://localhost/api/mitratokopedia/v1/V13Enquiry
?pengirim=session1
&client_number=515420130903
&product_id=291

### OTPRequestQuery
### Request
GET http://localhost/api/mitratokopedia/v1/OTPRequestQuery
?pengirim=session1






### V2PaymentConfirm
### Request
GET http://localhost/api/mitratokopedia/v1/V2PaymentConfirm
?pengirim=session1
&trxid=192
&gateway_code=MITRAVA
&code=111670
&category_id=1
&voucher_code=
&client_number=087758437457
&operator_id=5
&transactionAmount=5750
&product_id=1135
&is_pulsa_trx=true






### OrderDetailQuery
### Request
GET http://localhost/api/mitratokopedia/v1/OrderDetailQuery
?pengirim=session1
&paymentId=1882090231

### GetUOHOrderList
### Request
GET http://localhost/api/mitratokopedia/v1/GetUOHOrderList
?pengirim=session1
&vertical_category=mitra
&status=
&searchable_text=
&create_time_start=2021-10-04
&create_time_end=
