### Reseller
GET http://localhost/api/v2/reseller?
### Reseller Downline
GET http://localhost/api/v2/reseller?&kode_reseller=N5700006





### Pengirim
GET http://localhost/api/v2/pengirim?
### Pengirim Downline
GET http://localhost/api/v2/pengirim?&kode_reseller=N5700006





### Downline
GET http://localhost/api/v2/downline?
### Downline Downline
GET http://localhost/api/v2/downline?&kode_reseller=N5700006





### Level
GET http://localhost/api/v2/level?
### Level Downline
GET http://localhost/api/v2/level?&kode_reseller=N5700006





### Operator
GET http://localhost/api/v2/operator?
### Operator Downline
GET http://localhost/api/v2/operator?&kode_reseller=N5700006





### Produk
GET http://localhost/api/v2/produk?&kode_operator=TEST
### Produk Downline
GET http://localhost/api/v2/produk?&kode_reseller=N5700006&kode_operator=TEST





### Mutasi
GET http://localhost/api/v2/mutasi?
### Mutasi Downline
GET http://localhost/api/v2/mutasi?&kode_reseller=N5700006








### Inbox
GET http://localhost/api/v2/inbox?&pesan=cs.











### Outbox (SMS)
GET http://localhost/api/v2/outbox?tipe_penerima=S&penerima=6281935155404&pesan=data
### Outbox (Whatsapp)
GET http://localhost/api/v2/outbox?tipe_penerima=W&penerima=6281935155404&pesan=data
### Outbox (Jabber)
GET http://localhost/api/v2/outbox?tipe_penerima=G&penerima=ndiing2@jabb.im&pesan=data
### Outbox (Telegram)
GET http://localhost/api/v2/outbox?tipe_penerima=Y&penerima=1344008938&pesan=data










### Aktifkan downline/reseller
GET http://localhost/api/v2/aktifkan-dl?&kodereseller=N5700006&pin=1234

### Aktifkan downline/reseller (urlencoded)
POST http://localhost/api/v2/aktifkan-dl
Content-Type: application/x-www-form-urlencoded

&kodereseller=N5700006&pin=1234

### Aktifkan downline/reseller (json)
POST http://localhost/api/v2/aktifkan-dl
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "pin": "1234"
}

### Aktifkan downline/reseller (xml)
POST http://localhost/api/v2/aktifkan-dl
Content-Type: application/xml

<kodereseller>N5700006</kodereseller>
<pin>1234</pin>








### Batalkan transaksi yang belum diproses
GET http://localhost/api/v2/batal-transaksi?&trxid=123456&pin=1234

### Batalkan transaksi yang belum diproses (urlencoded)
POST http://localhost/api/v2/batal-transaksi
Content-Type: application/x-www-form-urlencoded

&trxid=123456&pin=1234

### Batalkan transaksi yang belum diproses (json)
POST http://localhost/api/v2/batal-transaksi
Content-Type: application/json

{
    "trxid": "123456",
    "pin": "1234"
}

### Batalkan transaksi yang belum diproses (xml)
POST http://localhost/api/v2/batal-transaksi
Content-Type: application/xml

<trxid>123456</trxid>
<pin>1234</pin>








### Cancel balance transfer
GET http://localhost/api/v2/batal-transfer-saldo?&kodereseller=N5700006&jumlah=1000000&pin=1234

### Cancel balance transfer (urlencoded)
POST http://localhost/api/v2/batal-transfer-saldo
Content-Type: application/x-www-form-urlencoded

&kodereseller=N5700006&jumlah=1000000&pin=1234

### Cancel balance transfer (json)
POST http://localhost/api/v2/batal-transfer-saldo
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "jumlah": "1000000",
    "pin": "1234"
}

### Cancel balance transfer (xml)
POST http://localhost/api/v2/batal-transfer-saldo
Content-Type: application/xml

<kodereseller>N5700006</kodereseller>
<jumlah>1000000</jumlah>
<pin>1234</pin>








### Cek harga produk
GET http://localhost/api/v2/cek-harga?&kodeproduk=TF

### Cek harga produk (urlencoded)
POST http://localhost/api/v2/cek-harga
Content-Type: application/x-www-form-urlencoded

&kodeproduk=TF

### Cek harga produk (json)
POST http://localhost/api/v2/cek-harga
Content-Type: application/json

{
    "kodeproduk": "TF"
}

### Cek harga produk (xml)
POST http://localhost/api/v2/cek-harga
Content-Type: application/xml

<kodeproduk>TF</kodeproduk>








### Check downline"s markup
GET http://localhost/api/v2/cek-markup?&kodereseller=N5700006&pin=1234

### Check downline"s markup (urlencoded)
POST http://localhost/api/v2/cek-markup
Content-Type: application/x-www-form-urlencoded

&kodereseller=N5700006&pin=1234

### Check downline"s markup (json)
POST http://localhost/api/v2/cek-markup
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "pin": "1234"
}

### Check downline"s markup (xml)
POST http://localhost/api/v2/cek-markup
Content-Type: application/xml

<kodereseller>N5700006</kodereseller>
<pin>1234</pin>








### Check product markup
GET http://localhost/api/v2/cek-markup-produk?&kodereseller=N5700006&kodeproduk=TEST5&pin=1234

### Check product markup (urlencoded)
POST http://localhost/api/v2/cek-markup-produk
Content-Type: application/x-www-form-urlencoded

&kodereseller=N5700006&kodeproduk=TEST5&pin=1234

### Check product markup (json)
POST http://localhost/api/v2/cek-markup-produk
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "kodeproduk": "TEST5",
    "pin": "1234"
}

### Check product markup (xml)
POST http://localhost/api/v2/cek-markup-produk
Content-Type: application/xml

<kodereseller>N5700006</kodereseller>
<kodeproduk>TEST5</kodeproduk>
<pin>1234</pin>








### Check all product markups
GET http://localhost/api/v2/cek-markup-produk2?&kodereseller=N5700006&pin=1234

### Check all product markups (urlencoded)
POST http://localhost/api/v2/cek-markup-produk2
Content-Type: application/x-www-form-urlencoded

&kodereseller=N5700006&pin=1234

### Check all product markups (json)
POST http://localhost/api/v2/cek-markup-produk2
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "pin": "1234"
}

### Check all product markups (xml)
POST http://localhost/api/v2/cek-markup-produk2
Content-Type: application/xml

<kodereseller>N5700006</kodereseller>
<pin>1234</pin>








### Cek N (lihat Setting.LimitCekMutasi) mutasi saldo/deposit terakhir
GET http://localhost/api/v2/cek-mutasi?

### Cek N (lihat Setting.LimitCekMutasi) mutasi saldo/deposit terakhir (urlencoded)
POST http://localhost/api/v2/cek-mutasi
Content-Type: application/x-www-form-urlencoded



### Cek N (lihat Setting.LimitCekMutasi) mutasi saldo/deposit terakhir (json)
POST http://localhost/api/v2/cek-mutasi
Content-Type: application/json

{
}

### Cek N (lihat Setting.LimitCekMutasi) mutasi saldo/deposit terakhir (xml)
POST http://localhost/api/v2/cek-mutasi
Content-Type: application/xml









### Cek mutasi saldo terakhir, khusus manual, tiket, dan transfer saldo
GET http://localhost/api/v2/cek-mutasi2?

### Cek mutasi saldo terakhir, khusus manual, tiket, dan transfer saldo (urlencoded)
POST http://localhost/api/v2/cek-mutasi2
Content-Type: application/x-www-form-urlencoded



### Cek mutasi saldo terakhir, khusus manual, tiket, dan transfer saldo (json)
POST http://localhost/api/v2/cek-mutasi2
Content-Type: application/json

{
}

### Cek mutasi saldo terakhir, khusus manual, tiket, dan transfer saldo (xml)
POST http://localhost/api/v2/cek-mutasi2
Content-Type: application/xml









### Check current OID for OtomaX HTH
GET http://localhost/api/v2/cek-oid?&pin=1234

### Check current OID for OtomaX HTH (urlencoded)
POST http://localhost/api/v2/cek-oid
Content-Type: application/x-www-form-urlencoded

&pin=1234

### Check current OID for OtomaX HTH (json)
POST http://localhost/api/v2/cek-oid
Content-Type: application/json

{
    "pin": "1234"
}

### Check current OID for OtomaX HTH (xml)
POST http://localhost/api/v2/cek-oid
Content-Type: application/xml

<pin>1234</pin>








### Cek saldo akhir
GET http://localhost/api/v2/cek-saldo?&pin=1234

### Cek saldo akhir (urlencoded)
POST http://localhost/api/v2/cek-saldo
Content-Type: application/x-www-form-urlencoded

&pin=1234

### Cek saldo akhir (json)
POST http://localhost/api/v2/cek-saldo
Content-Type: application/json

{
    "pin": "1234"
}

### Cek saldo akhir (xml)
POST http://localhost/api/v2/cek-saldo
Content-Type: application/xml

<pin>1234</pin>








### Cek saldo downline
GET http://localhost/api/v2/cek-saldo-dl?&kodereseller=N5700006

### Cek saldo downline (urlencoded)
POST http://localhost/api/v2/cek-saldo-dl
Content-Type: application/x-www-form-urlencoded

&kodereseller=N5700006

### Cek saldo downline (json)
POST http://localhost/api/v2/cek-saldo-dl
Content-Type: application/json

{
    "kodereseller": "N5700006"
}

### Cek saldo downline (xml)
POST http://localhost/api/v2/cek-saldo-dl
Content-Type: application/xml

<kodereseller>N5700006</kodereseller>








### Cek status transaksi
GET http://localhost/api/v2/cek-status-transaksi?&nomor+tujuan=6281935155111

### Cek status transaksi (urlencoded)
POST http://localhost/api/v2/cek-status-transaksi
Content-Type: application/x-www-form-urlencoded

&nomor+tujuan=6281935155111

### Cek status transaksi (json)
POST http://localhost/api/v2/cek-status-transaksi
Content-Type: application/json

{
    "nomor tujuan": "6281935155111"
}

### Cek status transaksi (xml)
POST http://localhost/api/v2/cek-status-transaksi
Content-Type: application/xml

<nomor tujuan>6281935155111</nomor tujuan>








### Cek status transaksi
GET http://localhost/api/v2/cek-status-transaksi2?&tujuan=6281935155111

### Cek status transaksi (urlencoded)
POST http://localhost/api/v2/cek-status-transaksi2
Content-Type: application/x-www-form-urlencoded

&tujuan=6281935155111

### Cek status transaksi (json)
POST http://localhost/api/v2/cek-status-transaksi2
Content-Type: application/json

{
    "tujuan": "6281935155111"
}

### Cek status transaksi (xml)
POST http://localhost/api/v2/cek-status-transaksi2
Content-Type: application/xml

<tujuan>6281935155111</tujuan>








### Cek status transaksi
GET http://localhost/api/v2/cek-status-transaksi3?&tanggal=20&tujuan=6281935155111

### Cek status transaksi (urlencoded)
POST http://localhost/api/v2/cek-status-transaksi3
Content-Type: application/x-www-form-urlencoded

&tanggal=20&tujuan=6281935155111

### Cek status transaksi (json)
POST http://localhost/api/v2/cek-status-transaksi3
Content-Type: application/json

{
    "tanggal": "20",
    "tujuan": "6281935155111"
}

### Cek status transaksi (xml)
POST http://localhost/api/v2/cek-status-transaksi3
Content-Type: application/xml

<tanggal>20</tanggal>
<tujuan>6281935155111</tujuan>








### Cek status N (lihat Setting.LimitCekTransaksiAkhir) transaksi terakhir
GET http://localhost/api/v2/cek-transaksi-akhir?

### Cek status N (lihat Setting.LimitCekTransaksiAkhir) transaksi terakhir (urlencoded)
POST http://localhost/api/v2/cek-transaksi-akhir
Content-Type: application/x-www-form-urlencoded



### Cek status N (lihat Setting.LimitCekTransaksiAkhir) transaksi terakhir (json)
POST http://localhost/api/v2/cek-transaksi-akhir
Content-Type: application/json

{
}

### Cek status N (lihat Setting.LimitCekTransaksiAkhir) transaksi terakhir (xml)
POST http://localhost/api/v2/cek-transaksi-akhir
Content-Type: application/xml









### Daftarkan downline/reseller baru
GET http://localhost/api/v2/daftar-dl?&nama=Ndiing&alamat=Pacitan&nomorhp=6281935155111&pin=1234

### Daftarkan downline/reseller baru (urlencoded)
POST http://localhost/api/v2/daftar-dl
Content-Type: application/x-www-form-urlencoded

&nama=Ndiing&alamat=Pacitan&nomorhp=6281935155111&pin=1234

### Daftarkan downline/reseller baru (json)
POST http://localhost/api/v2/daftar-dl
Content-Type: application/json

{
    "nama": "Ndiing",
    "alamat": "Pacitan",
    "nomorhp": "6281935155111",
    "pin": "1234"
}

### Daftarkan downline/reseller baru (xml)
POST http://localhost/api/v2/daftar-dl
Content-Type: application/xml

<nama>Ndiing</nama>
<alamat>Pacitan</alamat>
<nomorhp>6281935155111</nomorhp>
<pin>1234</pin>








### Daftarkan downline/reseller baru
GET http://localhost/api/v2/daftar-dl2?&nama=Ndiing&alamat=Pacitan&nomorhp=6281935155111&markup=500&pin=1234

### Daftarkan downline/reseller baru (urlencoded)
POST http://localhost/api/v2/daftar-dl2
Content-Type: application/x-www-form-urlencoded

&nama=Ndiing&alamat=Pacitan&nomorhp=6281935155111&markup=500&pin=1234

### Daftarkan downline/reseller baru (json)
POST http://localhost/api/v2/daftar-dl2
Content-Type: application/json

{
    "nama": "Ndiing",
    "alamat": "Pacitan",
    "nomorhp": "6281935155111",
    "markup": "500",
    "pin": "1234"
}

### Daftarkan downline/reseller baru (xml)
POST http://localhost/api/v2/daftar-dl2
Content-Type: application/xml

<nama>Ndiing</nama>
<alamat>Pacitan</alamat>
<nomorhp>6281935155111</nomorhp>
<markup>500</markup>
<pin>1234</pin>








### Daftarkan downline/reseller baru
GET http://localhost/api/v2/daftar-dl3?&nama=Ndiing&alamat=Pacitan&nomorhp=6281935155111&kodelevel=R&pin=1234

### Daftarkan downline/reseller baru (urlencoded)
POST http://localhost/api/v2/daftar-dl3
Content-Type: application/x-www-form-urlencoded

&nama=Ndiing&alamat=Pacitan&nomorhp=6281935155111&kodelevel=R&pin=1234

### Daftarkan downline/reseller baru (json)
POST http://localhost/api/v2/daftar-dl3
Content-Type: application/json

{
    "nama": "Ndiing",
    "alamat": "Pacitan",
    "nomorhp": "6281935155111",
    "kodelevel": "R",
    "pin": "1234"
}

### Daftarkan downline/reseller baru (xml)
POST http://localhost/api/v2/daftar-dl3
Content-Type: application/xml

<nama>Ndiing</nama>
<alamat>Pacitan</alamat>
<nomorhp>6281935155111</nomorhp>
<kodelevel>R</kodelevel>
<pin>1234</pin>








### Registration of non member
GET http://localhost/api/v2/daftar-non-member?&name=Ndiing&address=Pacitan&pin=1234

### Registration of non member (urlencoded)
POST http://localhost/api/v2/daftar-non-member
Content-Type: application/x-www-form-urlencoded

&name=Ndiing&address=Pacitan&pin=1234

### Registration of non member (json)
POST http://localhost/api/v2/daftar-non-member
Content-Type: application/json

{
    "name": "Ndiing",
    "address": "Pacitan",
    "pin": "1234"
}

### Registration of non member (xml)
POST http://localhost/api/v2/daftar-non-member
Content-Type: application/xml

<name>Ndiing</name>
<address>Pacitan</address>
<pin>1234</pin>








### Hapus pengirim tipe GTalk
GET http://localhost/api/v2/hapus-gtalk?&email=ndiing.inc%40gmail.com&pin=1234

### Hapus pengirim tipe GTalk (urlencoded)
POST http://localhost/api/v2/hapus-gtalk
Content-Type: application/x-www-form-urlencoded

&email=ndiing.inc%40gmail.com&pin=1234

### Hapus pengirim tipe GTalk (json)
POST http://localhost/api/v2/hapus-gtalk
Content-Type: application/json

{
    "email": "ndiing.inc@gmail.com",
    "pin": "1234"
}

### Hapus pengirim tipe GTalk (xml)
POST http://localhost/api/v2/hapus-gtalk
Content-Type: application/xml

<email>ndiing.inc@gmail.com</email>
<pin>1234</pin>








### Hapus pengirim tipe GTalk untuk downline
GET http://localhost/api/v2/hapus-gtalk2?&kodereseller=N5700006&email=ndiing.inc%40gmail.com&pin=1234

### Hapus pengirim tipe GTalk untuk downline (urlencoded)
POST http://localhost/api/v2/hapus-gtalk2
Content-Type: application/x-www-form-urlencoded

&kodereseller=N5700006&email=ndiing.inc%40gmail.com&pin=1234

### Hapus pengirim tipe GTalk untuk downline (json)
POST http://localhost/api/v2/hapus-gtalk2
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "email": "ndiing.inc@gmail.com",
    "pin": "1234"
}

### Hapus pengirim tipe GTalk untuk downline (xml)
POST http://localhost/api/v2/hapus-gtalk2
Content-Type: application/xml

<kodereseller>N5700006</kodereseller>
<email>ndiing.inc@gmail.com</email>
<pin>1234</pin>








### Delete product markup
GET http://localhost/api/v2/hapus-markup-produk?&kodeproduk=TEST5&kodereseller=N5700006&pin=1234

### Delete product markup (urlencoded)
POST http://localhost/api/v2/hapus-markup-produk
Content-Type: application/x-www-form-urlencoded

&kodeproduk=TEST5&kodereseller=N5700006&pin=1234

### Delete product markup (json)
POST http://localhost/api/v2/hapus-markup-produk
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "kodereseller": "N5700006",
    "pin": "1234"
}

### Delete product markup (xml)
POST http://localhost/api/v2/hapus-markup-produk
Content-Type: application/xml

<kodeproduk>TEST5</kodeproduk>
<kodereseller>N5700006</kodereseller>
<pin>1234</pin>








### Delete product markup
GET http://localhost/api/v2/hapus-markup-produk2?&kodereseller=N5700006&pin=1234

### Delete product markup (urlencoded)
POST http://localhost/api/v2/hapus-markup-produk2
Content-Type: application/x-www-form-urlencoded

&kodereseller=N5700006&pin=1234

### Delete product markup (json)
POST http://localhost/api/v2/hapus-markup-produk2
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "pin": "1234"
}

### Delete product markup (xml)
POST http://localhost/api/v2/hapus-markup-produk2
Content-Type: application/xml

<kodereseller>N5700006</kodereseller>
<pin>1234</pin>








### Delete product markup
GET http://localhost/api/v2/hapus-markup-produk3?&kodeproduk=TEST5&pin=1234

### Delete product markup (urlencoded)
POST http://localhost/api/v2/hapus-markup-produk3
Content-Type: application/x-www-form-urlencoded

&kodeproduk=TEST5&pin=1234

### Delete product markup (json)
POST http://localhost/api/v2/hapus-markup-produk3
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "pin": "1234"
}

### Delete product markup (xml)
POST http://localhost/api/v2/hapus-markup-produk3
Content-Type: application/xml

<kodeproduk>TEST5</kodeproduk>
<pin>1234</pin>








### Hapus pengirim tipe SMS
GET http://localhost/api/v2/hapus-nomor?&tujuan=6281935155111&pin=1234

### Hapus pengirim tipe SMS (urlencoded)
POST http://localhost/api/v2/hapus-nomor
Content-Type: application/x-www-form-urlencoded

&tujuan=6281935155111&pin=1234

### Hapus pengirim tipe SMS (json)
POST http://localhost/api/v2/hapus-nomor
Content-Type: application/json

{
    "tujuan": "6281935155111",
    "pin": "1234"
}

### Hapus pengirim tipe SMS (xml)
POST http://localhost/api/v2/hapus-nomor
Content-Type: application/xml

<tujuan>6281935155111</tujuan>
<pin>1234</pin>








### Hapus pengirim tipe SMS
GET http://localhost/api/v2/hapus-nomor2?&kodereseller=N5700006&tujuan=6281935155111&pin=1234

### Hapus pengirim tipe SMS (urlencoded)
POST http://localhost/api/v2/hapus-nomor2
Content-Type: application/x-www-form-urlencoded

&kodereseller=N5700006&tujuan=6281935155111&pin=1234

### Hapus pengirim tipe SMS (json)
POST http://localhost/api/v2/hapus-nomor2
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "tujuan": "6281935155111",
    "pin": "1234"
}

### Hapus pengirim tipe SMS (xml)
POST http://localhost/api/v2/hapus-nomor2
Content-Type: application/xml

<kodereseller>N5700006</kodereseller>
<tujuan>6281935155111</tujuan>
<pin>1234</pin>








### Hapus nomor WA
GET http://localhost/api/v2/hapus-wa?&nomor=6281935155111&pin=1234

### Hapus nomor WA (urlencoded)
POST http://localhost/api/v2/hapus-wa
Content-Type: application/x-www-form-urlencoded

&nomor=6281935155111&pin=1234

### Hapus nomor WA (json)
POST http://localhost/api/v2/hapus-wa
Content-Type: application/json

{
    "nomor": "6281935155111",
    "pin": "1234"
}

### Hapus nomor WA (xml)
POST http://localhost/api/v2/hapus-wa
Content-Type: application/xml

<nomor>6281935155111</nomor>
<pin>1234</pin>








### Hapus pengirim tipe YM
GET http://localhost/api/v2/hapus-ym?&yahooid=ndiing.inc%40yahoo.com&pin=1234

### Hapus pengirim tipe YM (urlencoded)
POST http://localhost/api/v2/hapus-ym
Content-Type: application/x-www-form-urlencoded

&yahooid=ndiing.inc%40yahoo.com&pin=1234

### Hapus pengirim tipe YM (json)
POST http://localhost/api/v2/hapus-ym
Content-Type: application/json

{
    "yahooid": "ndiing.inc@yahoo.com",
    "pin": "1234"
}

### Hapus pengirim tipe YM (xml)
POST http://localhost/api/v2/hapus-ym
Content-Type: application/xml

<yahooid>ndiing.inc@yahoo.com</yahooid>
<pin>1234</pin>








### Hapus pengirim tipe YM dari downline
GET http://localhost/api/v2/hapus-ym2?&kodereseller=N5700006&yahooid=ndiing.inc%40yahoo.com&pin=1234

### Hapus pengirim tipe YM dari downline (urlencoded)
POST http://localhost/api/v2/hapus-ym2
Content-Type: application/x-www-form-urlencoded

&kodereseller=N5700006&yahooid=ndiing.inc%40yahoo.com&pin=1234

### Hapus pengirim tipe YM dari downline (json)
POST http://localhost/api/v2/hapus-ym2
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "yahooid": "ndiing.inc@yahoo.com",
    "pin": "1234"
}

### Hapus pengirim tipe YM dari downline (xml)
POST http://localhost/api/v2/hapus-ym2
Content-Type: application/xml

<kodereseller>N5700006</kodereseller>
<yahooid>ndiing.inc@yahoo.com</yahooid>
<pin>1234</pin>








### Cek laporan mutasi saldo per tanggal
GET http://localhost/api/v2/laporan-mutasi?&tanggal=20

### Cek laporan mutasi saldo per tanggal (urlencoded)
POST http://localhost/api/v2/laporan-mutasi
Content-Type: application/x-www-form-urlencoded

&tanggal=20

### Cek laporan mutasi saldo per tanggal (json)
POST http://localhost/api/v2/laporan-mutasi
Content-Type: application/json

{
    "tanggal": "20"
}

### Cek laporan mutasi saldo per tanggal (xml)
POST http://localhost/api/v2/laporan-mutasi
Content-Type: application/xml

<tanggal>20</tanggal>








### Cek laporan transaksi per tanggal
GET http://localhost/api/v2/laporan-transaksi?&tanggal=20

### Cek laporan transaksi per tanggal (urlencoded)
POST http://localhost/api/v2/laporan-transaksi
Content-Type: application/x-www-form-urlencoded

&tanggal=20

### Cek laporan transaksi per tanggal (json)
POST http://localhost/api/v2/laporan-transaksi
Content-Type: application/json

{
    "tanggal": "20"
}

### Cek laporan transaksi per tanggal (xml)
POST http://localhost/api/v2/laporan-transaksi
Content-Type: application/xml

<tanggal>20</tanggal>








### View gift list
GET http://localhost/api/v2/lihat-hadiah-poin?

### View gift list (urlencoded)
POST http://localhost/api/v2/lihat-hadiah-poin
Content-Type: application/x-www-form-urlencoded



### View gift list (json)
POST http://localhost/api/v2/lihat-hadiah-poin
Content-Type: application/json

{
}

### View gift list (xml)
POST http://localhost/api/v2/lihat-hadiah-poin
Content-Type: application/xml









### Lihat daftar downline
GET http://localhost/api/v2/list-dl?

### Lihat daftar downline (urlencoded)
POST http://localhost/api/v2/list-dl
Content-Type: application/x-www-form-urlencoded



### Lihat daftar downline (json)
POST http://localhost/api/v2/list-dl
Content-Type: application/json

{
}

### Lihat daftar downline (xml)
POST http://localhost/api/v2/list-dl
Content-Type: application/xml









### Lihat daftar downline dari downline (sub-downline)
GET http://localhost/api/v2/list-dl2?&kodereseller=N5700006

### Lihat daftar downline dari downline (sub-downline) (urlencoded)
POST http://localhost/api/v2/list-dl2
Content-Type: application/x-www-form-urlencoded

&kodereseller=N5700006

### Lihat daftar downline dari downline (sub-downline) (json)
POST http://localhost/api/v2/list-dl2
Content-Type: application/json

{
    "kodereseller": "N5700006"
}

### Lihat daftar downline dari downline (sub-downline) (xml)
POST http://localhost/api/v2/list-dl2
Content-Type: application/xml

<kodereseller>N5700006</kodereseller>








### Lihat daftar pengirim semua tipe
GET http://localhost/api/v2/list-pengirim?

### Lihat daftar pengirim semua tipe (urlencoded)
POST http://localhost/api/v2/list-pengirim
Content-Type: application/x-www-form-urlencoded



### Lihat daftar pengirim semua tipe (json)
POST http://localhost/api/v2/list-pengirim
Content-Type: application/json

{
}

### Lihat daftar pengirim semua tipe (xml)
POST http://localhost/api/v2/list-pengirim
Content-Type: application/xml









### Lihat daftar pengirim tipe GTalk
GET http://localhost/api/v2/list-pengirim-gtalk?

### Lihat daftar pengirim tipe GTalk (urlencoded)
POST http://localhost/api/v2/list-pengirim-gtalk
Content-Type: application/x-www-form-urlencoded



### Lihat daftar pengirim tipe GTalk (json)
POST http://localhost/api/v2/list-pengirim-gtalk
Content-Type: application/json

{
}

### Lihat daftar pengirim tipe GTalk (xml)
POST http://localhost/api/v2/list-pengirim-gtalk
Content-Type: application/xml









### Lihat daftar pengirim tipe GTalk untuk downline
GET http://localhost/api/v2/list-pengirim-gtalk2?&kodereseller=N5700006

### Lihat daftar pengirim tipe GTalk untuk downline (urlencoded)
POST http://localhost/api/v2/list-pengirim-gtalk2
Content-Type: application/x-www-form-urlencoded

&kodereseller=N5700006

### Lihat daftar pengirim tipe GTalk untuk downline (json)
POST http://localhost/api/v2/list-pengirim-gtalk2
Content-Type: application/json

{
    "kodereseller": "N5700006"
}

### Lihat daftar pengirim tipe GTalk untuk downline (xml)
POST http://localhost/api/v2/list-pengirim-gtalk2
Content-Type: application/xml

<kodereseller>N5700006</kodereseller>








### Lihat daftar pengirim tipe SMS
GET http://localhost/api/v2/list-pengirim-sms?

### Lihat daftar pengirim tipe SMS (urlencoded)
POST http://localhost/api/v2/list-pengirim-sms
Content-Type: application/x-www-form-urlencoded



### Lihat daftar pengirim tipe SMS (json)
POST http://localhost/api/v2/list-pengirim-sms
Content-Type: application/json

{
}

### Lihat daftar pengirim tipe SMS (xml)
POST http://localhost/api/v2/list-pengirim-sms
Content-Type: application/xml









### Lihat daftar pengirim tipe SMS dari downline
GET http://localhost/api/v2/list-pengirim-sms2?&kodereseller=N5700006

### Lihat daftar pengirim tipe SMS dari downline (urlencoded)
POST http://localhost/api/v2/list-pengirim-sms2
Content-Type: application/x-www-form-urlencoded

&kodereseller=N5700006

### Lihat daftar pengirim tipe SMS dari downline (json)
POST http://localhost/api/v2/list-pengirim-sms2
Content-Type: application/json

{
    "kodereseller": "N5700006"
}

### Lihat daftar pengirim tipe SMS dari downline (xml)
POST http://localhost/api/v2/list-pengirim-sms2
Content-Type: application/xml

<kodereseller>N5700006</kodereseller>








### Lihat daftar pengirim tipe YM
GET http://localhost/api/v2/list-pengirim-ym?

### Lihat daftar pengirim tipe YM (urlencoded)
POST http://localhost/api/v2/list-pengirim-ym
Content-Type: application/x-www-form-urlencoded



### Lihat daftar pengirim tipe YM (json)
POST http://localhost/api/v2/list-pengirim-ym
Content-Type: application/json

{
}

### Lihat daftar pengirim tipe YM (xml)
POST http://localhost/api/v2/list-pengirim-ym
Content-Type: application/xml









### Lihat daftar pengirim tipe YM dari downline
GET http://localhost/api/v2/list-pengirim-ym2?&kodereseller=N5700006

### Lihat daftar pengirim tipe YM dari downline (urlencoded)
POST http://localhost/api/v2/list-pengirim-ym2
Content-Type: application/x-www-form-urlencoded

&kodereseller=N5700006

### Lihat daftar pengirim tipe YM dari downline (json)
POST http://localhost/api/v2/list-pengirim-ym2
Content-Type: application/json

{
    "kodereseller": "N5700006"
}

### Lihat daftar pengirim tipe YM dari downline (xml)
POST http://localhost/api/v2/list-pengirim-ym2
Content-Type: application/xml

<kodereseller>N5700006</kodereseller>








### Non-aktifkan downline/reseller
GET http://localhost/api/v2/non-aktifkan-dl?&kodereseller=N5700006&pin=1234

### Non-aktifkan downline/reseller (urlencoded)
POST http://localhost/api/v2/non-aktifkan-dl
Content-Type: application/x-www-form-urlencoded

&kodereseller=N5700006&pin=1234

### Non-aktifkan downline/reseller (json)
POST http://localhost/api/v2/non-aktifkan-dl
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "pin": "1234"
}

### Non-aktifkan downline/reseller (xml)
POST http://localhost/api/v2/non-aktifkan-dl
Content-Type: application/xml

<kodereseller>N5700006</kodereseller>
<pin>1234</pin>








### Reset pin member
GET http://localhost/api/v2/reset-pin?&kodereseller=N5700006&pin=1234

### Reset pin member (urlencoded)
POST http://localhost/api/v2/reset-pin
Content-Type: application/x-www-form-urlencoded

&kodereseller=N5700006&pin=1234

### Reset pin member (json)
POST http://localhost/api/v2/reset-pin
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "pin": "1234"
}

### Reset pin member (xml)
POST http://localhost/api/v2/reset-pin
Content-Type: application/xml

<kodereseller>N5700006</kodereseller>
<pin>1234</pin>








### Tambah pengirim tipe GTalk
GET http://localhost/api/v2/tambah-gtalk?&email=ndiing.inc%40gmail.com&pin=1234

### Tambah pengirim tipe GTalk (urlencoded)
POST http://localhost/api/v2/tambah-gtalk
Content-Type: application/x-www-form-urlencoded

&email=ndiing.inc%40gmail.com&pin=1234

### Tambah pengirim tipe GTalk (json)
POST http://localhost/api/v2/tambah-gtalk
Content-Type: application/json

{
    "email": "ndiing.inc@gmail.com",
    "pin": "1234"
}

### Tambah pengirim tipe GTalk (xml)
POST http://localhost/api/v2/tambah-gtalk
Content-Type: application/xml

<email>ndiing.inc@gmail.com</email>
<pin>1234</pin>








### Tambah pengirim tipe GTalk untuk downline
GET http://localhost/api/v2/tambah-gtalk2?&kodereseller=N5700006&email=ndiing.inc%40gmail.com&pin=1234

### Tambah pengirim tipe GTalk untuk downline (urlencoded)
POST http://localhost/api/v2/tambah-gtalk2
Content-Type: application/x-www-form-urlencoded

&kodereseller=N5700006&email=ndiing.inc%40gmail.com&pin=1234

### Tambah pengirim tipe GTalk untuk downline (json)
POST http://localhost/api/v2/tambah-gtalk2
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "email": "ndiing.inc@gmail.com",
    "pin": "1234"
}

### Tambah pengirim tipe GTalk untuk downline (xml)
POST http://localhost/api/v2/tambah-gtalk2
Content-Type: application/xml

<kodereseller>N5700006</kodereseller>
<email>ndiing.inc@gmail.com</email>
<pin>1234</pin>








### Tambah pengirim tipe SMS
GET http://localhost/api/v2/tambah-nomor?&tujuan=6281935155111&pin=1234

### Tambah pengirim tipe SMS (urlencoded)
POST http://localhost/api/v2/tambah-nomor
Content-Type: application/x-www-form-urlencoded

&tujuan=6281935155111&pin=1234

### Tambah pengirim tipe SMS (json)
POST http://localhost/api/v2/tambah-nomor
Content-Type: application/json

{
    "tujuan": "6281935155111",
    "pin": "1234"
}

### Tambah pengirim tipe SMS (xml)
POST http://localhost/api/v2/tambah-nomor
Content-Type: application/xml

<tujuan>6281935155111</tujuan>
<pin>1234</pin>








### Tambah pengirim tipe SMS untuk downline
GET http://localhost/api/v2/tambah-nomor2?&kodereseller=N5700006&tujuan=6281935155111&pin=1234

### Tambah pengirim tipe SMS untuk downline (urlencoded)
POST http://localhost/api/v2/tambah-nomor2
Content-Type: application/x-www-form-urlencoded

&kodereseller=N5700006&tujuan=6281935155111&pin=1234

### Tambah pengirim tipe SMS untuk downline (json)
POST http://localhost/api/v2/tambah-nomor2
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "tujuan": "6281935155111",
    "pin": "1234"
}

### Tambah pengirim tipe SMS untuk downline (xml)
POST http://localhost/api/v2/tambah-nomor2
Content-Type: application/xml

<kodereseller>N5700006</kodereseller>
<tujuan>6281935155111</tujuan>
<pin>1234</pin>








### Tambah nomor WA
GET http://localhost/api/v2/tambah-wa?&number=6281935155111&pin=1234

### Tambah nomor WA (urlencoded)
POST http://localhost/api/v2/tambah-wa
Content-Type: application/x-www-form-urlencoded

&number=6281935155111&pin=1234

### Tambah nomor WA (json)
POST http://localhost/api/v2/tambah-wa
Content-Type: application/json

{
    "number": "6281935155111",
    "pin": "1234"
}

### Tambah nomor WA (xml)
POST http://localhost/api/v2/tambah-wa
Content-Type: application/xml

<number>6281935155111</number>
<pin>1234</pin>








### Tambah pengirim tipe YM
GET http://localhost/api/v2/tambah-ym?&yahooid=ndiing.inc%40yahoo.com&pin=1234

### Tambah pengirim tipe YM (urlencoded)
POST http://localhost/api/v2/tambah-ym
Content-Type: application/x-www-form-urlencoded

&yahooid=ndiing.inc%40yahoo.com&pin=1234

### Tambah pengirim tipe YM (json)
POST http://localhost/api/v2/tambah-ym
Content-Type: application/json

{
    "yahooid": "ndiing.inc@yahoo.com",
    "pin": "1234"
}

### Tambah pengirim tipe YM (xml)
POST http://localhost/api/v2/tambah-ym
Content-Type: application/xml

<yahooid>ndiing.inc@yahoo.com</yahooid>
<pin>1234</pin>








### Tambah pengirim tipe YM untuk downline
GET http://localhost/api/v2/tambah-ym2?&kodereseller=N5700006&yahooid=ndiing.inc%40yahoo.com&pin=1234

### Tambah pengirim tipe YM untuk downline (urlencoded)
POST http://localhost/api/v2/tambah-ym2
Content-Type: application/x-www-form-urlencoded

&kodereseller=N5700006&yahooid=ndiing.inc%40yahoo.com&pin=1234

### Tambah pengirim tipe YM untuk downline (json)
POST http://localhost/api/v2/tambah-ym2
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "yahooid": "ndiing.inc@yahoo.com",
    "pin": "1234"
}

### Tambah pengirim tipe YM untuk downline (xml)
POST http://localhost/api/v2/tambah-ym2
Content-Type: application/xml

<kodereseller>N5700006</kodereseller>
<yahooid>ndiing.inc@yahoo.com</yahooid>
<pin>1234</pin>








### Tiket Deposit
GET http://localhost/api/v2/tiket-deposit?&jumlah=1000000&pin=1234

### Tiket Deposit (urlencoded)
POST http://localhost/api/v2/tiket-deposit
Content-Type: application/x-www-form-urlencoded

&jumlah=1000000&pin=1234

### Tiket Deposit (json)
POST http://localhost/api/v2/tiket-deposit
Content-Type: application/json

{
    "jumlah": "1000000",
    "pin": "1234"
}

### Tiket Deposit (xml)
POST http://localhost/api/v2/tiket-deposit
Content-Type: application/xml

<jumlah>1000000</jumlah>
<pin>1234</pin>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi?&kodeproduk=TEST5&tujuan=6281935155111&pin=1234

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi
Content-Type: application/x-www-form-urlencoded

&kodeproduk=TEST5&tujuan=6281935155111&pin=1234

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "tujuan": "6281935155111",
    "pin": "1234"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi
Content-Type: application/xml

<kodeproduk>TEST5</kodeproduk>
<tujuan>6281935155111</tujuan>
<pin>1234</pin>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi10?&kodeproduk=TEST5&tujuan=6281935155111&pin=1234

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi10
Content-Type: application/x-www-form-urlencoded

&kodeproduk=TEST5&tujuan=6281935155111&pin=1234

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi10
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "tujuan": "6281935155111",
    "pin": "1234"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi10
Content-Type: application/xml

<kodeproduk>TEST5</kodeproduk>
<tujuan>6281935155111</tujuan>
<pin>1234</pin>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi11?&nominal=100&tujuan=6281935155111&pin=1234

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi11
Content-Type: application/x-www-form-urlencoded

&nominal=100&tujuan=6281935155111&pin=1234

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi11
Content-Type: application/json

{
    "nominal": "100",
    "tujuan": "6281935155111",
    "pin": "1234"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi11
Content-Type: application/xml

<nominal>100</nominal>
<tujuan>6281935155111</tujuan>
<pin>1234</pin>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi12?&tujuan=6281935155111&nominal=100&pin=1234

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi12
Content-Type: application/x-www-form-urlencoded

&tujuan=6281935155111&nominal=100&pin=1234

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi12
Content-Type: application/json

{
    "tujuan": "6281935155111",
    "nominal": "100",
    "pin": "1234"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi12
Content-Type: application/xml

<tujuan>6281935155111</tujuan>
<nominal>100</nominal>
<pin>1234</pin>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi13?&tujuan=6281935155111&kodeproduk=TEST5&pin=1234

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi13
Content-Type: application/x-www-form-urlencoded

&tujuan=6281935155111&kodeproduk=TEST5&pin=1234

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi13
Content-Type: application/json

{
    "tujuan": "6281935155111",
    "kodeproduk": "TEST5",
    "pin": "1234"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi13
Content-Type: application/xml

<tujuan>6281935155111</tujuan>
<kodeproduk>TEST5</kodeproduk>
<pin>1234</pin>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi14?&kodeproduk=TEST5&counter=1&tujuan=6281935155111&pin=1234

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi14
Content-Type: application/x-www-form-urlencoded

&kodeproduk=TEST5&counter=1&tujuan=6281935155111&pin=1234

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi14
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "counter": "21",
    "tujuan": "6281935155111",
    "pin": "1234"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi14
Content-Type: application/xml

<kodeproduk>TEST5</kodeproduk>
<counter>1</counter>
<tujuan>6281935155111</tujuan>
<pin>1234</pin>






### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi15?&tujuan=6281935155111&nominal=100&counter=1&pin=1234

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi15
Content-Type: application/x-www-form-urlencoded

&tujuan=6281935155111&nominal=100&counter=1&pin=1234

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi15
Content-Type: application/json

{
    "tujuan": "6281935155111",
    "nominal": "100",
    "counter": "1",
    "pin": "1234"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi15
Content-Type: application/xml

<tujuan>6281935155111</tujuan>
<nominal>100</nominal>
<counter>1</counter>
<pin>1234</pin>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi16?&nominal=100&tujuan=6281935155111&pin=1234

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi16
Content-Type: application/x-www-form-urlencoded

&nominal=100&tujuan=6281935155111&pin=1234

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi16
Content-Type: application/json

{
    "nominal": "100",
    "tujuan": "6281935155111",
    "pin": "1234"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi16
Content-Type: application/xml

<nominal>100</nominal>
<tujuan>6281935155111</tujuan>
<pin>1234</pin>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi17?&tujuan=6281935155111&nominal=100&pin=1234

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi17
Content-Type: application/x-www-form-urlencoded

&tujuan=6281935155111&nominal=100&pin=1234

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi17
Content-Type: application/json

{
    "tujuan": "6281935155111",
    "nominal": "100",
    "pin": "1234"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi17
Content-Type: application/xml

<tujuan>6281935155111</tujuan>
<nominal>100</nominal>
<pin>1234</pin>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi18?&tujuan=6281935155111&kodeproduk=TEST5&pin=1234

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi18
Content-Type: application/x-www-form-urlencoded

&tujuan=6281935155111&kodeproduk=TEST5&pin=1234

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi18
Content-Type: application/json

{
    "tujuan": "6281935155111",
    "kodeproduk": "TEST5",
    "pin": "1234"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi18
Content-Type: application/xml

<tujuan>6281935155111</tujuan>
<kodeproduk>TEST5</kodeproduk>
<pin>1234</pin>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi19?&kodeproduk=TEST5&tujuan=6281935155111&pin=1234

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi19
Content-Type: application/x-www-form-urlencoded

&kodeproduk=TEST5&tujuan=6281935155111&pin=1234

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi19
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "tujuan": "6281935155111",
    "pin": "1234"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi19
Content-Type: application/xml

<kodeproduk>TEST5</kodeproduk>
<tujuan>6281935155111</tujuan>
<pin>1234</pin>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi2?&kodeproduk=TEST5&tujuan=6281935155111&pin=1234

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi2
Content-Type: application/x-www-form-urlencoded

&kodeproduk=TEST5&tujuan=6281935155111&pin=1234

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi2
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "tujuan": "6281935155111",
    "pin": "1234"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi2
Content-Type: application/xml

<kodeproduk>TEST5</kodeproduk>
<tujuan>6281935155111</tujuan>
<pin>1234</pin>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi20?&nominal=100&tujuan=6281935155111&pin=1234

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi20
Content-Type: application/x-www-form-urlencoded

&nominal=100&tujuan=6281935155111&pin=1234

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi20
Content-Type: application/json

{
    "nominal": "100",
    "tujuan": "6281935155111",
    "pin": "1234"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi20
Content-Type: application/xml

<nominal>100</nominal>
<tujuan>6281935155111</tujuan>
<pin>1234</pin>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi21?&tujuan=6281935155111&nominal=100&pin=1234

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi21
Content-Type: application/x-www-form-urlencoded

&tujuan=6281935155111&nominal=100&pin=1234

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi21
Content-Type: application/json

{
    "tujuan": "6281935155111",
    "nominal": "100",
    "pin": "1234"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi21
Content-Type: application/xml

<tujuan>6281935155111</tujuan>
<nominal>100</nominal>
<pin>1234</pin>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi22?&tujuan=6281935155111&kodeproduk=TEST5&pin=1234

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi22
Content-Type: application/x-www-form-urlencoded

&tujuan=6281935155111&kodeproduk=TEST5&pin=1234

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi22
Content-Type: application/json

{
    "tujuan": "6281935155111",
    "kodeproduk": "TEST5",
    "pin": "1234"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi22
Content-Type: application/xml

<tujuan>6281935155111</tujuan>
<kodeproduk>TEST5</kodeproduk>
<pin>1234</pin>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi23?&kodeproduk=TEST5&qty=1&tujuan=6281935155111&pin=1234

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi23
Content-Type: application/x-www-form-urlencoded

&kodeproduk=TEST5&qty=1&tujuan=6281935155111&pin=1234

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi23
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "qty": "1",
    "tujuan": "6281935155111",
    "pin": "1234"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi23
Content-Type: application/xml

<kodeproduk>TEST5</kodeproduk>
<qty>1</qty>
<tujuan>6281935155111</tujuan>
<pin>1234</pin>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi24?&kodeproduk=TEST5&qty=1&tujuan=6281935155111&pin=1234&counter=1

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi24
Content-Type: application/x-www-form-urlencoded

&kodeproduk=TEST5&qty=1&tujuan=6281935155111&pin=1234&counter=1

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi24
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "qty": "1",
    "tujuan": "6281935155111",
    "pin": "1234",
    "counter": "1"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi24
Content-Type: application/xml

<kodeproduk>TEST5</kodeproduk>
<qty>1</qty>
<tujuan>6281935155111</tujuan>
<pin>1234</pin>
<counter>1</counter>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi25?&kodeproduk=TEST5&tujuan=6281935155111&pin=1234&trxid=123456

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi25
Content-Type: application/x-www-form-urlencoded

&kodeproduk=TEST5&tujuan=6281935155111&pin=1234&trxid=123456

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi25
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "tujuan": "6281935155111",
    "pin": "1234",
    "trxid": "123456"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi25
Content-Type: application/xml

<kodeproduk>TEST5</kodeproduk>
<tujuan>6281935155111</tujuan>
<pin>1234</pin>
<trxid>123456</trxid>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi26?&kodeproduk=TEST5&tujuan=6281935155111&pin=1234&enduser=6281935155111

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi26
Content-Type: application/x-www-form-urlencoded

&kodeproduk=TEST5&tujuan=6281935155111&pin=1234&enduser=6281935155111

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi26
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "tujuan": "6281935155111",
    "pin": "1234",
    "enduser": "6281935155111"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi26
Content-Type: application/xml

<kodeproduk>TEST5</kodeproduk>
<tujuan>6281935155111</tujuan>
<pin>1234</pin>
<enduser>6281935155111</enduser>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi27?

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi27
Content-Type: application/x-www-form-urlencoded



### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi27
Content-Type: application/json

{
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi27
Content-Type: application/xml









### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi28?&nominal=100&counter=1&tujuan=6281935155111&pin=1234

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi28
Content-Type: application/x-www-form-urlencoded

&nominal=100&counter=1&tujuan=6281935155111&pin=1234

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi28
Content-Type: application/json

{
    "nominal": "100",
    "counter": "1",
    "tujuan": "6281935155111",
    "pin": "1234"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi28
Content-Type: application/xml

<nominal>100</nominal>
<counter>1</counter>
<tujuan>6281935155111</tujuan>
<pin>1234</pin>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi29?&kodeproduk=TEST5&qty=1&tujuan=6281935155111&pin=1234

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi29
Content-Type: application/x-www-form-urlencoded

&kodeproduk=TEST5&qty=1&tujuan=6281935155111&pin=1234

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi29
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "qty": "1",
    "tujuan": "6281935155111",
    "pin": "1234"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi29
Content-Type: application/xml

<kodeproduk>TEST5</kodeproduk>
<qty>1</qty>
<tujuan>6281935155111</tujuan>
<pin>1234</pin>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi3?&counter=1&kodeproduk=TEST5&qty=1&tujuan=6281935155111&pin=1234

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi3
Content-Type: application/x-www-form-urlencoded

&counter=1&kodeproduk=TEST5&qty=1&tujuan=6281935155111&pin=1234

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi3
Content-Type: application/json

{
    "counter": "1",
    "kodeproduk": "TEST5",
    "qty": "1",
    "tujuan": "6281935155111",
    "pin": "1234"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi3
Content-Type: application/xml

<counter>1</counter>
<kodeproduk>TEST5</kodeproduk>
<qty>1</qty>
<tujuan>6281935155111</tujuan>
<pin>1234</pin>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi4?&kodeproduk=TEST5&nominal=100&tujuan=6281935155111&pin=1234&enduser=6281935155111

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi4
Content-Type: application/x-www-form-urlencoded

&kodeproduk=TEST5&nominal=100&tujuan=6281935155111&pin=1234&enduser=6281935155111

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi4
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "nominal": "100",
    "tujuan": "6281935155111",
    "pin": "1234",
    "enduser": "6281935155111"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi4
Content-Type: application/xml

<kodeproduk>TEST5</kodeproduk>
<nominal>100</nominal>
<tujuan>6281935155111</tujuan>
<pin>1234</pin>
<enduser>6281935155111</enduser>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi5?

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi5
Content-Type: application/x-www-form-urlencoded



### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi5
Content-Type: application/json

{
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi5
Content-Type: application/xml









### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi6?&kodeproduk=TEST5&pin=1234

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi6
Content-Type: application/x-www-form-urlencoded

&kodeproduk=TEST5&pin=1234

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi6
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "pin": "1234"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi6
Content-Type: application/xml

<kodeproduk>TEST5</kodeproduk>
<pin>1234</pin>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi7?&nominal=100

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi7
Content-Type: application/x-www-form-urlencoded

&nominal=100

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi7
Content-Type: application/json

{
    "nominal": "100"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi7
Content-Type: application/xml

<nominal>100</nominal>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi8?&kodeproduk=TEST5

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi8
Content-Type: application/x-www-form-urlencoded

&kodeproduk=TEST5

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi8
Content-Type: application/json

{
    "kodeproduk": "TEST5"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi8
Content-Type: application/xml

<kodeproduk>TEST5</kodeproduk>








### Transaksi pengisian pulsa
GET http://localhost/api/v2/transaksi9?&nominal=100&pin=1234

### Transaksi pengisian pulsa (urlencoded)
POST http://localhost/api/v2/transaksi9
Content-Type: application/x-www-form-urlencoded

&nominal=100&pin=1234

### Transaksi pengisian pulsa (json)
POST http://localhost/api/v2/transaksi9
Content-Type: application/json

{
    "nominal": "100",
    "pin": "1234"
}

### Transaksi pengisian pulsa (xml)
POST http://localhost/api/v2/transaksi9
Content-Type: application/xml

<nominal>100</nominal>
<pin>1234</pin>








### Transaksi pengisian pulsa TANPA pengecekan dobel
GET http://localhost/api/v2/transaksi-bebas-dobel?

### Transaksi pengisian pulsa TANPA pengecekan dobel (urlencoded)
POST http://localhost/api/v2/transaksi-bebas-dobel
Content-Type: application/x-www-form-urlencoded



### Transaksi pengisian pulsa TANPA pengecekan dobel (json)
POST http://localhost/api/v2/transaksi-bebas-dobel
Content-Type: application/json

{
}

### Transaksi pengisian pulsa TANPA pengecekan dobel (xml)
POST http://localhost/api/v2/transaksi-bebas-dobel
Content-Type: application/xml









### Transfer saldo/deposit ke downline/reseller
GET http://localhost/api/v2/transfer-saldo?&kodereseller=N5700006&jumlah=1000000&pin=1234

### Transfer saldo/deposit ke downline/reseller (urlencoded)
POST http://localhost/api/v2/transfer-saldo
Content-Type: application/x-www-form-urlencoded

&kodereseller=N5700006&jumlah=1000000&pin=1234

### Transfer saldo/deposit ke downline/reseller (json)
POST http://localhost/api/v2/transfer-saldo
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "jumlah": "1000000",
    "pin": "1234"
}

### Transfer saldo/deposit ke downline/reseller (xml)
POST http://localhost/api/v2/transfer-saldo
Content-Type: application/xml

<kodereseller>N5700006</kodereseller>
<jumlah>1000000</jumlah>
<pin>1234</pin>








### Allows transfer balance across the membership network
GET http://localhost/api/v2/transfer-saldo-lintas?

### Allows transfer balance across the membership network (urlencoded)
POST http://localhost/api/v2/transfer-saldo-lintas
Content-Type: application/x-www-form-urlencoded



### Allows transfer balance across the membership network (json)
POST http://localhost/api/v2/transfer-saldo-lintas
Content-Type: application/json

{
}

### Allows transfer balance across the membership network (xml)
POST http://localhost/api/v2/transfer-saldo-lintas
Content-Type: application/xml









### Tukar komisi tunda dalam bentuk deposit
GET http://localhost/api/v2/tukar-komisi?&jumlah=1000000&pin=1234

### Tukar komisi tunda dalam bentuk deposit (urlencoded)
POST http://localhost/api/v2/tukar-komisi
Content-Type: application/x-www-form-urlencoded

&jumlah=1000000&pin=1234

### Tukar komisi tunda dalam bentuk deposit (json)
POST http://localhost/api/v2/tukar-komisi
Content-Type: application/json

{
    "jumlah": "1000000",
    "pin": "1234"
}

### Tukar komisi tunda dalam bentuk deposit (xml)
POST http://localhost/api/v2/tukar-komisi
Content-Type: application/xml

<jumlah>1000000</jumlah>
<pin>1234</pin>








### Tukar semua komisi tunda dalam bentuk deposit
GET http://localhost/api/v2/tukar-komisi2?

### Tukar semua komisi tunda dalam bentuk deposit (urlencoded)
POST http://localhost/api/v2/tukar-komisi2
Content-Type: application/x-www-form-urlencoded



### Tukar semua komisi tunda dalam bentuk deposit (json)
POST http://localhost/api/v2/tukar-komisi2
Content-Type: application/json

{
}

### Tukar semua komisi tunda dalam bentuk deposit (xml)
POST http://localhost/api/v2/tukar-komisi2
Content-Type: application/xml









### Menukar poin
GET http://localhost/api/v2/tukar-poin?&kode=TEST5&pin=1234

### Menukar poin (urlencoded)
POST http://localhost/api/v2/tukar-poin
Content-Type: application/x-www-form-urlencoded

&kode=TEST5&pin=1234

### Menukar poin (json)
POST http://localhost/api/v2/tukar-poin
Content-Type: application/json

{
    "kode": "TEST5",
    "pin": "1234"
}

### Menukar poin (xml)
POST http://localhost/api/v2/tukar-poin
Content-Type: application/xml

<kode>TEST5</kode>
<pin>1234</pin>








### Change IP Address
GET http://localhost/api/v2/ubah-alamat-ip?&newip=127.0.0.1&pin=1234

### Change IP Address (urlencoded)
POST http://localhost/api/v2/ubah-alamat-ip
Content-Type: application/x-www-form-urlencoded

&newip=127.0.0.1&pin=1234

### Change IP Address (json)
POST http://localhost/api/v2/ubah-alamat-ip
Content-Type: application/json

{
    "newip": "127.0.0.1",
    "pin": "1234"
}

### Change IP Address (xml)
POST http://localhost/api/v2/ubah-alamat-ip
Content-Type: application/xml

<newip>127.0.0.1</newip>
<pin>1234</pin>








### Ubah level downline
GET http://localhost/api/v2/ubah-level?&kodereseller=N5700006&kodelevel=R&pin=1234

### Ubah level downline (urlencoded)
POST http://localhost/api/v2/ubah-level
Content-Type: application/x-www-form-urlencoded

&kodereseller=N5700006&kodelevel=R&pin=1234

### Ubah level downline (json)
POST http://localhost/api/v2/ubah-level
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "kodelevel": "R",
    "pin": "1234"
}

### Ubah level downline (xml)
POST http://localhost/api/v2/ubah-level
Content-Type: application/xml

<kodereseller>N5700006</kodereseller>
<kodelevel>R</kodelevel>
<pin>1234</pin>








### Change downline"s markup
GET http://localhost/api/v2/ubah-markup?&kodereseller=N5700006&markup=500&pin=1234

### Change downline"s markup (urlencoded)
POST http://localhost/api/v2/ubah-markup
Content-Type: application/x-www-form-urlencoded

&kodereseller=N5700006&markup=500&pin=1234

### Change downline"s markup (json)
POST http://localhost/api/v2/ubah-markup
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "markup": "500",
    "pin": "1234"
}

### Change downline"s markup (xml)
POST http://localhost/api/v2/ubah-markup
Content-Type: application/xml

<kodereseller>N5700006</kodereseller>
<markup>500</markup>
<pin>1234</pin>








### Change product markup
GET http://localhost/api/v2/ubah-markup-produk?&kodeproduk=TEST5&markup=500&kodereseller=N5700006&pin=1234

### Change product markup (urlencoded)
POST http://localhost/api/v2/ubah-markup-produk
Content-Type: application/x-www-form-urlencoded

&kodeproduk=TEST5&markup=500&kodereseller=N5700006&pin=1234

### Change product markup (json)
POST http://localhost/api/v2/ubah-markup-produk
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "markup": "500",
    "kodereseller": "N5700006",
    "pin": "1234"
}

### Change product markup (xml)
POST http://localhost/api/v2/ubah-markup-produk
Content-Type: application/xml

<kodeproduk>TEST5</kodeproduk>
<markup>500</markup>
<kodereseller>N5700006</kodereseller>
<pin>1234</pin>








### Change product markup for all downlines
GET http://localhost/api/v2/ubah-markup-produk2?&kodeproduk=TEST5&markup=500&pin=1234

### Change product markup for all downlines (urlencoded)
POST http://localhost/api/v2/ubah-markup-produk2
Content-Type: application/x-www-form-urlencoded

&kodeproduk=TEST5&markup=500&pin=1234

### Change product markup for all downlines (json)
POST http://localhost/api/v2/ubah-markup-produk2
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "markup": "500",
    "pin": "1234"
}

### Change product markup for all downlines (xml)
POST http://localhost/api/v2/ubah-markup-produk2
Content-Type: application/xml

<kodeproduk>TEST5</kodeproduk>
<markup>500</markup>
<pin>1234</pin>








### Ubah nama
GET http://localhost/api/v2/ubah-nama?&nama=Ndiing&pin=1234

### Ubah nama (urlencoded)
POST http://localhost/api/v2/ubah-nama
Content-Type: application/x-www-form-urlencoded

&nama=Ndiing&pin=1234

### Ubah nama (json)
POST http://localhost/api/v2/ubah-nama
Content-Type: application/json

{
    "nama": "Ndiing",
    "pin": "1234"
}

### Ubah nama (xml)
POST http://localhost/api/v2/ubah-nama
Content-Type: application/xml

<nama>Ndiing</nama>
<pin>1234</pin>








### Change OID for OtomaX HTH
GET http://localhost/api/v2/ubah-oid?&oid=987987654654321321741741852963&pin=1234

### Change OID for OtomaX HTH (urlencoded)
POST http://localhost/api/v2/ubah-oid
Content-Type: application/x-www-form-urlencoded

&oid=987987654654321321741741852963&pin=1234

### Change OID for OtomaX HTH (json)
POST http://localhost/api/v2/ubah-oid
Content-Type: application/json

{
    "oid": "987987654654321321741741852963",
    "pin": "1234"
}

### Change OID for OtomaX HTH (xml)
POST http://localhost/api/v2/ubah-oid
Content-Type: application/xml

<oid>987987654654321321741741852963</oid>
<pin>1234</pin>








### Change IP Password
GET http://localhost/api/v2/ubah-password-ip?&oldpassword=1234&newpassword=1234&pin=1234

### Change IP Password (urlencoded)
POST http://localhost/api/v2/ubah-password-ip
Content-Type: application/x-www-form-urlencoded

&oldpassword=1234&newpassword=1234&pin=1234

### Change IP Password (json)
POST http://localhost/api/v2/ubah-password-ip
Content-Type: application/json

{
    "oldpassword": "1234",
    "newpassword": "1234",
    "pin": "1234"
}

### Change IP Password (xml)
POST http://localhost/api/v2/ubah-password-ip
Content-Type: application/xml

<oldpassword>1234</oldpassword>
<newpassword>1234</newpassword>
<pin>1234</pin>








### Ubah PIN
GET http://localhost/api/v2/ubah-pin?&pinlama=1234&pinbaru=1234

### Ubah PIN (urlencoded)
POST http://localhost/api/v2/ubah-pin
Content-Type: application/x-www-form-urlencoded

&pinlama=1234&pinbaru=1234

### Ubah PIN (json)
POST http://localhost/api/v2/ubah-pin
Content-Type: application/json

{
    "pinlama": "1234",
    "pinbaru": "1234"
}

### Ubah PIN (xml)
POST http://localhost/api/v2/ubah-pin
Content-Type: application/xml

<pinlama>1234</pinlama>
<pinbaru>1234</pinbaru>








### Change Report URL
GET http://localhost/api/v2/ubah-report-url?&newurl=http%3A%2F%2Fndiing.ddns.net%2Freport&pin=1234

### Change Report URL (urlencoded)
POST http://localhost/api/v2/ubah-report-url
Content-Type: application/x-www-form-urlencoded

&newurl=http%3A%2F%2Fndiing.ddns.net%2Freport&pin=1234

### Change Report URL (json)
POST http://localhost/api/v2/ubah-report-url
Content-Type: application/json

{
    "newurl": "http://ndiing.ddns.net/report",
    "pin": "1234"
}

### Change Report URL (xml)
POST http://localhost/api/v2/ubah-report-url
Content-Type: application/xml

<newurl>http://localhost/api/v2/test</newurl>
<pin>1234</pin>








