### Aktifkan downline/reseller
POST http://localhost/api/v1/aktifkan-dl?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "pin": "1234"
}

### Batalkan transaksi yang belum diproses
POST http://localhost/api/v1/batal-transaksi?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "trxid": "123456",
    "pin": "1234"
}

### Cancel balance transfer
POST http://localhost/api/v1/batal-transfer-saldo?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "jumlah": "100000",
    "pin": "1234"
}

### Cek harga produk
POST http://localhost/api/v1/cek-harga?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodeproduk": "TEST5"
}

### Check downline"s markup
POST http://localhost/api/v1/cek-markup?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "pin": "1234"
}

### Check product markup
POST http://localhost/api/v1/cek-markup-produk?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "kodeproduk": "TEST5",
    "pin": "1234"
}

### Check all product markups
POST http://localhost/api/v1/cek-markup-produk2?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "pin": "1234"
}

### Cek N (lihat Setting.LimitCekMutasi) mutasi saldo/deposit terakhir
POST http://localhost/api/v1/cek-mutasi?&pengirim=%2B6281935155404
Content-Type: application/json

{}

### Cek mutasi saldo terakhir, khusus manual, tiket, dan transfer saldo
POST http://localhost/api/v1/cek-mutasi2?&pengirim=%2B6281935155404
Content-Type: application/json

{}

### Check current OID for OtomaX HTH
POST http://localhost/api/v1/cek-oid?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "pin": "1234"
}

### Cek saldo akhir
POST http://localhost/api/v1/cek-saldo?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "pin": "1234"
}

### Cek saldo downline
POST http://localhost/api/v1/cek-saldo-dl?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodereseller": "N5700006"
}

### Cek status transaksi
POST http://localhost/api/v1/cek-status-transaksi?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "nomor tujuan": "6287758437457"
}

### Cek status transaksi
POST http://localhost/api/v1/cek-status-transaksi2?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "tujuan": "6287758437457"
}

### Cek status transaksi
POST http://localhost/api/v1/cek-status-transaksi3?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "tanggal": "29",
    "tujuan": "6287758437457"
}

### Cek status N (lihat Setting.LimitCekTransaksiAkhir) transaksi terakhir
POST http://localhost/api/v1/cek-transaksi-akhir?&pengirim=%2B6281935155404
Content-Type: application/json

{}

### Daftarkan downline/reseller baru
POST http://localhost/api/v1/daftar-dl?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "nama": "Ndiing",
    "alamat": "Pacitan",
    "nomorhp": "6287758437457",
    "pin": "1234"
}

### Daftarkan downline/reseller baru
POST http://localhost/api/v1/daftar-dl2?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "nama": "Ndiing",
    "alamat": "Pacitan",
    "nomorhp": "6287758437457",
    "markup": "150",
    "pin": "1234"
}

### Daftarkan downline/reseller baru
POST http://localhost/api/v1/daftar-dl3?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "nama": "Ndiing",
    "alamat": "Pacitan",
    "nomorhp": "6287758437457",
    "kodelevel": "R",
    "pin": "1234"
}

### Registration of non member
POST http://localhost/api/v1/daftar-non-member?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "name": "Ndiing",
    "address": "Pacitan",
    "pin": "1234"
}

### Hapus pengirim tipe GTalk
POST http://localhost/api/v1/hapus-gtalk?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "email": "ndiing.inc@gmail.com",
    "pin": "1234"
}

### Hapus pengirim tipe GTalk untuk downline
POST http://localhost/api/v1/hapus-gtalk2?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "email": "ndiing.inc@gmail.com",
    "pin": "1234"
}

### Delete product markup
POST http://localhost/api/v1/hapus-markup-produk?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "kodereseller": "N5700006",
    "pin": "1234"
}

### Delete product markup
POST http://localhost/api/v1/hapus-markup-produk2?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "pin": "1234"
}

### Delete product markup
POST http://localhost/api/v1/hapus-markup-produk3?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "pin": "1234"
}

### Hapus pengirim tipe SMS
POST http://localhost/api/v1/hapus-nomor?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "tujuan": "6287758437457",
    "pin": "1234"
}

### Hapus pengirim tipe SMS
POST http://localhost/api/v1/hapus-nomor2?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "tujuan": "6287758437457",
    "pin": "1234"
}

### Hapus nomor WA
POST http://localhost/api/v1/hapus-wa?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "nomor": "6287758437457",
    "pin": "1234"
}

### Hapus pengirim tipe YM
POST http://localhost/api/v1/hapus-ym?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "yahooid": "ndiing.inc@yahoo.co.id",
    "pin": "1234"
}

### Hapus pengirim tipe YM dari downline
POST http://localhost/api/v1/hapus-ym2?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "yahooid": "ndiing.inc@yahoo.co.id",
    "pin": "1234"
}

### Cek laporan mutasi saldo per tanggal
POST http://localhost/api/v1/laporan-mutasi?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "tanggal": "29"
}

### Cek laporan transaksi per tanggal
POST http://localhost/api/v1/laporan-transaksi?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "tanggal": "29"
}

### View gift list
POST http://localhost/api/v1/lihat-hadiah-poin?&pengirim=%2B6281935155404
Content-Type: application/json

{}

### Lihat daftar downline
POST http://localhost/api/v1/list-dl?&pengirim=%2B6281935155404
Content-Type: application/json

{}

### Lihat daftar downline dari downline (sub-downline)
POST http://localhost/api/v1/list-dl2?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodereseller": "N5700006"
}

### Lihat daftar pengirim semua tipe
POST http://localhost/api/v1/list-pengirim?&pengirim=%2B6281935155404
Content-Type: application/json

{}

### Lihat daftar pengirim tipe GTalk
POST http://localhost/api/v1/list-pengirim-gtalk?&pengirim=%2B6281935155404
Content-Type: application/json

{}

### Lihat daftar pengirim tipe GTalk untuk downline
POST http://localhost/api/v1/list-pengirim-gtalk2?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodereseller": "N5700006"
}

### Lihat daftar pengirim tipe SMS
POST http://localhost/api/v1/list-pengirim-sms?&pengirim=%2B6281935155404
Content-Type: application/json

{}

### Lihat daftar pengirim tipe SMS dari downline
POST http://localhost/api/v1/list-pengirim-sms2?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodereseller": "N5700006"
}

### Lihat daftar pengirim tipe YM
POST http://localhost/api/v1/list-pengirim-ym?&pengirim=%2B6281935155404
Content-Type: application/json

{}

### Lihat daftar pengirim tipe YM dari downline
POST http://localhost/api/v1/list-pengirim-ym2?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodereseller": "N5700006"
}

### Non-aktifkan downline/reseller
POST http://localhost/api/v1/non-aktifkan-dl?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "pin": "1234"
}

### Reset pin member
POST http://localhost/api/v1/reset-pin?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "pin": "1234"
}

### Tambah pengirim tipe GTalk
POST http://localhost/api/v1/tambah-gtalk?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "email": "ndiing.inc@gmail.com",
    "pin": "1234"
}

### Tambah pengirim tipe GTalk untuk downline
POST http://localhost/api/v1/tambah-gtalk2?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "email": "ndiing.inc@gmail.com",
    "pin": "1234"
}

### Tambah pengirim tipe SMS
POST http://localhost/api/v1/tambah-nomor?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "tujuan": "6287758437457",
    "pin": "1234"
}

### Tambah pengirim tipe SMS untuk downline
POST http://localhost/api/v1/tambah-nomor2?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "tujuan": "6287758437457",
    "pin": "1234"
}

### Tambah nomor WA
POST http://localhost/api/v1/tambah-wa?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "number": "6287758437457",
    "pin": "1234"
}

### Tambah pengirim tipe YM
POST http://localhost/api/v1/tambah-ym?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "yahooid": "ndiing.inc@yahoo.co.id",
    "pin": "1234"
}

### Tambah pengirim tipe YM untuk downline
POST http://localhost/api/v1/tambah-ym2?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "yahooid": "ndiing.inc@yahoo.co.id",
    "pin": "1234"
}

### Tiket Deposit
POST http://localhost/api/v1/tiket-deposit?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "jumlah": "100000",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "tujuan": "6287758437457",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi10?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "tujuan": "6287758437457",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi11?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "nominal": "100000",
    "tujuan": "6287758437457",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi12?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "tujuan": "6287758437457",
    "nominal": "100000",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi13?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "tujuan": "6287758437457",
    "kodeproduk": "TEST5",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi14?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "counter": "1",
    "tujuan": "6287758437457",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi15?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "tujuan": "6287758437457",
    "nominal": "100000",
    "counter": "1",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi16?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "nominal": "100000",
    "tujuan": "6287758437457",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi17?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "tujuan": "6287758437457",
    "nominal": "100000",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi18?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "tujuan": "6287758437457",
    "kodeproduk": "TEST5",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi19?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "tujuan": "6287758437457",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi2?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "tujuan": "6287758437457",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi20?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "nominal": "100000",
    "tujuan": "6287758437457",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi21?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "tujuan": "6287758437457",
    "nominal": "100000",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi22?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "tujuan": "6287758437457",
    "kodeproduk": "TEST5",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi23?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "qty": "1",
    "tujuan": "6287758437457",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi24?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "qty": "1",
    "tujuan": "6287758437457",
    "pin": "1234",
    "counter": "1"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi25?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "tujuan": "6287758437457",
    "pin": "1234",
    "trxid": "123456"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi26?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "tujuan": "6287758437457",
    "pin": "1234",
    "enduser": "6281335447689"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi27?&pengirim=%2B6281935155404
Content-Type: application/json

{}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi28?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "nominal": "100000",
    "counter": "1",
    "tujuan": "6287758437457",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi29?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "qty": "1",
    "tujuan": "6287758437457",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi3?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "counter": "1",
    "kodeproduk": "TEST5",
    "qty": "1",
    "tujuan": "6287758437457",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi4?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "nominal": "100000",
    "tujuan": "6287758437457",
    "pin": "1234",
    "enduser": "6281335447689"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi5?&pengirim=%2B6281935155404
Content-Type: application/json

{}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi6?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi7?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "nominal": "100000"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi8?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodeproduk": "TEST5"
}

### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi9?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "nominal": "100000",
    "pin": "1234"
}

### Transaksi pengisian pulsa TANPA pengecekan dobel
POST http://localhost/api/v1/transaksi-bebas-dobel?&pengirim=%2B6281935155404
Content-Type: application/json

{}

### Transfer saldo/deposit ke downline/reseller
POST http://localhost/api/v1/transfer-saldo?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "jumlah": "100000",
    "pin": "1234"
}

### Allows transfer balance across the membership network
POST http://localhost/api/v1/transfer-saldo-lintas?&pengirim=%2B6281935155404
Content-Type: application/json

{}

### Tukar komisi tunda dalam bentuk deposit
POST http://localhost/api/v1/tukar-komisi?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "jumlah": "100000",
    "pin": "1234"
}

### Tukar semua komisi tunda dalam bentuk deposit
POST http://localhost/api/v1/tukar-komisi2?&pengirim=%2B6281935155404
Content-Type: application/json

{}

### Menukar poin
POST http://localhost/api/v1/tukar-poin?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kode": "TEST5",
    "pin": "1234"
}

### Change IP Address
POST http://localhost/api/v1/ubah-alamat-ip?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "newip": "192.168.1.1",
    "pin": "1234"
}

### Ubah level downline
POST http://localhost/api/v1/ubah-level?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "kodelevel": "R",
    "pin": "1234"
}

### Change downline"s markup
POST http://localhost/api/v1/ubah-markup?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodereseller": "N5700006",
    "markup": "150",
    "pin": "1234"
}

### Change product markup
POST http://localhost/api/v1/ubah-markup-produk?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "markup": "150",
    "kodereseller": "N5700006",
    "pin": "1234"
}

### Change product markup for all downlines
POST http://localhost/api/v1/ubah-markup-produk2?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "kodeproduk": "TEST5",
    "markup": "150",
    "pin": "1234"
}

### Ubah nama
POST http://localhost/api/v1/ubah-nama?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "nama": "Ndiing",
    "pin": "1234"
}

### Change OID for OtomaX HTH
POST http://localhost/api/v1/ubah-oid?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "oid": "ASDF321ASDF654ASDF987ASDF321",
    "pin": "1234"
}

### Change IP Password
POST http://localhost/api/v1/ubah-password-ip?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "oldpassword": "1234",
    "newpassword": "1234",
    "pin": "1234"
}

### Ubah PIN
POST http://localhost/api/v1/ubah-pin?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "pinlama": "1234",
    "pinbaru": "1234"
}

### Change Report URL
POST http://localhost/api/v1/ubah-report-url?&pengirim=%2B6281935155404
Content-Type: application/json

{
    "newurl": "http://ndiing.ddns.net/api/v1/webhook",
    "pin": "1234"
}

