### Aktifkan downline/reseller
GET http://ndiing.ddns.net/api/v1/aktifkan-dl?&pengirim=%2B6281935155405&kodereseller=N5700006&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Batalkan transaksi yang belum diproses
GET http://ndiing.ddns.net/api/v1/batal-transaksi?&pengirim=%2B6281935155405&trxid=123456&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Cancel balance transfer
GET http://ndiing.ddns.net/api/v1/batal-transfer-saldo?&pengirim=%2B6281935155405&kodereseller=N5700006&jumlah=100000&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Cek harga produk
GET http://ndiing.ddns.net/api/v1/cek-harga?&pengirim=%2B6281935155405&kodeproduk=TEST5
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Check downline"s markup
GET http://ndiing.ddns.net/api/v1/cek-markup?&pengirim=%2B6281935155405&kodereseller=N5700006&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Check product markup
GET http://ndiing.ddns.net/api/v1/cek-markup-produk?&pengirim=%2B6281935155405&kodereseller=N5700006&kodeproduk=TEST5&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Check all product markups
GET http://ndiing.ddns.net/api/v1/cek-markup-produk2?&pengirim=%2B6281935155405&kodereseller=N5700006&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Cek N (lihat Setting.LimitCekMutasi) mutasi saldo/deposit terakhir
GET http://ndiing.ddns.net/api/v1/cek-mutasi?&pengirim=%2B6281935155405&
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Cek mutasi saldo terakhir, khusus manual, tiket, dan transfer saldo
GET http://ndiing.ddns.net/api/v1/cek-mutasi2?&pengirim=%2B6281935155405&
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Check current OID for OtomaX HTH
GET http://ndiing.ddns.net/api/v1/cek-oid?&pengirim=%2B6281935155405&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Cek saldo akhir
GET http://ndiing.ddns.net/api/v1/cek-saldo?&pengirim=%2B6281935155405&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Cek saldo downline
GET http://ndiing.ddns.net/api/v1/cek-saldo-dl?&pengirim=%2B6281935155405&kodereseller=N5700006
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Cek status transaksi
GET http://ndiing.ddns.net/api/v1/cek-status-transaksi?&pengirim=%2B6281935155405&nomor+tujuan=6287758437457
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Cek status transaksi
GET http://ndiing.ddns.net/api/v1/cek-status-transaksi2?&pengirim=%2B6281935155405&tujuan=6287758437457
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Cek status transaksi
GET http://ndiing.ddns.net/api/v1/cek-status-transaksi3?&pengirim=%2B6281935155405&tanggal=29&tujuan=6287758437457
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Cek status N (lihat Setting.LimitCekTransaksiAkhir) transaksi terakhir
GET http://ndiing.ddns.net/api/v1/cek-transaksi-akhir?&pengirim=%2B6281935155405&
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Daftarkan downline/reseller baru
GET http://ndiing.ddns.net/api/v1/daftar-dl?&pengirim=%2B6281935155405&nama=Ndiing&alamat=Pacitan&nomorhp=6287758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Daftarkan downline/reseller baru
GET http://ndiing.ddns.net/api/v1/daftar-dl2?&pengirim=%2B6281935155405&nama=Ndiing&alamat=Pacitan&nomorhp=6287758437457&markup=150&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Daftarkan downline/reseller baru
GET http://ndiing.ddns.net/api/v1/daftar-dl3?&pengirim=%2B6281935155405&nama=Ndiing&alamat=Pacitan&nomorhp=6287758437457&kodelevel=R&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Registration of non member
GET http://ndiing.ddns.net/api/v1/daftar-non-member?&pengirim=%2B6281935155405&name=Ndiing&address=Pacitan&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Hapus pengirim tipe GTalk
GET http://ndiing.ddns.net/api/v1/hapus-gtalk?&pengirim=%2B6281935155405&email=ndiing.inc%40gmail.com&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Hapus pengirim tipe GTalk untuk downline
GET http://ndiing.ddns.net/api/v1/hapus-gtalk2?&pengirim=%2B6281935155405&kodereseller=N5700006&email=ndiing.inc%40gmail.com&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Delete product markup
GET http://ndiing.ddns.net/api/v1/hapus-markup-produk?&pengirim=%2B6281935155405&kodeproduk=TEST5&kodereseller=N5700006&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Delete product markup
GET http://ndiing.ddns.net/api/v1/hapus-markup-produk2?&pengirim=%2B6281935155405&kodereseller=N5700006&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Delete product markup
GET http://ndiing.ddns.net/api/v1/hapus-markup-produk3?&pengirim=%2B6281935155405&kodeproduk=TEST5&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Hapus pengirim tipe SMS
GET http://ndiing.ddns.net/api/v1/hapus-nomor?&pengirim=%2B6281935155405&tujuan=6287758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Hapus pengirim tipe SMS
GET http://ndiing.ddns.net/api/v1/hapus-nomor2?&pengirim=%2B6281935155405&kodereseller=N5700006&tujuan=6287758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Hapus nomor WA
GET http://ndiing.ddns.net/api/v1/hapus-wa?&pengirim=%2B6281935155405&nomor=6287758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Hapus pengirim tipe YM
GET http://ndiing.ddns.net/api/v1/hapus-ym?&pengirim=%2B6281935155405&yahooid=ndiing.inc%40yahoo.co.id&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Hapus pengirim tipe YM dari downline
GET http://ndiing.ddns.net/api/v1/hapus-ym2?&pengirim=%2B6281935155405&kodereseller=N5700006&yahooid=ndiing.inc%40yahoo.co.id&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Cek laporan mutasi saldo per tanggal
GET http://ndiing.ddns.net/api/v1/laporan-mutasi?&pengirim=%2B6281935155405&tanggal=29
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Cek laporan transaksi per tanggal
GET http://ndiing.ddns.net/api/v1/laporan-transaksi?&pengirim=%2B6281935155405&tanggal=29
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### View gift list
GET http://ndiing.ddns.net/api/v1/lihat-hadiah-poin?&pengirim=%2B6281935155405&
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Lihat daftar downline
GET http://ndiing.ddns.net/api/v1/list-dl?&pengirim=%2B6281935155405&
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Lihat daftar downline dari downline (sub-downline)
GET http://ndiing.ddns.net/api/v1/list-dl2?&pengirim=%2B6281935155405&kodereseller=N5700006
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Lihat daftar pengirim semua tipe
GET http://ndiing.ddns.net/api/v1/list-pengirim?&pengirim=%2B6281935155405&
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Lihat daftar pengirim tipe GTalk
GET http://ndiing.ddns.net/api/v1/list-pengirim-gtalk?&pengirim=%2B6281935155405&
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Lihat daftar pengirim tipe GTalk untuk downline
GET http://ndiing.ddns.net/api/v1/list-pengirim-gtalk2?&pengirim=%2B6281935155405&kodereseller=N5700006
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Lihat daftar pengirim tipe SMS
GET http://ndiing.ddns.net/api/v1/list-pengirim-sms?&pengirim=%2B6281935155405&
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Lihat daftar pengirim tipe SMS dari downline
GET http://ndiing.ddns.net/api/v1/list-pengirim-sms2?&pengirim=%2B6281935155405&kodereseller=N5700006
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Lihat daftar pengirim tipe YM
GET http://ndiing.ddns.net/api/v1/list-pengirim-ym?&pengirim=%2B6281935155405&
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Lihat daftar pengirim tipe YM dari downline
GET http://ndiing.ddns.net/api/v1/list-pengirim-ym2?&pengirim=%2B6281935155405&kodereseller=N5700006
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Non-aktifkan downline/reseller
GET http://ndiing.ddns.net/api/v1/non-aktifkan-dl?&pengirim=%2B6281935155405&kodereseller=N5700006&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Reset pin member
GET http://ndiing.ddns.net/api/v1/reset-pin?&pengirim=%2B6281935155405&kodereseller=N5700006&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Tambah pengirim tipe GTalk
GET http://ndiing.ddns.net/api/v1/tambah-gtalk?&pengirim=%2B6281935155405&email=ndiing.inc%40gmail.com&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Tambah pengirim tipe GTalk untuk downline
GET http://ndiing.ddns.net/api/v1/tambah-gtalk2?&pengirim=%2B6281935155405&kodereseller=N5700006&email=ndiing.inc%40gmail.com&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Tambah pengirim tipe SMS
GET http://ndiing.ddns.net/api/v1/tambah-nomor?&pengirim=%2B6281935155405&tujuan=6287758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Tambah pengirim tipe SMS untuk downline
GET http://ndiing.ddns.net/api/v1/tambah-nomor2?&pengirim=%2B6281935155405&kodereseller=N5700006&tujuan=6287758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Tambah nomor WA
GET http://ndiing.ddns.net/api/v1/tambah-wa?&pengirim=%2B6281935155405&number=6287758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Tambah pengirim tipe YM
GET http://ndiing.ddns.net/api/v1/tambah-ym?&pengirim=%2B6281935155405&yahooid=ndiing.inc%40yahoo.co.id&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Tambah pengirim tipe YM untuk downline
GET http://ndiing.ddns.net/api/v1/tambah-ym2?&pengirim=%2B6281935155405&kodereseller=N5700006&yahooid=ndiing.inc%40yahoo.co.id&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Tiket Deposit
GET http://ndiing.ddns.net/api/v1/tiket-deposit?&pengirim=%2B6281935155405&jumlah=100000&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi?&pengirim=%2B6281935155405&kodeproduk=TEST5&tujuan=6287758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi10?&pengirim=%2B6281935155405&kodeproduk=TEST5&tujuan=6287758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi11?&pengirim=%2B6281935155405&nominal=100000&tujuan=6287758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi12?&pengirim=%2B6281935155405&tujuan=6287758437457&nominal=100000&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi13?&pengirim=%2B6281935155405&tujuan=6287758437457&kodeproduk=TEST5&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi14?&pengirim=%2B6281935155405&kodeproduk=TEST5&counter=1&tujuan=6287758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi15?&pengirim=%2B6281935155405&tujuan=6287758437457&nominal=100000&counter=1&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi16?&pengirim=%2B6281935155405&nominal=100000&tujuan=6287758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi17?&pengirim=%2B6281935155405&tujuan=6287758437457&nominal=100000&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi18?&pengirim=%2B6281935155405&tujuan=6287758437457&kodeproduk=TEST5&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi19?&pengirim=%2B6281935155405&kodeproduk=TEST5&tujuan=6287758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi2?&pengirim=%2B6281935155405&kodeproduk=TEST5&tujuan=6287758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi20?&pengirim=%2B6281935155405&nominal=100000&tujuan=6287758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi21?&pengirim=%2B6281935155405&tujuan=6287758437457&nominal=100000&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi22?&pengirim=%2B6281935155405&tujuan=6287758437457&kodeproduk=TEST5&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi23?&pengirim=%2B6281935155405&kodeproduk=TEST5&qty=1&tujuan=6287758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi24?&pengirim=%2B6281935155405&kodeproduk=TEST5&qty=1&tujuan=6287758437457&pin=1234&counter=1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi25?&pengirim=%2B6281935155405&kodeproduk=TEST5&tujuan=6287758437457&pin=1234&trxid=123456
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi26?&pengirim=%2B6281935155405&kodeproduk=TEST5&tujuan=6287758437457&pin=1234&enduser=6281335447689
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi27?&pengirim=%2B6281935155405&
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi28?&pengirim=%2B6281935155405&nominal=100000&counter=1&tujuan=6287758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi29?&pengirim=%2B6281935155405&kodeproduk=TEST5&qty=1&tujuan=6287758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi3?&pengirim=%2B6281935155405&counter=1&kodeproduk=TEST5&qty=1&tujuan=6287758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi4?&pengirim=%2B6281935155405&kodeproduk=TEST5&nominal=100000&tujuan=6287758437457&pin=1234&enduser=6281335447689
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi5?&pengirim=%2B6281935155405&
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi6?&pengirim=%2B6281935155405&kodeproduk=TEST5&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi7?&pengirim=%2B6281935155405&nominal=100000
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi8?&pengirim=%2B6281935155405&kodeproduk=TEST5
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa
GET http://ndiing.ddns.net/api/v1/transaksi9?&pengirim=%2B6281935155405&nominal=100000&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transaksi pengisian pulsa TANPA pengecekan dobel
GET http://ndiing.ddns.net/api/v1/transaksi-bebas-dobel?&pengirim=%2B6281935155405&
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Transfer saldo/deposit ke downline/reseller
GET http://ndiing.ddns.net/api/v1/transfer-saldo?&pengirim=%2B6281935155405&kodereseller=N5700006&jumlah=100000&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Allows transfer balance across the membership network
GET http://ndiing.ddns.net/api/v1/transfer-saldo-lintas?&pengirim=%2B6281935155405&
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Tukar komisi tunda dalam bentuk deposit
GET http://ndiing.ddns.net/api/v1/tukar-komisi?&pengirim=%2B6281935155405&jumlah=100000&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Tukar semua komisi tunda dalam bentuk deposit
GET http://ndiing.ddns.net/api/v1/tukar-komisi2?&pengirim=%2B6281935155405&
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Menukar poin
GET http://ndiing.ddns.net/api/v1/tukar-poin?&pengirim=%2B6281935155405&kode=TEST5&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Change IP Address
GET http://ndiing.ddns.net/api/v1/ubah-alamat-ip?&pengirim=%2B6281935155405&newip=192.168.1.1&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Ubah level downline
GET http://ndiing.ddns.net/api/v1/ubah-level?&pengirim=%2B6281935155405&kodereseller=N5700006&kodelevel=R&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Change downline"s markup
GET http://ndiing.ddns.net/api/v1/ubah-markup?&pengirim=%2B6281935155405&kodereseller=N5700006&markup=150&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Change product markup
GET http://ndiing.ddns.net/api/v1/ubah-markup-produk?&pengirim=%2B6281935155405&kodeproduk=TEST5&markup=150&kodereseller=N5700006&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Change product markup for all downlines
GET http://ndiing.ddns.net/api/v1/ubah-markup-produk2?&pengirim=%2B6281935155405&kodeproduk=TEST5&markup=150&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Ubah nama
GET http://ndiing.ddns.net/api/v1/ubah-nama?&pengirim=%2B6281935155405&nama=Ndiing&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Change OID for OtomaX HTH
GET http://ndiing.ddns.net/api/v1/ubah-oid?&pengirim=%2B6281935155405&oid=ASDF321ASDF654ASDF987ASDF321&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Change IP Password
GET http://ndiing.ddns.net/api/v1/ubah-password-ip?&pengirim=%2B6281935155405&oldpassword=1234&newpassword=1234&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Ubah PIN
GET http://ndiing.ddns.net/api/v1/ubah-pin?&pengirim=%2B6281935155405&pinlama=1234&pinbaru=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

### Change Report URL
GET http://ndiing.ddns.net/api/v1/ubah-report-url?&pengirim=%2B6281935155405&newurl=http%3A%2F%2Fndiing.ddns.net%2Fapi%2Fv1%2Fwebhook&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.NGYwOTRkM2UwMzVkYTNmZTdhMWMwMjkwMDA2N2YwNzZkYTBiZjNiN2E4ODA0ZDQyOTRlMDBlNDkxMTIwYzZjOGQ2OGE1NDZmMDk5ZGZmMTZlOWE0MWQ5Y2QyNWQxNWEyN2VhMjhmNWY5ODY3Mjk1NDAxODM1NTkxZDAxYmE0YmU0Y2NjMGIzNTVkZGNlMjM3YWFjNjc0Y2Q4MzFhZWZkODk3NDM5OTJiYTg2ZThiNmZhNThlNjg1NDlhNGJhN2UwOWY0NGQ5ZjEzODRhNjgzYjkzZjQwYWMxMGIwMTA3OThhNjRkZmZlMjM2Y2M4MGJkZDNjYmM4ODQxOGVkNjM2MmY3YjlmN2NmNzk1NWIxNjExOTNiMTUyNWM4MTM0YmY1YjhjNTg1OTlhNGZkMjAxNmYwZGIwMGI4YjVkYThhZjQ5MjRlNzgzNmZhMjhlN2U0YjJmNjkyMjVhNmMwYjk1M2VmMGE3NmY3Zjg4MjJlMGI1YWJiY2JiNDMyZTMwNjJlMjg3YzcxOGY3M2Q4YTdjN2Y5ZDdhNjQzMzE5NmQzOGMxYjE1MzFmMmZiM2RkOWMxZDQ0NjdiZjUyZTA3MjRmYg==.ZjRiZWVmMTFkOTk0ZmNhN2ZmODBkZDRiYjVjMmYyZDU0YTVlZGEzMmNhNmU2YmIxY2I3NDIzYjVlMDFkZmZkMw==

