### Aktifkan downline/reseller
POST http://localhost/api/v1/aktifkan-dl?pengirim=%2B6281935155404&type=xml
Content-Type: application/xml

<request>
  <kodereseller>N5700006</kodereseller>
  <pin>1234</pin>
</request>


### Batalkan transaksi yang belum diproses
POST http://localhost/api/v1/batal-transaksi
Content-Type: application/xml

<request>
  <trxid>123456</trxid>
  <pin>1234</pin>
</request>


### Cancel balance transfer
POST http://localhost/api/v1/batal-transfer-saldo
Content-Type: application/xml

<request>
  <kodereseller>N5700006</kodereseller>
  <jumlah>100000</jumlah>
  <pin>1234</pin>
</request>


### Cek harga produk
POST http://localhost/api/v1/cek-harga
Content-Type: application/xml

<request>
  <kodeproduk>TEST5</kodeproduk>
</request>


### Check downline"s markup
POST http://localhost/api/v1/cek-markup
Content-Type: application/xml

<request>
  <kodereseller>N5700006</kodereseller>
  <pin>1234</pin>
</request>


### Check product markup
POST http://localhost/api/v1/cek-markup-produk
Content-Type: application/xml

<request>
  <kodereseller>N5700006</kodereseller>
  <kodeproduk>TEST5</kodeproduk>
  <pin>1234</pin>
</request>


### Check all product markups
POST http://localhost/api/v1/cek-markup-produk2
Content-Type: application/xml

<request>
  <kodereseller>N5700006</kodereseller>
  <pin>1234</pin>
</request>


### Cek N (lihat Setting.LimitCekMutasi) mutasi saldo/deposit terakhir
POST http://localhost/api/v1/cek-mutasi
Content-Type: application/xml

<request>
</request>


### Cek mutasi saldo terakhir, khusus manual, tiket, dan transfer saldo
POST http://localhost/api/v1/cek-mutasi2
Content-Type: application/xml

<request>
</request>


### Check current OID for OtomaX HTH
POST http://localhost/api/v1/cek-oid
Content-Type: application/xml

<request>
  <pin>1234</pin>
</request>


### Cek saldo akhir
POST http://localhost/api/v1/cek-saldo
Content-Type: application/xml

<request>
  <pin>1234</pin>
</request>


### Cek saldo downline
POST http://localhost/api/v1/cek-saldo-dl
Content-Type: application/xml

<request>
  <kodereseller>N5700006</kodereseller>
</request>


### Cek status transaksi
POST http://localhost/api/v1/cek-status-transaksi
Content-Type: application/xml

<request>
  <nomor tujuan>6287758437457</nomor tujuan>
</request>


### Cek status transaksi
POST http://localhost/api/v1/cek-status-transaksi2
Content-Type: application/xml

<request>
  <tujuan>6287758437457</tujuan>
</request>


### Cek status transaksi
POST http://localhost/api/v1/cek-status-transaksi3
Content-Type: application/xml

<request>
  <tanggal>29</tanggal>
  <tujuan>6287758437457</tujuan>
</request>


### Cek status N (lihat Setting.LimitCekTransaksiAkhir) transaksi terakhir
POST http://localhost/api/v1/cek-transaksi-akhir
Content-Type: application/xml

<request>
</request>


### Daftarkan downline/reseller baru
POST http://localhost/api/v1/daftar-dl
Content-Type: application/xml

<request>
  <nama>Ndiing</nama>
  <alamat>Pacitan</alamat>
  <nomorhp>6287758437457</nomorhp>
  <pin>1234</pin>
</request>


### Daftarkan downline/reseller baru
POST http://localhost/api/v1/daftar-dl2
Content-Type: application/xml

<request>
  <nama>Ndiing</nama>
  <alamat>Pacitan</alamat>
  <nomorhp>6287758437457</nomorhp>
  <markup>150</markup>
  <pin>1234</pin>
</request>


### Daftarkan downline/reseller baru
POST http://localhost/api/v1/daftar-dl3
Content-Type: application/xml

<request>
  <nama>Ndiing</nama>
  <alamat>Pacitan</alamat>
  <nomorhp>6287758437457</nomorhp>
  <kodelevel>R</kodelevel>
  <pin>1234</pin>
</request>







### Registration of non member
POST http://localhost/api/v1/daftar-non-member
Content-Type: application/xml

<request>
  <name>Ndiing</name>
  <address>Pacitan</address>
  <pin>1234</pin>
</request>
### Registration of non member
POST http://192.168.1.123/api/v1/daftar-non-member
Content-Type: application/xml

<request>
  <name>Ndiing</name>
  <address>Pacitan</address>
  <pin>1234</pin>
</request>
### Registration of non member
POST http://ndiing.ddns.net/api/v1/daftar-non-member
Content-Type: application/xml

<request>
  <name>Ndiing</name>
  <address>Pacitan</address>
  <pin>1234</pin>
</request>







### Hapus pengirim tipe GTalk
POST http://localhost/api/v1/hapus-gtalk
Content-Type: application/xml

<request>
  <email>ndiing.inc@gmail.com</email>
  <pin>1234</pin>
</request>


### Hapus pengirim tipe GTalk untuk downline
POST http://localhost/api/v1/hapus-gtalk2
Content-Type: application/xml

<request>
  <kodereseller>N5700006</kodereseller>
  <email>ndiing.inc@gmail.com</email>
  <pin>1234</pin>
</request>


### Delete product markup
POST http://localhost/api/v1/hapus-markup-produk
Content-Type: application/xml

<request>
  <kodeproduk>TEST5</kodeproduk>
  <kodereseller>N5700006</kodereseller>
  <pin>1234</pin>
</request>


### Delete product markup
POST http://localhost/api/v1/hapus-markup-produk2
Content-Type: application/xml

<request>
  <kodereseller>N5700006</kodereseller>
  <pin>1234</pin>
</request>


### Delete product markup
POST http://localhost/api/v1/hapus-markup-produk3
Content-Type: application/xml

<request>
  <kodeproduk>TEST5</kodeproduk>
  <pin>1234</pin>
</request>


### Hapus pengirim tipe SMS
POST http://localhost/api/v1/hapus-nomor
Content-Type: application/xml

<request>
  <tujuan>6287758437457</tujuan>
  <pin>1234</pin>
</request>


### Hapus pengirim tipe SMS
POST http://localhost/api/v1/hapus-nomor2
Content-Type: application/xml

<request>
  <kodereseller>N5700006</kodereseller>
  <tujuan>6287758437457</tujuan>
  <pin>1234</pin>
</request>


### Hapus nomor WA
POST http://localhost/api/v1/hapus-wa
Content-Type: application/xml

<request>
  <nomor>6287758437457</nomor>
  <pin>1234</pin>
</request>


### Hapus pengirim tipe YM
POST http://localhost/api/v1/hapus-ym
Content-Type: application/xml

<request>
  <yahooid>ndiing.inc@yahoo.co.id</yahooid>
  <pin>1234</pin>
</request>


### Hapus pengirim tipe YM dari downline
POST http://localhost/api/v1/hapus-ym2
Content-Type: application/xml

<request>
  <kodereseller>N5700006</kodereseller>
  <yahooid>ndiing.inc@yahoo.co.id</yahooid>
  <pin>1234</pin>
</request>


### Cek laporan mutasi saldo per tanggal
POST http://localhost/api/v1/laporan-mutasi
Content-Type: application/xml

<request>
  <tanggal>29</tanggal>
</request>


### Cek laporan transaksi per tanggal
POST http://localhost/api/v1/laporan-transaksi
Content-Type: application/xml

<request>
  <tanggal>29</tanggal>
</request>


### View gift list
POST http://localhost/api/v1/lihat-hadiah-poin
Content-Type: application/xml

<request>
</request>


### Lihat daftar downline
POST http://localhost/api/v1/list-dl
Content-Type: application/xml

<request>
</request>


### Lihat daftar downline dari downline (sub-downline)
POST http://localhost/api/v1/list-dl2
Content-Type: application/xml

<request>
  <kodereseller>N5700006</kodereseller>
</request>


### Lihat daftar pengirim semua tipe
POST http://localhost/api/v1/list-pengirim
Content-Type: application/xml

<request>
</request>


### Lihat daftar pengirim tipe GTalk
POST http://localhost/api/v1/list-pengirim-gtalk
Content-Type: application/xml

<request>
</request>


### Lihat daftar pengirim tipe GTalk untuk downline
POST http://localhost/api/v1/list-pengirim-gtalk2
Content-Type: application/xml

<request>
  <kodereseller>N5700006</kodereseller>
</request>


### Lihat daftar pengirim tipe SMS
POST http://localhost/api/v1/list-pengirim-sms
Content-Type: application/xml

<request>
</request>


### Lihat daftar pengirim tipe SMS dari downline
POST http://localhost/api/v1/list-pengirim-sms2
Content-Type: application/xml

<request>
  <kodereseller>N5700006</kodereseller>
</request>


### Lihat daftar pengirim tipe YM
POST http://localhost/api/v1/list-pengirim-ym
Content-Type: application/xml

<request>
</request>


### Lihat daftar pengirim tipe YM dari downline
POST http://localhost/api/v1/list-pengirim-ym2
Content-Type: application/xml

<request>
  <kodereseller>N5700006</kodereseller>
</request>


### Non-aktifkan downline/reseller
POST http://localhost/api/v1/non-aktifkan-dl
Content-Type: application/xml

<request>
  <kodereseller>N5700006</kodereseller>
  <pin>1234</pin>
</request>


### Reset pin member
POST http://localhost/api/v1/reset-pin
Content-Type: application/xml

<request>
  <kodereseller>N5700006</kodereseller>
  <pin>1234</pin>
</request>


### Tambah pengirim tipe GTalk
POST http://localhost/api/v1/tambah-gtalk
Content-Type: application/xml

<request>
  <email>ndiing.inc@gmail.com</email>
  <pin>1234</pin>
</request>


### Tambah pengirim tipe GTalk untuk downline
POST http://localhost/api/v1/tambah-gtalk2
Content-Type: application/xml

<request>
  <kodereseller>N5700006</kodereseller>
  <email>ndiing.inc@gmail.com</email>
  <pin>1234</pin>
</request>


### Tambah pengirim tipe SMS
POST http://localhost/api/v1/tambah-nomor
Content-Type: application/xml

<request>
  <tujuan>6287758437457</tujuan>
  <pin>1234</pin>
</request>


### Tambah pengirim tipe SMS untuk downline
POST http://localhost/api/v1/tambah-nomor2
Content-Type: application/xml

<request>
  <kodereseller>N5700006</kodereseller>
  <tujuan>6287758437457</tujuan>
  <pin>1234</pin>
</request>


### Tambah nomor WA
POST http://localhost/api/v1/tambah-wa
Content-Type: application/xml

<request>
  <number>6287758437457</number>
  <pin>1234</pin>
</request>


### Tambah pengirim tipe YM
POST http://localhost/api/v1/tambah-ym
Content-Type: application/xml

<request>
  <yahooid>ndiing.inc@yahoo.co.id</yahooid>
  <pin>1234</pin>
</request>


### Tambah pengirim tipe YM untuk downline
POST http://localhost/api/v1/tambah-ym2
Content-Type: application/xml

<request>
  <kodereseller>N5700006</kodereseller>
  <yahooid>ndiing.inc@yahoo.co.id</yahooid>
  <pin>1234</pin>
</request>


### Tiket Deposit
POST http://localhost/api/v1/tiket-deposit
Content-Type: application/xml

<request>
  <jumlah>100000</jumlah>
  <pin>1234</pin>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi
Content-Type: application/xml

<request>
  <kodeproduk>TEST5</kodeproduk>
  <tujuan>6287758437457</tujuan>
  <pin>1234</pin>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi10
Content-Type: application/xml

<request>
  <kodeproduk>TEST5</kodeproduk>
  <tujuan>6287758437457</tujuan>
  <pin>1234</pin>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi11
Content-Type: application/xml

<request>
  <nominal>100000</nominal>
  <tujuan>6287758437457</tujuan>
  <pin>1234</pin>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi12
Content-Type: application/xml

<request>
  <tujuan>6287758437457</tujuan>
  <nominal>100000</nominal>
  <pin>1234</pin>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi13
Content-Type: application/xml

<request>
  <tujuan>6287758437457</tujuan>
  <kodeproduk>TEST5</kodeproduk>
  <pin>1234</pin>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi14
Content-Type: application/xml

<request>
  <kodeproduk>TEST5</kodeproduk>
  <counter>1</counter>
  <tujuan>6287758437457</tujuan>
  <pin>1234</pin>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi15
Content-Type: application/xml

<request>
  <tujuan>6287758437457</tujuan>
  <nominal>100000</nominal>
  <counter>1</counter>
  <pin>1234</pin>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi16
Content-Type: application/xml

<request>
  <nominal>100000</nominal>
  <tujuan>6287758437457</tujuan>
  <pin>1234</pin>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi17
Content-Type: application/xml

<request>
  <tujuan>6287758437457</tujuan>
  <nominal>100000</nominal>
  <pin>1234</pin>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi18
Content-Type: application/xml

<request>
  <tujuan>6287758437457</tujuan>
  <kodeproduk>TEST5</kodeproduk>
  <pin>1234</pin>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi19
Content-Type: application/xml

<request>
  <kodeproduk>TEST5</kodeproduk>
  <tujuan>6287758437457</tujuan>
  <pin>1234</pin>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi2
Content-Type: application/xml

<request>
  <kodeproduk>TEST5</kodeproduk>
  <tujuan>6287758437457</tujuan>
  <pin>1234</pin>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi20
Content-Type: application/xml

<request>
  <nominal>100000</nominal>
  <tujuan>6287758437457</tujuan>
  <pin>1234</pin>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi21
Content-Type: application/xml

<request>
  <tujuan>6287758437457</tujuan>
  <nominal>100000</nominal>
  <pin>1234</pin>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi22
Content-Type: application/xml

<request>
  <tujuan>6287758437457</tujuan>
  <kodeproduk>TEST5</kodeproduk>
  <pin>1234</pin>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi23
Content-Type: application/xml

<request>
  <kodeproduk>TEST5</kodeproduk>
  <qty>1</qty>
  <tujuan>6287758437457</tujuan>
  <pin>1234</pin>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi24
Content-Type: application/xml

<request>
  <kodeproduk>TEST5</kodeproduk>
  <qty>1</qty>
  <tujuan>6287758437457</tujuan>
  <pin>1234</pin>
  <counter>1</counter>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi25
Content-Type: application/xml

<request>
  <kodeproduk>TEST5</kodeproduk>
  <tujuan>6287758437457</tujuan>
  <pin>1234</pin>
  <trxid>123456</trxid>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi26
Content-Type: application/xml

<request>
  <kodeproduk>TEST5</kodeproduk>
  <tujuan>6287758437457</tujuan>
  <pin>1234</pin>
  <enduser>6281335447689</enduser>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi27
Content-Type: application/xml

<request>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi28
Content-Type: application/xml

<request>
  <nominal>100000</nominal>
  <counter>1</counter>
  <tujuan>6287758437457</tujuan>
  <pin>1234</pin>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi29
Content-Type: application/xml

<request>
  <kodeproduk>TEST5</kodeproduk>
  <qty>1</qty>
  <tujuan>6287758437457</tujuan>
  <pin>1234</pin>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi3
Content-Type: application/xml

<request>
  <counter>1</counter>
  <kodeproduk>TEST5</kodeproduk>
  <qty>1</qty>
  <tujuan>6287758437457</tujuan>
  <pin>1234</pin>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi4
Content-Type: application/xml

<request>
  <kodeproduk>TEST5</kodeproduk>
  <nominal>100000</nominal>
  <tujuan>6287758437457</tujuan>
  <pin>1234</pin>
  <enduser>6281335447689</enduser>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi5
Content-Type: application/xml

<request>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi6
Content-Type: application/xml

<request>
  <kodeproduk>TEST5</kodeproduk>
  <pin>1234</pin>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi7
Content-Type: application/xml

<request>
  <nominal>100000</nominal>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi8
Content-Type: application/xml

<request>
  <kodeproduk>TEST5</kodeproduk>
</request>


### Transaksi pengisian pulsa
POST http://localhost/api/v1/transaksi9
Content-Type: application/xml

<request>
  <nominal>100000</nominal>
  <pin>1234</pin>
</request>


### Transaksi pengisian pulsa TANPA pengecekan dobel
POST http://localhost/api/v1/transaksi-bebas-dobel
Content-Type: application/xml

<request>
</request>


### Transfer saldo/deposit ke downline/reseller
POST http://localhost/api/v1/transfer-saldo
Content-Type: application/xml

<request>
  <kodereseller>N5700006</kodereseller>
  <jumlah>100000</jumlah>
  <pin>1234</pin>
</request>


### Allows transfer balance across the membership network
POST http://localhost/api/v1/transfer-saldo-lintas
Content-Type: application/xml

<request>
</request>


### Tukar komisi tunda dalam bentuk deposit
POST http://localhost/api/v1/tukar-komisi
Content-Type: application/xml

<request>
  <jumlah>100000</jumlah>
  <pin>1234</pin>
</request>


### Tukar semua komisi tunda dalam bentuk deposit
POST http://localhost/api/v1/tukar-komisi2
Content-Type: application/xml

<request>
</request>


### Menukar poin
POST http://localhost/api/v1/tukar-poin
Content-Type: application/xml

<request>
  <kode>TEST5</kode>
  <pin>1234</pin>
</request>


### Change IP Address
POST http://localhost/api/v1/ubah-alamat-ip
Content-Type: application/xml

<request>
  <newip>192.168.1.1</newip>
  <pin>1234</pin>
</request>


### Ubah level downline
POST http://localhost/api/v1/ubah-level
Content-Type: application/xml

<request>
  <kodereseller>N5700006</kodereseller>
  <kodelevel>R</kodelevel>
  <pin>1234</pin>
</request>


### Change downline"s markup
POST http://localhost/api/v1/ubah-markup
Content-Type: application/xml

<request>
  <kodereseller>N5700006</kodereseller>
  <markup>150</markup>
  <pin>1234</pin>
</request>


### Change product markup
POST http://localhost/api/v1/ubah-markup-produk
Content-Type: application/xml

<request>
  <kodeproduk>TEST5</kodeproduk>
  <markup>150</markup>
  <kodereseller>N5700006</kodereseller>
  <pin>1234</pin>
</request>


### Change product markup for all downlines
POST http://localhost/api/v1/ubah-markup-produk2
Content-Type: application/xml

<request>
  <kodeproduk>TEST5</kodeproduk>
  <markup>150</markup>
  <pin>1234</pin>
</request>


### Ubah nama
POST http://localhost/api/v1/ubah-nama
Content-Type: application/xml

<request>
  <nama>Ndiing</nama>
  <pin>1234</pin>
</request>


### Change OID for OtomaX HTH
POST http://localhost/api/v1/ubah-oid
Content-Type: application/xml

<request>
  <oid>ASDF321ASDF654ASDF987ASDF321</oid>
  <pin>1234</pin>
</request>


### Change IP Password
POST http://localhost/api/v1/ubah-password-ip
Content-Type: application/xml

<request>
  <oldpassword>1234</oldpassword>
  <newpassword>1234</newpassword>
  <pin>1234</pin>
</request>


### Ubah PIN
POST http://localhost/api/v1/ubah-pin
Content-Type: application/xml

<request>
  <pinlama>1234</pinlama>
  <pinbaru>1234</pinbaru>
</request>


### Change Report URL
POST http://localhost/api/v1/ubah-report-url
Content-Type: application/xml

<request>
  <newurl>http://ndiing.ddns.net/api/v1/webhook</newurl>
  <pin>1234</pin>
</request>


