### Login
POST http://ndiing.ddns.net/api/v1/sign
Content-Type: application/json

{
    "pengirim":"+6281935155404",
    "tipe_pengirim":"S"
}

### Konfirmasi login
POST http://ndiing.ddns.net/api/v1/verify
Content-Type: application/json

{
    "kode":"11f1ac07-667e-481f-a816-f399bca03442",
    "token":"400630"
}

### Konfirmasi refresh
POST http://ndiing.ddns.net/api/v1/verify
Content-Type: application/json

{
    "kode":"11f1ac07-667e-481f-a816-f399bca03442",
    "token":"NGUzYjRkZWM4ZjM2YjlkMzZlZjA0ZjliMzNlMGE1Nzk5ZTc2NTJhOTE1YjE3NTFmMTk5ODcxYmU3OGI0M2YxMg==",
    "token_type":"refresh"
}

### Konfirmasi shared (akses token disesuaikan)
POST http://ndiing.ddns.net/api/v1/verify
Content-Type: application/json

{
    "kode":"11f1ac07-667e-481f-a816-f399bca03442",
    "token":"MZYVEVRWFIRUQTSRMFTD4YZSH5KDAUKRKZJSCVRKIZ4DAMSSKRSQ",
    "token_type":"shared",
    "ip":".*",
    "aud": [
        "OtomaxOperator",
        "OtomaxProduk"
    ],
    "expires_in": 86400000
}

### List token
GET http://ndiing.ddns.net/api/v1/credential
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.YTFmMDlkNThiMDM2Njg3ZjRhM2U2NGI1MTFkOWQxYTQ5MTkxMmYyY2IzYTQzNTJkMjhjMzFkMTljZWY3NTIxOGJkYzJiYThhZTMzNWJhZjMyNTE4NjgxZmMyZTI4ZGViMTJiOGRiOGNlNWVlZjJiYzVhMGQxODlhNjBjZTY2NWNiYjM4YmE0MjkxMGNkODE5NDlmMzhkYTEwYzNhNWVkNjEwY2M5YTgwNzRjZGI0M2ZjOTlkOTIwYThjZjg0NmIyZDg2YjJiOGQ0NzhiMGFmMmI0YTM4OGJlYWI1ZTQ0N2MxZDVjZTZjMDIzNTczNjIxYTRhZGFiZjM1YzA5OWVkMGYxZGM3ZWY2M2JkNzkxNWI4M2MwZGI5MDc4MWM1NzkyNjQzNDQ2Y2U4MDBjMzc2MzRmNDFlMzAwZTkwYTljODg5YWZjM2VjMWExN2RlOTYzYWZiNWEwMmQ2MDljZTFkODUxZWIxOGE2M2M5MTcxMWUwYTIwYzExNWE1YWViNGZjYmE4NWQ2ZDMyYTI5ZDQ0ZWY1OWRkMDVkYjFiNGEwNDU3ZDA0OTMyZDY2MzExY2M3YzNhZjQ1OTAzOGZhZjJlNQ==.YjkyNjdkOGRmZTlkYTg2NGNmYTgzYjM4NGE4OTAzZWZhOTVlZmRlOWYxZDlhODIwY2JkZjZiMDIyNTkxYmM4OA==

### Cabut token
DELETE http://ndiing.ddns.net/api/v1/revoke/11f1ac07-667e-481f-a816-f399bca03442
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.YTFmMDlkNThiMDM2Njg3ZjRhM2U2NGI1MTFkOWQxYTQ5MTkxMmYyY2IzYTQzNTJkMjhjMzFkMTljZWY3NTIxOGJkYzJiYThhZTMzNWJhZjMyNTE4NjgxZmMyZTI4ZGViMTJiOGRiOGNlNWVlZjJiYzVhMGQxODlhNjBjZTY2NWNiYjM4YmE0MjkxMGNkODE5NDlmMzhkYTEwYzNhNWVkNjEwY2M5YTgwNzRjZGI0M2ZjOTlkOTIwYThjZjg0NmIyZDg2YjJiOGQ0NzhiMGFmMmI0YTM4OGJlYWI1ZTQ0N2MxZDVjZTZjMDIzNTczNjIxYTRhZGFiZjM1YzA5OWVkMGYxZGM3ZWY2M2JkNzkxNWI4M2MwZGI5MDc4MWM1NzkyNjQzNDQ2Y2U4MDBjMzc2MzRmNDFlMzAwZTkwYTljODg5YWZjM2VjMWExN2RlOTYzYWZiNWEwMmQ2MDljZTFkODUxZWIxOGE2M2M5MTcxMWUwYTIwYzExNWE1YWViNGZjYmE4NWQ2ZDMyYTI5ZDQ0ZWY1OWRkMDVkYjFiNGEwNDU3ZDA0OTMyZDY2MzExY2M3YzNhZjQ1OTAzOGZhZjJlNQ==.YjkyNjdkOGRmZTlkYTg2NGNmYTgzYjM4NGE4OTAzZWZhOTVlZmRlOWYxZDlhODIwY2JkZjZiMDIyNTkxYmM4OA==






### reseller
GET http://ndiing.ddns.net/api/v1/reseller
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.YTFmMDlkNThiMDM2Njg3ZjRhM2U2NGI1MTFkOWQxYTQ5MTkxMmYyY2IzYTQzNTJkMjhjMzFkMTljZWY3NTIxOGJkYzJiYThhZTMzNWJhZjMyNTE4NjgxZmMyZTI4ZGViMTJiOGRiOGNlNWVlZjJiYzVhMGQxODlhNjBjZTY2NWNiYjM4YmE0MjkxMGNkODE5NDlmMzhkYTEwYzNhNWVkNjEwY2M5YTgwNzRjZGI0M2ZjOTlkOTIwYThjZjg0NmIyZDg2YjJiOGQ0NzhiMGFmMmI0YTM4OGJlYWI1ZTQ0N2MxZDVjZTZjMDIzNTczNjIxYTRhZGFiZjM1YzA5OWVkMGYxZGM3ZWY2M2JkNzkxNWI4M2MwZGI5MDc4MWM1NzkyNjQzNDQ2Y2U4MDBjMzc2MzRmNDFlMzAwZTkwYTljODg5YWZjM2VjMWExN2RlOTYzYWZiNWEwMmQ2MDljZTFkODUxZWIxOGE2M2M5MTcxMWUwYTIwYzExNWE1YWViNGZjYmE4NWQ2ZDMyYTI5ZDQ0ZWY1OWRkMDVkYjFiNGEwNDU3ZDA0OTMyZDY2MzExY2M3YzNhZjQ1OTAzOGZhZjJlNQ==.YjkyNjdkOGRmZTlkYTg2NGNmYTgzYjM4NGE4OTAzZWZhOTVlZmRlOWYxZDlhODIwY2JkZjZiMDIyNTkxYmM4OA==
### reseller => shared token ?access_token=xxx 
GET http://ndiing.ddns.net/api/v1/reseller?access_token=5316189b-da7e-43d9-df71-769789900740






### pengirim
GET http://ndiing.ddns.net/api/v1/pengirim
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.YTFmMDlkNThiMDM2Njg3ZjRhM2U2NGI1MTFkOWQxYTQ5MTkxMmYyY2IzYTQzNTJkMjhjMzFkMTljZWY3NTIxOGJkYzJiYThhZTMzNWJhZjMyNTE4NjgxZmMyZTI4ZGViMTJiOGRiOGNlNWVlZjJiYzVhMGQxODlhNjBjZTY2NWNiYjM4YmE0MjkxMGNkODE5NDlmMzhkYTEwYzNhNWVkNjEwY2M5YTgwNzRjZGI0M2ZjOTlkOTIwYThjZjg0NmIyZDg2YjJiOGQ0NzhiMGFmMmI0YTM4OGJlYWI1ZTQ0N2MxZDVjZTZjMDIzNTczNjIxYTRhZGFiZjM1YzA5OWVkMGYxZGM3ZWY2M2JkNzkxNWI4M2MwZGI5MDc4MWM1NzkyNjQzNDQ2Y2U4MDBjMzc2MzRmNDFlMzAwZTkwYTljODg5YWZjM2VjMWExN2RlOTYzYWZiNWEwMmQ2MDljZTFkODUxZWIxOGE2M2M5MTcxMWUwYTIwYzExNWE1YWViNGZjYmE4NWQ2ZDMyYTI5ZDQ0ZWY1OWRkMDVkYjFiNGEwNDU3ZDA0OTMyZDY2MzExY2M3YzNhZjQ1OTAzOGZhZjJlNQ==.YjkyNjdkOGRmZTlkYTg2NGNmYTgzYjM4NGE4OTAzZWZhOTVlZmRlOWYxZDlhODIwY2JkZjZiMDIyNTkxYmM4OA==

### downline
GET http://ndiing.ddns.net/api/v1/downline
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.YTFmMDlkNThiMDM2Njg3ZjRhM2U2NGI1MTFkOWQxYTQ5MTkxMmYyY2IzYTQzNTJkMjhjMzFkMTljZWY3NTIxOGJkYzJiYThhZTMzNWJhZjMyNTE4NjgxZmMyZTI4ZGViMTJiOGRiOGNlNWVlZjJiYzVhMGQxODlhNjBjZTY2NWNiYjM4YmE0MjkxMGNkODE5NDlmMzhkYTEwYzNhNWVkNjEwY2M5YTgwNzRjZGI0M2ZjOTlkOTIwYThjZjg0NmIyZDg2YjJiOGQ0NzhiMGFmMmI0YTM4OGJlYWI1ZTQ0N2MxZDVjZTZjMDIzNTczNjIxYTRhZGFiZjM1YzA5OWVkMGYxZGM3ZWY2M2JkNzkxNWI4M2MwZGI5MDc4MWM1NzkyNjQzNDQ2Y2U4MDBjMzc2MzRmNDFlMzAwZTkwYTljODg5YWZjM2VjMWExN2RlOTYzYWZiNWEwMmQ2MDljZTFkODUxZWIxOGE2M2M5MTcxMWUwYTIwYzExNWE1YWViNGZjYmE4NWQ2ZDMyYTI5ZDQ0ZWY1OWRkMDVkYjFiNGEwNDU3ZDA0OTMyZDY2MzExY2M3YzNhZjQ1OTAzOGZhZjJlNQ==.YjkyNjdkOGRmZTlkYTg2NGNmYTgzYjM4NGE4OTAzZWZhOTVlZmRlOWYxZDlhODIwY2JkZjZiMDIyNTkxYmM4OA==






### operator
GET http://ndiing.ddns.net/api/v1/operator
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.YTFmMDlkNThiMDM2Njg3ZjRhM2U2NGI1MTFkOWQxYTQ5MTkxMmYyY2IzYTQzNTJkMjhjMzFkMTljZWY3NTIxOGJkYzJiYThhZTMzNWJhZjMyNTE4NjgxZmMyZTI4ZGViMTJiOGRiOGNlNWVlZjJiYzVhMGQxODlhNjBjZTY2NWNiYjM4YmE0MjkxMGNkODE5NDlmMzhkYTEwYzNhNWVkNjEwY2M5YTgwNzRjZGI0M2ZjOTlkOTIwYThjZjg0NmIyZDg2YjJiOGQ0NzhiMGFmMmI0YTM4OGJlYWI1ZTQ0N2MxZDVjZTZjMDIzNTczNjIxYTRhZGFiZjM1YzA5OWVkMGYxZGM3ZWY2M2JkNzkxNWI4M2MwZGI5MDc4MWM1NzkyNjQzNDQ2Y2U4MDBjMzc2MzRmNDFlMzAwZTkwYTljODg5YWZjM2VjMWExN2RlOTYzYWZiNWEwMmQ2MDljZTFkODUxZWIxOGE2M2M5MTcxMWUwYTIwYzExNWE1YWViNGZjYmE4NWQ2ZDMyYTI5ZDQ0ZWY1OWRkMDVkYjFiNGEwNDU3ZDA0OTMyZDY2MzExY2M3YzNhZjQ1OTAzOGZhZjJlNQ==.YjkyNjdkOGRmZTlkYTg2NGNmYTgzYjM4NGE4OTAzZWZhOTVlZmRlOWYxZDlhODIwY2JkZjZiMDIyNTkxYmM4OA==
### operator => shared token ?access_token=xxx
GET http://ndiing.ddns.net/api/v1/operator?access_token=5316189b-da7e-43d9-df71-769789900740






### produk
GET http://ndiing.ddns.net/api/v1/produk?kode_operator=test
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.YTFmMDlkNThiMDM2Njg3ZjRhM2U2NGI1MTFkOWQxYTQ5MTkxMmYyY2IzYTQzNTJkMjhjMzFkMTljZWY3NTIxOGJkYzJiYThhZTMzNWJhZjMyNTE4NjgxZmMyZTI4ZGViMTJiOGRiOGNlNWVlZjJiYzVhMGQxODlhNjBjZTY2NWNiYjM4YmE0MjkxMGNkODE5NDlmMzhkYTEwYzNhNWVkNjEwY2M5YTgwNzRjZGI0M2ZjOTlkOTIwYThjZjg0NmIyZDg2YjJiOGQ0NzhiMGFmMmI0YTM4OGJlYWI1ZTQ0N2MxZDVjZTZjMDIzNTczNjIxYTRhZGFiZjM1YzA5OWVkMGYxZGM3ZWY2M2JkNzkxNWI4M2MwZGI5MDc4MWM1NzkyNjQzNDQ2Y2U4MDBjMzc2MzRmNDFlMzAwZTkwYTljODg5YWZjM2VjMWExN2RlOTYzYWZiNWEwMmQ2MDljZTFkODUxZWIxOGE2M2M5MTcxMWUwYTIwYzExNWE1YWViNGZjYmE4NWQ2ZDMyYTI5ZDQ0ZWY1OWRkMDVkYjFiNGEwNDU3ZDA0OTMyZDY2MzExY2M3YzNhZjQ1OTAzOGZhZjJlNQ==.YjkyNjdkOGRmZTlkYTg2NGNmYTgzYjM4NGE4OTAzZWZhOTVlZmRlOWYxZDlhODIwY2JkZjZiMDIyNTkxYmM4OA==
### produk => shared token ?access_token=xxx
GET http://ndiing.ddns.net/api/v1/produk?access_token=5316189b-da7e-43d9-df71-769789900740&kode_operator=test






### mutasi
GET http://ndiing.ddns.net/api/v1/mutasi
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.YTFmMDlkNThiMDM2Njg3ZjRhM2U2NGI1MTFkOWQxYTQ5MTkxMmYyY2IzYTQzNTJkMjhjMzFkMTljZWY3NTIxOGJkYzJiYThhZTMzNWJhZjMyNTE4NjgxZmMyZTI4ZGViMTJiOGRiOGNlNWVlZjJiYzVhMGQxODlhNjBjZTY2NWNiYjM4YmE0MjkxMGNkODE5NDlmMzhkYTEwYzNhNWVkNjEwY2M5YTgwNzRjZGI0M2ZjOTlkOTIwYThjZjg0NmIyZDg2YjJiOGQ0NzhiMGFmMmI0YTM4OGJlYWI1ZTQ0N2MxZDVjZTZjMDIzNTczNjIxYTRhZGFiZjM1YzA5OWVkMGYxZGM3ZWY2M2JkNzkxNWI4M2MwZGI5MDc4MWM1NzkyNjQzNDQ2Y2U4MDBjMzc2MzRmNDFlMzAwZTkwYTljODg5YWZjM2VjMWExN2RlOTYzYWZiNWEwMmQ2MDljZTFkODUxZWIxOGE2M2M5MTcxMWUwYTIwYzExNWE1YWViNGZjYmE4NWQ2ZDMyYTI5ZDQ0ZWY1OWRkMDVkYjFiNGEwNDU3ZDA0OTMyZDY2MzExY2M3YzNhZjQ1OTAzOGZhZjJlNQ==.YjkyNjdkOGRmZTlkYTg2NGNmYTgzYjM4NGE4OTAzZWZhOTVlZmRlOWYxZDlhODIwY2JkZjZiMDIyNTkxYmM4OA==

### format
GET http://ndiing.ddns.net/api/v1/format
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.YTFmMDlkNThiMDM2Njg3ZjRhM2U2NGI1MTFkOWQxYTQ5MTkxMmYyY2IzYTQzNTJkMjhjMzFkMTljZWY3NTIxOGJkYzJiYThhZTMzNWJhZjMyNTE4NjgxZmMyZTI4ZGViMTJiOGRiOGNlNWVlZjJiYzVhMGQxODlhNjBjZTY2NWNiYjM4YmE0MjkxMGNkODE5NDlmMzhkYTEwYzNhNWVkNjEwY2M5YTgwNzRjZGI0M2ZjOTlkOTIwYThjZjg0NmIyZDg2YjJiOGQ0NzhiMGFmMmI0YTM4OGJlYWI1ZTQ0N2MxZDVjZTZjMDIzNTczNjIxYTRhZGFiZjM1YzA5OWVkMGYxZGM3ZWY2M2JkNzkxNWI4M2MwZGI5MDc4MWM1NzkyNjQzNDQ2Y2U4MDBjMzc2MzRmNDFlMzAwZTkwYTljODg5YWZjM2VjMWExN2RlOTYzYWZiNWEwMmQ2MDljZTFkODUxZWIxOGE2M2M5MTcxMWUwYTIwYzExNWE1YWViNGZjYmE4NWQ2ZDMyYTI5ZDQ0ZWY1OWRkMDVkYjFiNGEwNDU3ZDA0OTMyZDY2MzExY2M3YzNhZjQ1OTAzOGZhZjJlNQ==.YjkyNjdkOGRmZTlkYTg2NGNmYTgzYjM4NGE4OTAzZWZhOTVlZmRlOWYxZDlhODIwY2JkZjZiMDIyNTkxYmM4OA==






### webhook filter=[A,W,T,J,S,G,Y,1]
GET http://localhost/api/v1/webhook?code=[code]&to=[to]&to2=[to2]&message=[message]
### webhook
GET http://ndiing.ddns.net/api/v1/webhook
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.YTFmMDlkNThiMDM2Njg3ZjRhM2U2NGI1MTFkOWQxYTQ5MTkxMmYyY2IzYTQzNTJkMjhjMzFkMTljZWY3NTIxOGJkYzJiYThhZTMzNWJhZjMyNTE4NjgxZmMyZTI4ZGViMTJiOGRiOGNlNWVlZjJiYzVhMGQxODlhNjBjZTY2NWNiYjM4YmE0MjkxMGNkODE5NDlmMzhkYTEwYzNhNWVkNjEwY2M5YTgwNzRjZGI0M2ZjOTlkOTIwYThjZjg0NmIyZDg2YjJiOGQ0NzhiMGFmMmI0YTM4OGJlYWI1ZTQ0N2MxZDVjZTZjMDIzNTczNjIxYTRhZGFiZjM1YzA5OWVkMGYxZGM3ZWY2M2JkNzkxNWI4M2MwZGI5MDc4MWM1NzkyNjQzNDQ2Y2U4MDBjMzc2MzRmNDFlMzAwZTkwYTljODg5YWZjM2VjMWExN2RlOTYzYWZiNWEwMmQ2MDljZTFkODUxZWIxOGE2M2M5MTcxMWUwYTIwYzExNWE1YWViNGZjYmE4NWQ2ZDMyYTI5ZDQ0ZWY1OWRkMDVkYjFiNGEwNDU3ZDA0OTMyZDY2MzExY2M3YzNhZjQ1OTAzOGZhZjJlNQ==.YjkyNjdkOGRmZTlkYTg2NGNmYTgzYjM4NGE4OTAzZWZhOTVlZmRlOWYxZDlhODIwY2JkZjZiMDIyNTkxYmM4OA==






### inbox
GET http://ndiing.ddns.net/api/v1/inbox
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.YTFmMDlkNThiMDM2Njg3ZjRhM2U2NGI1MTFkOWQxYTQ5MTkxMmYyY2IzYTQzNTJkMjhjMzFkMTljZWY3NTIxOGJkYzJiYThhZTMzNWJhZjMyNTE4NjgxZmMyZTI4ZGViMTJiOGRiOGNlNWVlZjJiYzVhMGQxODlhNjBjZTY2NWNiYjM4YmE0MjkxMGNkODE5NDlmMzhkYTEwYzNhNWVkNjEwY2M5YTgwNzRjZGI0M2ZjOTlkOTIwYThjZjg0NmIyZDg2YjJiOGQ0NzhiMGFmMmI0YTM4OGJlYWI1ZTQ0N2MxZDVjZTZjMDIzNTczNjIxYTRhZGFiZjM1YzA5OWVkMGYxZGM3ZWY2M2JkNzkxNWI4M2MwZGI5MDc4MWM1NzkyNjQzNDQ2Y2U4MDBjMzc2MzRmNDFlMzAwZTkwYTljODg5YWZjM2VjMWExN2RlOTYzYWZiNWEwMmQ2MDljZTFkODUxZWIxOGE2M2M5MTcxMWUwYTIwYzExNWE1YWViNGZjYmE4NWQ2ZDMyYTI5ZDQ0ZWY1OWRkMDVkYjFiNGEwNDU3ZDA0OTMyZDY2MzExY2M3YzNhZjQ1OTAzOGZhZjJlNQ==.YjkyNjdkOGRmZTlkYTg2NGNmYTgzYjM4NGE4OTAzZWZhOTVlZmRlOWYxZDlhODIwY2JkZjZiMDIyNTkxYmM4OA==






### event
GET http://localhost/api/v1/event?pengirim=%2B6281935155404
### event
GET http://ndiing.ddns.net/api/v1/event
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.YTFmMDlkNThiMDM2Njg3ZjRhM2U2NGI1MTFkOWQxYTQ5MTkxMmYyY2IzYTQzNTJkMjhjMzFkMTljZWY3NTIxOGJkYzJiYThhZTMzNWJhZjMyNTE4NjgxZmMyZTI4ZGViMTJiOGRiOGNlNWVlZjJiYzVhMGQxODlhNjBjZTY2NWNiYjM4YmE0MjkxMGNkODE5NDlmMzhkYTEwYzNhNWVkNjEwY2M5YTgwNzRjZGI0M2ZjOTlkOTIwYThjZjg0NmIyZDg2YjJiOGQ0NzhiMGFmMmI0YTM4OGJlYWI1ZTQ0N2MxZDVjZTZjMDIzNTczNjIxYTRhZGFiZjM1YzA5OWVkMGYxZGM3ZWY2M2JkNzkxNWI4M2MwZGI5MDc4MWM1NzkyNjQzNDQ2Y2U4MDBjMzc2MzRmNDFlMzAwZTkwYTljODg5YWZjM2VjMWExN2RlOTYzYWZiNWEwMmQ2MDljZTFkODUxZWIxOGE2M2M5MTcxMWUwYTIwYzExNWE1YWViNGZjYmE4NWQ2ZDMyYTI5ZDQ0ZWY1OWRkMDVkYjFiNGEwNDU3ZDA0OTMyZDY2MzExY2M3YzNhZjQ1OTAzOGZhZjJlNQ==.YjkyNjdkOGRmZTlkYTg2NGNmYTgzYjM4NGE4OTAzZWZhOTVlZmRlOWYxZDlhODIwY2JkZjZiMDIyNTkxYmM4OA==
