
### Lihat semua sesi
GET http://localhost/api/telegram/v1

### Hapus sesi
DELETE http://localhost/api/telegram/v1/id-sesi-1

### Koneksi
POST http://localhost/api/telegram/v1/id-sesi-1/connect
Content-Type: application/json

{
    "token":"2049367740:AAFl5EPPT9D-EBFhuzxqlbf67Yn6tdQAfms"
}

### Kirim Pesan
GET http://localhost/api/telegram/v1/id-sesi-1/outbox?pengirim=1344008938&pesan=pesan

### Event [Start,Contact,Inbox,Open,Outbox]
GET http://localhost/api/telegram/v1/id-sesi-1/event

