
### Lihat semua sesi
GET http://localhost/api/whatsapp/v1

### Hapus sesi
DELETE http://localhost/api/whatsapp/v1/id-sesi-1

### Koneksi
POST http://localhost/api/whatsapp/v1/id-sesi-1/connect






### Kirim Pesan
GET http://localhost:81/api/whatsapp/v1/id-sesi-1/outbox?pengirim=6281935155404&pesan=pesan
### Kirim Pesan
GET http://localhost:81/api/whatsapp/v1/id-sesi-1/outbox?pengirim=[to]&pesan=[message]






### Event [Open,Close,ConnectionPhoneChange,Qr,Inbox,Outbox]
GET http://localhost/api/whatsapp/v1/id-sesi-1/event

