### Login
POST http://ndiing.myddns.me/api/v1/sign
Content-Type: application/json

{
    "pengirim": "+6281935155404"
}

### Verifikasi login dengan OTP
POST http://ndiing.myddns.me/api/v1/verify
Content-Type: application/json

{
    "_id": "009600c3-0007-4008-8023-00a6000400fb",
    "token": "043309"
}

### Renew token
POST http://ndiing.myddns.me/api/v1/refresh
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTNlN2Q3OWQyMzI1OTllYzUxZjZkM2YxODhmM2I5NzZkODFjNjZiYTU1MDViMGJlMzkxYjY5ZmFiM2I2MWEzNTc4MTkzYWJiNmFjNWU3ODA0NjI3MDM1NGMwZDAzNmRlYTZkMWNkOGI4YWM2YzgzZGFmN2MxNGE0NWQ2Yzg5N2I3ZTAzNGRhMDBjNDZlMGRkZGVlNTI3NmJlNzk2ZWJhODE5ZDcwYzc0MDk1Mjc5ODdmOWI0NTQ1Yzg1ZjIxMmEzYmI0NDZiODUzNzA3ZWNlMzAwYjVjNTJhMGE4YjJhNDAwYWM3N2VkYjdjOTAxNjExOTc2NDg5ZjFhYjdlZDUxMThkMGQzNDEwZGIyNmM3ZWJmNDkyZDVhZGQyYjdjMWQ5MzVmOTNhMjg2NTU0MDE2ODZiMThhZWNjYjgyMjA3ZmU1YTg2Mzc3NmU1MDJjYzIyNzY5ZmUyNTBjNzBiYzc2NGM5NGViMDQwMWE1OWJiNzcxN2MxZTRjZTJhZTJjNTljZjk=.MWVlMTMyYWUxODg0NTg5N2E2ZmE4ZDFkMTM0NDkyZjVkOWYzZWVmNTljNTQ3MTdhZDIwZmQwOTMxODBlMzk0Ng==
Content-Type: application/json

{
    "token": "YzViMDIxNjczMjM1NzdkZjJkZmYzMzc5ZDExZjYyYmZjMGYyNjliZDFmNTI0YzhmODFhMGQzYmZlMjViZWQxOQ=="
}

### Create personal access token
POST http://ndiing.myddns.me/api/v1/generate
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTNlN2Q3OWQyMzI1OTllYzUxZjZkM2YxODhmM2I5NzZkODFjNjZiYTU1MDViMGJlMzkxYjY5ZmFiM2I2MWEzNTc4MTkzYWJiNmFjNWU3ODA0NjI3MDM1NGMwZDAzNmRlYTZkMWNkOGI4YWM2YzgzZGFmN2MxNGE0NWQ2Yzg5N2I3ZTAzNGRhMDBjNDZlMGRkZGVlNTI3NmJlNzk2ZWJhODE5ZDcwYzc0MDk1Mjc5ODdmOWI0NTQ1Yzg1ZjIxMmEzYmI0NDZiODUzNzA3ZWNlMzAwYjVjNTJhMGE4YjJhNDAwYWM3N2VkYjdjOTAxNjExOTc2NDg5ZjFhYjdlZDUxMThkMGQzNDEwZGIyNmM3ZWJmNDkyZDVhZGQyYjdjMWQ5MzVmOTNhMjg2NTU0MDE2ODZiMThhZWNjYjgyMjA3ZmU1YTg2Mzc3NmU1MDJjYzIyNzY5ZmUyNTBjNzBiYzc2NGM5NGViMDQwMWE1OWJiNzcxN2MxZTRjZTJhZTJjNTljZjk=.MWVlMTMyYWUxODg0NTg5N2E2ZmE4ZDFkMTM0NDkyZjVkOWYzZWVmNTljNTQ3MTdhZDIwZmQwOTMxODBlMzk0Ng==
Content-Type: application/json

{
    "remoteAddress":".*",
    "audience": [
        "otomaxOperator",
        "otomaxProduk"
    ],
    "expires_in": 31104000000
}

### List of generated token
GET http://ndiing.myddns.me/api/v1/token
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTNlN2Q3OWQyMzI1OTllYzUxZjZkM2YxODhmM2I5NzZkODFjNjZiYTU1MDViMGJlMzkxYjY5ZmFiM2I2MWEzNTc4MTkzYWJiNmFjNWU3ODA0NjI3MDM1NGMwZDAzNmRlYTZkMWNkOGI4YWM2YzgzZGFmN2MxNGE0NWQ2Yzg5N2I3ZTAzNGRhMDBjNDZlMGRkZGVlNTI3NmJlNzk2ZWJhODE5ZDcwYzc0MDk1Mjc5ODdmOWI0NTQ1Yzg1ZjIxMmEzYmI0NDZiODUzNzA3ZWNlMzAwYjVjNTJhMGE4YjJhNDAwYWM3N2VkYjdjOTAxNjExOTc2NDg5ZjFhYjdlZDUxMThkMGQzNDEwZGIyNmM3ZWJmNDkyZDVhZGQyYjdjMWQ5MzVmOTNhMjg2NTU0MDE2ODZiMThhZWNjYjgyMjA3ZmU1YTg2Mzc3NmU1MDJjYzIyNzY5ZmUyNTBjNzBiYzc2NGM5NGViMDQwMWE1OWJiNzcxN2MxZTRjZTJhZTJjNTljZjk=.MWVlMTMyYWUxODg0NTg5N2E2ZmE4ZDFkMTM0NDkyZjVkOWYzZWVmNTljNTQ3MTdhZDIwZmQwOTMxODBlMzk0Ng==

### Hapus token/lgoout
DELETE http://ndiing.myddns.me/api/v1/revoke/00b100a2-003a-4003-801a-00bf0066009b
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTNlN2Q3OWQyMzI1OTllYzUxZjZkM2YxODhmM2I5NzZkODFjNjZiYTU1MDViMGJlMzkxYjY5ZmFiM2I2MWEzNTc4MTkzYWJiNmFjNWU3ODA0NjI3MDM1NGMwZDAzNmRlYTZkMWNkOGI4YWM2YzgzZGFmN2MxNGE0NWQ2Yzg5N2I3ZTAzNGRhMDBjNDZlMGRkZGVlNTI3NmJlNzk2ZWJhODE5ZDcwYzc0MDk1Mjc5ODdmOWI0NTQ1Yzg1ZjIxMmEzYmI0NDZiODUzNzA3ZWNlMzAwYjVjNTJhMGE4YjJhNDAwYWM3N2VkYjdjOTAxNjExOTc2NDg5ZjFhYjdlZDUxMThkMGQzNDEwZGIyNmM3ZWJmNDkyZDVhZGQyYjdjMWQ5MzVmOTNhMjg2NTU0MDE2ODZiMThhZWNjYjgyMjA3ZmU1YTg2Mzc3NmU1MDJjYzIyNzY5ZmUyNTBjNzBiYzc2NGM5NGViMDQwMWE1OWJiNzcxN2MxZTRjZTJhZTJjNTljZjk=.MWVlMTMyYWUxODg0NTg5N2E2ZmE4ZDFkMTM0NDkyZjVkOWYzZWVmNTljNTQ3MTdhZDIwZmQwOTMxODBlMzk0Ng==
