### Aktifkan downline/reseller
GET http://ndiing.myddns.me/api/v1/aktifkan-dl?kodereseller=ox0004&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Batalkan transaksi yang belum diproses
GET http://ndiing.myddns.me/api/v1/batal-transaksi?trxid=123456&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Cancel balance transfer
GET http://ndiing.myddns.me/api/v1/batal-transfer-saldo?kodereseller=ox0004&jumlah=10000&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Cek harga produk
GET http://ndiing.myddns.me/api/v1/cek-harga?kodeproduk=test5
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Check downline's markup
GET http://ndiing.myddns.me/api/v1/cek-markup?kodereseller=ox0004&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Check product markup
GET http://ndiing.myddns.me/api/v1/cek-markup-produk?kodereseller=ox0004&kodeproduk=test5&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Check all product markups
GET http://ndiing.myddns.me/api/v1/cek-markup-produk2?kodereseller=ox0004&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Cek N (lihat Setting.LimitCekMutasi) mutasi saldo/deposit terakhir
GET http://ndiing.myddns.me/api/v1/cek-mutasi?
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Cek mutasi saldo terakhir, khusus manual, tiket, dan transfer saldo
GET http://ndiing.myddns.me/api/v1/cek-mutasi2?
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Check current OID for OtomaX HTH
GET http://ndiing.myddns.me/api/v1/cek-oid?pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Cek saldo akhir
GET http://ndiing.myddns.me/api/v1/cek-saldo?pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Cek saldo downline
GET http://ndiing.myddns.me/api/v1/cek-saldo-dl?kodereseller=ox0004
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Cek status transaksi
GET http://ndiing.myddns.me/api/v1/cek-status-transaksi?nomor+tujuan=087758437457
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Cek status transaksi
GET http://ndiing.myddns.me/api/v1/cek-status-transaksi2?tujuan=087758437457
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Cek status transaksi
GET http://ndiing.myddns.me/api/v1/cek-status-transaksi3?tanggal=20&tujuan=087758437457
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Cek status N (lihat Setting.LimitCekTransaksiAkhir) transaksi terakhir
GET http://ndiing.myddns.me/api/v1/cek-transaksi-akhir?
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Daftarkan downline/reseller baru
GET http://ndiing.myddns.me/api/v1/daftar-dl?nama=Ridho&alamat=Pacitan&nomorhp=087758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Daftarkan downline/reseller baru
GET http://ndiing.myddns.me/api/v1/daftar-dl2?nama=Ridho&alamat=Pacitan&nomorhp=087758437457&markup=500&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Daftarkan downline/reseller baru
GET http://ndiing.myddns.me/api/v1/daftar-dl3?nama=Ridho&alamat=Pacitan&nomorhp=087758437457&kodelevel=R&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Registration of non member
GET http://ndiing.myddns.me/api/v1/daftar-non-member?pengirim=%2B6281935155404&name=Ridho&address=Pacitan&pin=1234

### Hapus pengirim tipe GTalk
GET http://ndiing.myddns.me/api/v1/hapus-gtalk?email=ndiing.inc%40gmail.com&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Hapus pengirim tipe GTalk untuk downline
GET http://ndiing.myddns.me/api/v1/hapus-gtalk2?kodereseller=ox0004&email=ndiing.inc%40gmail.com&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Delete product markup
GET http://ndiing.myddns.me/api/v1/hapus-markup-produk?kodereseller=ox0004&pin=1234&kodeproduk=test5
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Delete product markup
GET http://ndiing.myddns.me/api/v1/hapus-markup-produk2?kodereseller=ox0004&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Delete product markup
GET http://ndiing.myddns.me/api/v1/hapus-markup-produk3?kodeproduk=test5&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Hapus pengirim tipe SMS
GET http://ndiing.myddns.me/api/v1/hapus-nomor?tujuan=087758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Hapus pengirim tipe SMS
GET http://ndiing.myddns.me/api/v1/hapus-nomor2?kodereseller=ox0004&tujuan=087758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Hapus nomor WA
GET http://ndiing.myddns.me/api/v1/hapus-wa?nomor=087758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Hapus pengirim tipe YM
GET http://ndiing.myddns.me/api/v1/hapus-ym?yahooid=ndiing.inc%40yahoo.co.id&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Hapus pengirim tipe YM dari downline
GET http://ndiing.myddns.me/api/v1/hapus-ym2?kodereseller=ox0004&yahooid=ndiing.inc%40yahoo.co.id&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Cek laporan mutasi saldo per tanggal
GET http://ndiing.myddns.me/api/v1/laporan-mutasi?tanggal=20
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Cek laporan transaksi per tanggal
GET http://ndiing.myddns.me/api/v1/laporan-transaksi?tanggal=20
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### View gift list
GET http://ndiing.myddns.me/api/v1/lihat-hadiah-poin?
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Lihat daftar downline
GET http://ndiing.myddns.me/api/v1/list-dl?
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Lihat daftar downline dari downline (sub-downline)
GET http://ndiing.myddns.me/api/v1/list-dl2?kodereseller=ox0004
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Lihat daftar pengirim semua tipe
GET http://ndiing.myddns.me/api/v1/list-pengirim?
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Lihat daftar pengirim tipe GTalk
GET http://ndiing.myddns.me/api/v1/list-pengirim-gtalk?
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Lihat daftar pengirim tipe GTalk untuk downline
GET http://ndiing.myddns.me/api/v1/list-pengirim-gtalk2?kodereseller=ox0004
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Lihat daftar pengirim tipe SMS
GET http://ndiing.myddns.me/api/v1/list-pengirim-sms?
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Lihat daftar pengirim tipe SMS dari downline
GET http://ndiing.myddns.me/api/v1/list-pengirim-sms2?kodereseller=ox0004
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Lihat daftar pengirim tipe YM
GET http://ndiing.myddns.me/api/v1/list-pengirim-ym?
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Lihat daftar pengirim tipe YM dari downline
GET http://ndiing.myddns.me/api/v1/list-pengirim-ym2?kodereseller=ox0004
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Non-aktifkan downline/reseller
GET http://ndiing.myddns.me/api/v1/non-aktifkan-dl?kodereseller=ox0004&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Reset pin member
GET http://ndiing.myddns.me/api/v1/reset-pin?kodereseller=ox0004&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Tambah pengirim tipe GTalk
GET http://ndiing.myddns.me/api/v1/tambah-gtalk?email=ndiing.inc%40gmail.com&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Tambah pengirim tipe GTalk untuk downline
GET http://ndiing.myddns.me/api/v1/tambah-gtalk2?kodereseller=ox0004&email=ndiing.inc%40gmail.com&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Tambah pengirim tipe SMS
GET http://ndiing.myddns.me/api/v1/tambah-nomor?tujuan=087758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Tambah pengirim tipe SMS untuk downline
GET http://ndiing.myddns.me/api/v1/tambah-nomor2?kodereseller=ox0004&tujuan=087758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Tambah nomor WA
GET http://ndiing.myddns.me/api/v1/tambah-wa?number=087758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Tambah pengirim tipe YM
GET http://ndiing.myddns.me/api/v1/tambah-ym?yahooid=ndiing.inc%40yahoo.co.id&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Tambah pengirim tipe YM untuk downline
GET http://ndiing.myddns.me/api/v1/tambah-ym2?kodereseller=ox0004&yahooid=ndiing.inc%40yahoo.co.id&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Tiket Deposit
GET http://ndiing.myddns.me/api/v1/tiket-deposit?jumlah=10000&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi?kodeproduk=test5&tujuan=087758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi10?pin=1234&kodeproduk=test5&tujuan=087758437457
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi11?pin=1234&nominal=50&tujuan=087758437457
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi12?pin=1234&tujuan=087758437457&nominal=50
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi13?pin=1234&tujuan=087758437457&kodeproduk=test5
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi14?pin=1234&kodeproduk=test5&counter=1&tujuan=087758437457
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi15?tujuan=087758437457&nominal=50&counter=1&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi16?pin=1234&nominal=50&tujuan=087758437457
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi17?pin=1234&tujuan=087758437457&nominal=50
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi18?pin=1234&tujuan=087758437457&kodeproduk=test5
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi19?pin=1234&kodeproduk=test5&tujuan=087758437457
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi2?pin=1234&kodeproduk=test5&tujuan=087758437457
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi20?pin=1234&nominal=50&tujuan=087758437457
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi21?pin=1234&tujuan=087758437457&nominal=50
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi22?pin=1234&tujuan=087758437457&kodeproduk=test5
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi23?tujuan=087758437457&pin=1234&kodeproduk=test5&qty=1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi24?kodeproduk=test5&qty=1&tujuan=087758437457&pin=1234&counter=1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi25?kodeproduk=test5&tujuan=087758437457&pin=1234&trxid=123456
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi26?kodeproduk=test5&tujuan=087758437457&pin=1234&enduser=087758437457
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi27?
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi28?nominal=50&counter=1&tujuan=087758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi29?kodeproduk=test5&qty=1&tujuan=087758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi3?counter=1&kodeproduk=test5&qty=1&tujuan=087758437457&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi4?kodeproduk=test5&nominal=50&tujuan=087758437457&pin=1234&enduser=087758437457
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi5?
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi6?kodeproduk=test5&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi7?nominal=50
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi8?kodeproduk=test5
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa
GET http://ndiing.myddns.me/api/v1/transaksi9?nominal=50&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transaksi pengisian pulsa TANPA pengecekan dobel
GET http://ndiing.myddns.me/api/v1/transaksi-bebas-dobel?
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Transfer saldo/deposit ke downline/reseller
GET http://ndiing.myddns.me/api/v1/transfer-saldo?counter=1&kodereseller=ox0004&jumlah=10000&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Allows transfer balance across the membership network
GET http://ndiing.myddns.me/api/v1/transfer-saldo-lintas?
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Tukar komisi tunda dalam bentuk deposit
GET http://ndiing.myddns.me/api/v1/tukar-komisi?jumlah=10000&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Tukar semua komisi tunda dalam bentuk deposit
GET http://ndiing.myddns.me/api/v1/tukar-komisi2?
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Menukar poin
GET http://ndiing.myddns.me/api/v1/tukar-poin?kode=test5&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Change IP Address
GET http://ndiing.myddns.me/api/v1/ubah-alamat-ip?newip=127.0.0.1&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Ubah level downline
GET http://ndiing.myddns.me/api/v1/ubah-level?kodereseller=ox0004&kodelevel=R&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Change downline's markup
GET http://ndiing.myddns.me/api/v1/ubah-markup?kodereseller=ox0004&markup=500&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Change product markup
GET http://ndiing.myddns.me/api/v1/ubah-markup-produk?kodereseller=ox0004&pin=1234&kodeproduk=test5&markup=500
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Change product markup for all downlines
GET http://ndiing.myddns.me/api/v1/ubah-markup-produk2?pin=1234&kodeproduk=test5&markup=500
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Ubah nama
GET http://ndiing.myddns.me/api/v1/ubah-nama?nama=Ridho&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Change OID for OtomaX HTH
GET http://ndiing.myddns.me/api/v1/ubah-oid?oid=321654987asdfwerezveryt987f65gh1s54g89sr4gv&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Change IP Password
GET http://ndiing.myddns.me/api/v1/ubah-password-ip?oldpassword=1234&newpassword=1234&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Ubah PIN
GET http://ndiing.myddns.me/api/v1/ubah-pin?pinlama=1234&pinbaru=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Change Report URL
GET http://ndiing.myddns.me/api/v1/ubah-report-url?newurl=http%http://ndiing.myddns.me/2Fapi%2Fv1%2Freport&pin=1234
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
