### Login
POST http://ndiing.myddns.me/api/v1/sign
Content-Type: application/json

{
    "pengirim": "+6281935155404"
}

### Verifikasi login dengan OTP
POST http://ndiing.myddns.me/api/v1/verify
Content-Type: application/json

{
    "_id": "00b400cb-00f0-4003-805a-008c00440050",
    "token": "255372"
}

### Renew token
POST http://ndiing.myddns.me/api/v1/refresh
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "token": "ZjJhY2ViYzExNGNmYWM3ODA3MDA0NTFkZTBiZDNkNDdlOTNjZGYxZjY5N2E1NjhmNzQzNzc5M2QwODE5OTAzMg=="
}

### Create personal access token
POST http://ndiing.myddns.me/api/v1/generate
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "remoteAddress":".*",
    "audience": [
        "otomaxOperator",
        "otomaxProduk"
    ],
    "expires_in": 31104000000
}

### List of generated token
GET http://ndiing.myddns.me/api/v1/token
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### Hapus token/lgoout
DELETE http://ndiing.myddns.me/api/v1/revoke/00b100a2-003a-4003-801a-00bf0066009b
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
