###
GET http://localhost/api/v1/web-sms-sender
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

###
GET http://localhost/api/v1/ip-client
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

###
GET http://localhost/api/v1/report
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==

### outbox callback
POST http://localhost/api/v1/outbox-callback
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{}
