### Login
POST http://ndiing.myddns.me/api/v1/sign
Content-Type: application/json

{
    "pengirim": "+6281935155404"
}

### Verifikasi login dengan OTP
POST http://ndiing.myddns.me/api/v1/verify
Content-Type: application/json

{
    "_id": "00ca00c1-000b-4008-800f-00d20071003d",
    "token": "126560"
}

### Renew token
POST http://ndiing.myddns.me/api/v1/refresh
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTM1NDM5MDcxMzJiNzVkMjIwOTU4MjZmZTAxMjFiMGU3ZWZkNTNiMzM3ZGE5MzRjYzJhNTUwYmU1MmIyZGRhY2M3MjAxNmJmMDQxMmVjZjZiNTQxYWExMDBjOTc5NzFkYzdkNzExNGJhOGU0YmFjNzc5NmE5ZjhhMzcyNWI4MmZmOGE4MmNlMDIxYmRlN2E2MTdiZTU5NWE0MzI2ODhlYWM4MzM5MzdmNWJiZjAzNGIxYzBlYzNiMjRhNzc5NGVlNzgxYWI3NTNlNjVlNjg3NGM4YzA1ODNmZTExOTczNjY1MmQ1NmUzYzk1ZjFlNmI1OTc3M2Q4NTc0Nzg0ZGFiY2I2YWVkNjgwMzU2NDY5MTVkZDk0NjdmNmJlMGRjYzkzZjlmMGEwY2VhYTljZDFmMzEzMjA5OTgwOGY1ZDVkYzE0MTgwZjM4OGNmYjkyZjIxMDM2YTIwYjM4MTQ1NjZkYzA2ZDk3MjE0ODU0NDFlOTRjNGNlODEwZWY4N2UzODZiN2I=.ZGU4OWYxNDM3OTgzYjY0MjYxYTZjODc2ZGE1NWFhZDU1OTA0NGY5NzAwMDlmZTNiYjkxNTc1ZWExZGNhZWRkMQ==
Content-Type: application/json

{
    "token": "YzViMDIxNjczMjM1NzdkZjJkZmYzMzc5ZDExZjYyYmZjMGYyNjliZDFmNTI0YzhmODFhMGQzYmZlMjViZWQxOQ=="
}

### Create personal access token
POST http://ndiing.myddns.me/api/v1/generate
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTM1NDM5MDcxMzJiNzVkMjIwOTU4MjZmZTAxMjFiMGU3ZWZkNTNiMzM3ZGE5MzRjYzJhNTUwYmU1MmIyZGRhY2M3MjAxNmJmMDQxMmVjZjZiNTQxYWExMDBjOTc5NzFkYzdkNzExNGJhOGU0YmFjNzc5NmE5ZjhhMzcyNWI4MmZmOGE4MmNlMDIxYmRlN2E2MTdiZTU5NWE0MzI2ODhlYWM4MzM5MzdmNWJiZjAzNGIxYzBlYzNiMjRhNzc5NGVlNzgxYWI3NTNlNjVlNjg3NGM4YzA1ODNmZTExOTczNjY1MmQ1NmUzYzk1ZjFlNmI1OTc3M2Q4NTc0Nzg0ZGFiY2I2YWVkNjgwMzU2NDY5MTVkZDk0NjdmNmJlMGRjYzkzZjlmMGEwY2VhYTljZDFmMzEzMjA5OTgwOGY1ZDVkYzE0MTgwZjM4OGNmYjkyZjIxMDM2YTIwYjM4MTQ1NjZkYzA2ZDk3MjE0ODU0NDFlOTRjNGNlODEwZWY4N2UzODZiN2I=.ZGU4OWYxNDM3OTgzYjY0MjYxYTZjODc2ZGE1NWFhZDU1OTA0NGY5NzAwMDlmZTNiYjkxNTc1ZWExZGNhZWRkMQ==
Content-Type: application/json

{
    "remoteAddress":".*",
    "audience": [
        "otomaxOperator",
        "otomaxProduk"
    ],
    "expires_in": 31104000000
}

### List of generated token
GET http://ndiing.myddns.me/api/v1/token
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTM1NDM5MDcxMzJiNzVkMjIwOTU4MjZmZTAxMjFiMGU3ZWZkNTNiMzM3ZGE5MzRjYzJhNTUwYmU1MmIyZGRhY2M3MjAxNmJmMDQxMmVjZjZiNTQxYWExMDBjOTc5NzFkYzdkNzExNGJhOGU0YmFjNzc5NmE5ZjhhMzcyNWI4MmZmOGE4MmNlMDIxYmRlN2E2MTdiZTU5NWE0MzI2ODhlYWM4MzM5MzdmNWJiZjAzNGIxYzBlYzNiMjRhNzc5NGVlNzgxYWI3NTNlNjVlNjg3NGM4YzA1ODNmZTExOTczNjY1MmQ1NmUzYzk1ZjFlNmI1OTc3M2Q4NTc0Nzg0ZGFiY2I2YWVkNjgwMzU2NDY5MTVkZDk0NjdmNmJlMGRjYzkzZjlmMGEwY2VhYTljZDFmMzEzMjA5OTgwOGY1ZDVkYzE0MTgwZjM4OGNmYjkyZjIxMDM2YTIwYjM4MTQ1NjZkYzA2ZDk3MjE0ODU0NDFlOTRjNGNlODEwZWY4N2UzODZiN2I=.ZGU4OWYxNDM3OTgzYjY0MjYxYTZjODc2ZGE1NWFhZDU1OTA0NGY5NzAwMDlmZTNiYjkxNTc1ZWExZGNhZWRkMQ==

### Hapus token/lgoout
DELETE http://ndiing.myddns.me/api/v1/revoke/00b100a2-003a-4003-801a-00bf0066009b
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTM1NDM5MDcxMzJiNzVkMjIwOTU4MjZmZTAxMjFiMGU3ZWZkNTNiMzM3ZGE5MzRjYzJhNTUwYmU1MmIyZGRhY2M3MjAxNmJmMDQxMmVjZjZiNTQxYWExMDBjOTc5NzFkYzdkNzExNGJhOGU0YmFjNzc5NmE5ZjhhMzcyNWI4MmZmOGE4MmNlMDIxYmRlN2E2MTdiZTU5NWE0MzI2ODhlYWM4MzM5MzdmNWJiZjAzNGIxYzBlYzNiMjRhNzc5NGVlNzgxYWI3NTNlNjVlNjg3NGM4YzA1ODNmZTExOTczNjY1MmQ1NmUzYzk1ZjFlNmI1OTc3M2Q4NTc0Nzg0ZGFiY2I2YWVkNjgwMzU2NDY5MTVkZDk0NjdmNmJlMGRjYzkzZjlmMGEwY2VhYTljZDFmMzEzMjA5OTgwOGY1ZDVkYzE0MTgwZjM4OGNmYjkyZjIxMDM2YTIwYjM4MTQ1NjZkYzA2ZDk3MjE0ODU0NDFlOTRjNGNlODEwZWY4N2UzODZiN2I=.ZGU4OWYxNDM3OTgzYjY0MjYxYTZjODc2ZGE1NWFhZDU1OTA0NGY5NzAwMDlmZTNiYjkxNTc1ZWExZGNhZWRkMQ==
