###
GET http://localhost/api/v1/web-sms-sender
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTNlN2Q3OWQyMzI1OTllYzUxZjZkM2YxODhmM2I5NzZkODFjNjZiYTU1MDViMGJlMzkxYjY5ZmFiM2I2MWEzNTc4MTkzYWJiNmFjNWU3ODA0NjI3MDM1NGMwZDAzNmRlYTZkMWNkOGI4YWM2YzgzZGFmN2MxNGE0NWQ2Yzg5N2I3ZTAzNGRhMDBjNDZlMGRkZGVlNTI3NmJlNzk2ZWJhODE5ZDcwYzc0MDk1Mjc5ODdmOWI0NTQ1Yzg1ZjIxMmEzYmI0NDZiODUzNzA3ZWNlMzAwYjVjNTJhMGE4YjJhNDAwYWM3N2VkYjdjOTAxNjExOTc2NDg5ZjFhYjdlZDUxMThkMGQzNDEwZGIyNmM3ZWJmNDkyZDVhZGQyYjdjMWQ5MzVmOTNhMjg2NTU0MDE2ODZiMThhZWNjYjgyMjA3ZmU1YTg2Mzc3NmU1MDJjYzIyNzY5ZmUyNTBjNzBiYzc2NGM5NGViMDQwMWE1OWJiNzcxN2MxZTRjZTJhZTJjNTljZjk=.MWVlMTMyYWUxODg0NTg5N2E2ZmE4ZDFkMTM0NDkyZjVkOWYzZWVmNTljNTQ3MTdhZDIwZmQwOTMxODBlMzk0Ng==

###
GET http://localhost/api/v1/ip-client
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTNlN2Q3OWQyMzI1OTllYzUxZjZkM2YxODhmM2I5NzZkODFjNjZiYTU1MDViMGJlMzkxYjY5ZmFiM2I2MWEzNTc4MTkzYWJiNmFjNWU3ODA0NjI3MDM1NGMwZDAzNmRlYTZkMWNkOGI4YWM2YzgzZGFmN2MxNGE0NWQ2Yzg5N2I3ZTAzNGRhMDBjNDZlMGRkZGVlNTI3NmJlNzk2ZWJhODE5ZDcwYzc0MDk1Mjc5ODdmOWI0NTQ1Yzg1ZjIxMmEzYmI0NDZiODUzNzA3ZWNlMzAwYjVjNTJhMGE4YjJhNDAwYWM3N2VkYjdjOTAxNjExOTc2NDg5ZjFhYjdlZDUxMThkMGQzNDEwZGIyNmM3ZWJmNDkyZDVhZGQyYjdjMWQ5MzVmOTNhMjg2NTU0MDE2ODZiMThhZWNjYjgyMjA3ZmU1YTg2Mzc3NmU1MDJjYzIyNzY5ZmUyNTBjNzBiYzc2NGM5NGViMDQwMWE1OWJiNzcxN2MxZTRjZTJhZTJjNTljZjk=.MWVlMTMyYWUxODg0NTg5N2E2ZmE4ZDFkMTM0NDkyZjVkOWYzZWVmNTljNTQ3MTdhZDIwZmQwOTMxODBlMzk0Ng==

###
GET http://localhost/api/v1/report
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTNlN2Q3OWQyMzI1OTllYzUxZjZkM2YxODhmM2I5NzZkODFjNjZiYTU1MDViMGJlMzkxYjY5ZmFiM2I2MWEzNTc4MTkzYWJiNmFjNWU3ODA0NjI3MDM1NGMwZDAzNmRlYTZkMWNkOGI4YWM2YzgzZGFmN2MxNGE0NWQ2Yzg5N2I3ZTAzNGRhMDBjNDZlMGRkZGVlNTI3NmJlNzk2ZWJhODE5ZDcwYzc0MDk1Mjc5ODdmOWI0NTQ1Yzg1ZjIxMmEzYmI0NDZiODUzNzA3ZWNlMzAwYjVjNTJhMGE4YjJhNDAwYWM3N2VkYjdjOTAxNjExOTc2NDg5ZjFhYjdlZDUxMThkMGQzNDEwZGIyNmM3ZWJmNDkyZDVhZGQyYjdjMWQ5MzVmOTNhMjg2NTU0MDE2ODZiMThhZWNjYjgyMjA3ZmU1YTg2Mzc3NmU1MDJjYzIyNzY5ZmUyNTBjNzBiYzc2NGM5NGViMDQwMWE1OWJiNzcxN2MxZTRjZTJhZTJjNTljZjk=.MWVlMTMyYWUxODg0NTg5N2E2ZmE4ZDFkMTM0NDkyZjVkOWYzZWVmNTljNTQ3MTdhZDIwZmQwOTMxODBlMzk0Ng==

### outbox callback
POST http://localhost/api/v1/outbox-callback
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTNlN2Q3OWQyMzI1OTllYzUxZjZkM2YxODhmM2I5NzZkODFjNjZiYTU1MDViMGJlMzkxYjY5ZmFiM2I2MWEzNTc4MTkzYWJiNmFjNWU3ODA0NjI3MDM1NGMwZDAzNmRlYTZkMWNkOGI4YWM2YzgzZGFmN2MxNGE0NWQ2Yzg5N2I3ZTAzNGRhMDBjNDZlMGRkZGVlNTI3NmJlNzk2ZWJhODE5ZDcwYzc0MDk1Mjc5ODdmOWI0NTQ1Yzg1ZjIxMmEzYmI0NDZiODUzNzA3ZWNlMzAwYjVjNTJhMGE4YjJhNDAwYWM3N2VkYjdjOTAxNjExOTc2NDg5ZjFhYjdlZDUxMThkMGQzNDEwZGIyNmM3ZWJmNDkyZDVhZGQyYjdjMWQ5MzVmOTNhMjg2NTU0MDE2ODZiMThhZWNjYjgyMjA3ZmU1YTg2Mzc3NmU1MDJjYzIyNzY5ZmUyNTBjNzBiYzc2NGM5NGViMDQwMWE1OWJiNzcxN2MxZTRjZTJhZTJjNTljZjk=.MWVlMTMyYWUxODg0NTg5N2E2ZmE4ZDFkMTM0NDkyZjVkOWYzZWVmNTljNTQ3MTdhZDIwZmQwOTMxODBlMzk0Ng==
Content-Type: application/json

{}
