### Cek saldo downline
POST http://ndiing.myddns.me/api/v1/cek-saldo-dl
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodereseller": "ox0004"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodeproduk": "test5",
    "tujuan": "087758437457",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi14
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "pin": "1234",
    "kodeproduk": "test5",
    "counter": "2",
    "tujuan": "087758437457"
}

### Cek saldo akhir
POST http://ndiing.myddns.me/api/v1/cek-saldo
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "pin": "1234"
}

### Change IP Address
POST http://ndiing.myddns.me/api/v1/ubah-alamat-ip
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "newip": "127.0.0.1",
    "pin": "1234"
}

### Cek laporan transaksi per tanggal
POST http://ndiing.myddns.me/api/v1/laporan-transaksi
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "tanggal": "20"
}

### Cek harga produk
POST http://ndiing.myddns.me/api/v1/cek-harga
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodeproduk": "test5"
}

### Ubah PIN
POST http://ndiing.myddns.me/api/v1/ubah-pin
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "pinlama": "1234",
    "pinbaru": "1234"
}

### Aktifkan downline/reseller
POST http://ndiing.myddns.me/api/v1/aktifkan-dl
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodereseller": "ox0004",
    "pin": "1234"
}

### Lihat daftar pengirim tipe SMS dari downline
POST http://ndiing.myddns.me/api/v1/list-pengirim-sms2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodereseller": "ox0004"
}

### Transfer saldo/deposit ke downline/reseller
POST http://ndiing.myddns.me/api/v1/transfer-saldo
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "counter": "1",
    "kodereseller": "ox0004",
    "jumlah": "10000",
    "pin": "1234"
}

### Batalkan transaksi yang belum diproses
POST http://ndiing.myddns.me/api/v1/batal-transaksi
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "trxid": "123456",
    "pin": "1234"
}

### Lihat daftar pengirim tipe SMS
POST http://ndiing.myddns.me/api/v1/list-pengirim-sms
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
}

### Tiket Deposit
POST http://ndiing.myddns.me/api/v1/tiket-deposit
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "jumlah": "10000",
    "pin": "1234"
}

### Lihat daftar downline
POST http://ndiing.myddns.me/api/v1/list-dl
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
}

### Cek status transaksi
POST http://ndiing.myddns.me/api/v1/cek-status-transaksi
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "nomor tujuan": "087758437457"
}

### Menukar poin
POST http://ndiing.myddns.me/api/v1/tukar-poin
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kode": "test5",
    "pin": "1234"
}

### Registration of non member
POST http://ndiing.myddns.me/api/v1/daftar-non-member
Content-Type: application/json

{
    "pengirim": "+6281935155404",
    "name": "Ridho",
    "address": "Pacitan",
    "pin": "1234"
}

### Cancel balance transfer
POST http://ndiing.myddns.me/api/v1/batal-transfer-saldo
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodereseller": "ox0004",
    "jumlah": "10000",
    "pin": "1234"
}

### Check downline's markup
POST http://ndiing.myddns.me/api/v1/cek-markup
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodereseller": "ox0004",
    "pin": "1234"
}

### Check product markup
POST http://ndiing.myddns.me/api/v1/cek-markup-produk
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodereseller": "ox0004",
    "kodeproduk": "test5",
    "pin": "1234"
}

### Check all product markups
POST http://ndiing.myddns.me/api/v1/cek-markup-produk2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodereseller": "ox0004",
    "pin": "1234"
}

### Cek N (lihat Setting.LimitCekMutasi) mutasi saldo/deposit terakhir
POST http://ndiing.myddns.me/api/v1/cek-mutasi
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
}

### Cek mutasi saldo terakhir, khusus manual, tiket, dan transfer saldo
POST http://ndiing.myddns.me/api/v1/cek-mutasi2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
}

### Check current OID for OtomaX HTH
POST http://ndiing.myddns.me/api/v1/cek-oid
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "pin": "1234"
}

### Cek status transaksi
POST http://ndiing.myddns.me/api/v1/cek-status-transaksi2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "tujuan": "087758437457"
}

### Cek status transaksi
POST http://ndiing.myddns.me/api/v1/cek-status-transaksi3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "tanggal": "20",
    "tujuan": "087758437457"
}

### Cek status N (lihat Setting.LimitCekTransaksiAkhir) transaksi terakhir
POST http://ndiing.myddns.me/api/v1/cek-transaksi-akhir
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
}

### Daftarkan downline/reseller baru
POST http://ndiing.myddns.me/api/v1/daftar-dl
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "nama": "Ridho",
    "alamat": "Pacitan",
    "nomorhp": "087758437457",
    "pin": "1234"
}

### Daftarkan downline/reseller baru
POST http://ndiing.myddns.me/api/v1/daftar-dl2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "nama": "Ridho",
    "alamat": "Pacitan",
    "nomorhp": "087758437457",
    "markup": "500",
    "pin": "1234"
}

### Daftarkan downline/reseller baru
POST http://ndiing.myddns.me/api/v1/daftar-dl3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "nama": "Ridho",
    "alamat": "Pacitan",
    "nomorhp": "087758437457",
    "kodelevel": "R",
    "pin": "1234"
}

### Hapus pengirim tipe GTalk
POST http://ndiing.myddns.me/api/v1/hapus-gtalk
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "email": "ndiing.inc@gmail.com",
    "pin": "1234"
}

### Hapus pengirim tipe GTalk untuk downline
POST http://ndiing.myddns.me/api/v1/hapus-gtalk2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodereseller": "ox0004",
    "email": "ndiing.inc@gmail.com",
    "pin": "1234"
}

### Delete product markup
POST http://ndiing.myddns.me/api/v1/hapus-markup-produk
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodereseller": "ox0004",
    "pin": "1234",
    "kodeproduk": "test5"
}

### Delete product markup
POST http://ndiing.myddns.me/api/v1/hapus-markup-produk2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodereseller": "ox0004",
    "pin": "1234"
}

### Delete product markup
POST http://ndiing.myddns.me/api/v1/hapus-markup-produk3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodeproduk": "test5",
    "pin": "1234"
}

### Hapus pengirim tipe SMS
POST http://ndiing.myddns.me/api/v1/hapus-nomor
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "tujuan": "087758437457",
    "pin": "1234"
}

### Hapus pengirim tipe SMS
POST http://ndiing.myddns.me/api/v1/hapus-nomor2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodereseller": "ox0004",
    "tujuan": "087758437457",
    "pin": "1234"
}

### Hapus nomor WA
POST http://ndiing.myddns.me/api/v1/hapus-wa
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "nomor": "087758437457",
    "pin": "1234"
}

### Hapus pengirim tipe YM
POST http://ndiing.myddns.me/api/v1/hapus-ym
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "yahooid": "ndiing.inc@yahoo.co.id",
    "pin": "1234"
}

### Hapus pengirim tipe YM dari downline
POST http://ndiing.myddns.me/api/v1/hapus-ym2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodereseller": "ox0004",
    "yahooid": "ndiing.inc@yahoo.co.id",
    "pin": "1234"
}

### Cek laporan mutasi saldo per tanggal
POST http://ndiing.myddns.me/api/v1/laporan-mutasi
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "tanggal": "20"
}

### View gift list
POST http://ndiing.myddns.me/api/v1/lihat-hadiah-poin
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
}

### Lihat daftar downline dari downline (sub-downline)
POST http://ndiing.myddns.me/api/v1/list-dl2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodereseller": "ox0004"
}

### Lihat daftar pengirim semua tipe
POST http://ndiing.myddns.me/api/v1/list-pengirim
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
}

### Lihat daftar pengirim tipe GTalk
POST http://ndiing.myddns.me/api/v1/list-pengirim-gtalk
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
}

### Lihat daftar pengirim tipe GTalk untuk downline
POST http://ndiing.myddns.me/api/v1/list-pengirim-gtalk2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodereseller": "ox0004"
}

### Lihat daftar pengirim tipe YM
POST http://ndiing.myddns.me/api/v1/list-pengirim-ym
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
}

### Lihat daftar pengirim tipe YM dari downline
POST http://ndiing.myddns.me/api/v1/list-pengirim-ym2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodereseller": "ox0004"
}

### Non-aktifkan downline/reseller
POST http://ndiing.myddns.me/api/v1/non-aktifkan-dl
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodereseller": "ox0004",
    "pin": "1234"
}

### Reset pin member
POST http://ndiing.myddns.me/api/v1/reset-pin
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodereseller": "ox0004",
    "pin": "1234"
}

### Tambah pengirim tipe GTalk
POST http://ndiing.myddns.me/api/v1/tambah-gtalk
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "email": "ndiing.inc@gmail.com",
    "pin": "1234"
}

### Tambah pengirim tipe GTalk untuk downline
POST http://ndiing.myddns.me/api/v1/tambah-gtalk2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodereseller": "ox0004",
    "email": "ndiing.inc@gmail.com",
    "pin": "1234"
}

### Tambah pengirim tipe SMS
POST http://ndiing.myddns.me/api/v1/tambah-nomor
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "tujuan": "087758437457",
    "pin": "1234"
}

### Tambah pengirim tipe SMS untuk downline
POST http://ndiing.myddns.me/api/v1/tambah-nomor2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodereseller": "ox0004",
    "tujuan": "087758437457",
    "pin": "1234"
}

### Tambah nomor WA
POST http://ndiing.myddns.me/api/v1/tambah-wa
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "number": "087758437457",
    "pin": "1234"
}

### Tambah pengirim tipe YM
POST http://ndiing.myddns.me/api/v1/tambah-ym
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "yahooid": "ndiing.inc@yahoo.co.id",
    "pin": "1234"
}

### Tambah pengirim tipe YM untuk downline
POST http://ndiing.myddns.me/api/v1/tambah-ym2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodereseller": "ox0004",
    "yahooid": "ndiing.inc@yahoo.co.id",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi10
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "pin": "1234",
    "kodeproduk": "test5",
    "tujuan": "087758437457"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi11
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "pin": "1234",
    "nominal": "50",
    "tujuan": "087758437457"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi12
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "pin": "1234",
    "tujuan": "087758437457",
    "nominal": "50"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi13
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "pin": "1234",
    "tujuan": "087758437457",
    "kodeproduk": "test5"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi15
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "tujuan": "087758437457",
    "nominal": "50",
    "counter": "1",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi16
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "pin": "1234",
    "nominal": "50",
    "tujuan": "087758437457"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi17
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "pin": "1234",
    "tujuan": "087758437457",
    "nominal": "50"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi18
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "pin": "1234",
    "tujuan": "087758437457",
    "kodeproduk": "test5"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi19
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "pin": "1234",
    "kodeproduk": "test5",
    "tujuan": "087758437457"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "pin": "1234",
    "kodeproduk": "test5",
    "tujuan": "087758437457"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi20
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "pin": "1234",
    "nominal": "50",
    "tujuan": "087758437457"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi21
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "pin": "1234",
    "tujuan": "087758437457",
    "nominal": "50"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi22
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "pin": "1234",
    "tujuan": "087758437457",
    "kodeproduk": "test5"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi23
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "tujuan": "087758437457",
    "pin": "1234",
    "kodeproduk": "test5",
    "qty": "1"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi24
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodeproduk": "test5",
    "qty": "1",
    "tujuan": "087758437457",
    "pin": "1234",
    "counter": "1"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi25
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodeproduk": "test5",
    "tujuan": "087758437457",
    "pin": "1234",
    "trxid": "123456"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi26
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodeproduk": "test5",
    "tujuan": "087758437457",
    "pin": "1234",
    "enduser": "087758437457"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi27
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi28
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "nominal": "50",
    "counter": "1",
    "tujuan": "087758437457",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi29
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodeproduk": "test5",
    "qty": "1",
    "tujuan": "087758437457",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "counter": "1",
    "kodeproduk": "test5",
    "qty": "1",
    "tujuan": "087758437457",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi4
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodeproduk": "test5",
    "nominal": "50",
    "tujuan": "087758437457",
    "pin": "1234",
    "enduser": "087758437457"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi5
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi6
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodeproduk": "test5",
    "pin": "1234"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi7
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "nominal": "50"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodeproduk": "test5"
}

### Transaksi pengisian pulsa
POST http://ndiing.myddns.me/api/v1/transaksi9
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "nominal": "50",
    "pin": "1234"
}

### Transaksi pengisian pulsa TANPA pengecekan dobel
POST http://ndiing.myddns.me/api/v1/transaksi-bebas-dobel
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
}

### Allows transfer balance across the membership network
POST http://ndiing.myddns.me/api/v1/transfer-saldo-lintas
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
}

### Tukar komisi tunda dalam bentuk deposit
POST http://ndiing.myddns.me/api/v1/tukar-komisi
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "jumlah": "10000",
    "pin": "1234"
}

### Tukar semua komisi tunda dalam bentuk deposit
POST http://ndiing.myddns.me/api/v1/tukar-komisi2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
}

### Ubah level downline
POST http://ndiing.myddns.me/api/v1/ubah-level
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodereseller": "ox0004",
    "kodelevel": "R",
    "pin": "1234"
}

### Change downline's markup
POST http://ndiing.myddns.me/api/v1/ubah-markup
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodereseller": "ox0004",
    "markup": "500",
    "pin": "1234"
}

### Change product markup
POST http://ndiing.myddns.me/api/v1/ubah-markup-produk
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "kodereseller": "ox0004",
    "pin": "1234",
    "kodeproduk": "test5",
    "markup": "500"
}

### Change product markup for all downlines
POST http://ndiing.myddns.me/api/v1/ubah-markup-produk2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "pin": "1234",
    "kodeproduk": "test5",
    "markup": "500"
}

### Ubah nama
POST http://ndiing.myddns.me/api/v1/ubah-nama
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "nama": "Ridho",
    "pin": "1234"
}

### Change OID for OtomaX HTH
POST http://ndiing.myddns.me/api/v1/ubah-oid
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "oid": "321654987asdfwerezveryt987f65gh1s54g89sr4gv",
    "pin": "1234"
}

### Change IP Password
POST http://ndiing.myddns.me/api/v1/ubah-password-ip
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "oldpassword": "1234",
    "newpassword": "1234",
    "pin": "1234"
}

### Change Report URL
POST http://ndiing.myddns.me/api/v1/ubah-report-url
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
Content-Type: application/json

{
    "newurl": "http://ndiing.myddns.me/api/v1/report",
    Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.MTE1YmJkZmI1MmYyNzIwZjBhNDc0ZDQ1ZDVkODEzNTMxYzY4YjJjMTFkMDkzY2I4MGU1NmYxNTRmOGE3YmJkYjMzZmFiYTdjOTlhMjUyMGU1Yzk1ZjM1MmZkYTJiMjlmYjBkMWM3YjMzZGU3YTI5MTVhMWJlOTMwYTI1NTM4ZTJlMzc5MWFhYzA0NDk3YTA1ZDk1ODg2Yjk4NWZhMTA4ZTM2YTk0N2M5OThlMTIxZDAzZjBkZDkzODY5NDIxOTMzMzg1ZDgyMzhhMGY3MmY0NGRhNzJkOWJkMjRmYTBhNjQyNTc0NjMxNTY3NWFjYjdmZjZkNjdiODdjZTY4Y2UzYmM0MzRjMDQ0ODBjZjkwNGQ1ZmM0MGI5NThhMGFmMDgxNGNjN2Q0ZTcyMmY0YjI1MzZjMjQ0YTQzOTJiYjBjY2IxZjAwZDNmMWNiZmIwMjljOWFhZDcxMWI4NWYyMmE4Y2JhZDA2ZTk5ZTVkMmVlYjA5YjUxMWM4YjhlODhiNTMxMmE5NTMwNWQ3OWU1OTdlY2RhMzUzZjRkYWUzMDZjYzA=.NzU1MGJhOGM4YjkyZWEyNmY5ZDYwNmYyNmZkN2UzYzJmYjRhOWIxNzA1ZGRhMGYxNDZhNzA5MTFkYTkzMWQ5Mg==
    "pin": "1234"
}

