###
GET http://ndiing.myddns.me/api/v1/web-sms-sender

###
GET http://ndiing.myddns.me/api/v1/ip-client

###
GET http://ndiing.myddns.me/api/v1/report

### outbox callback
POST http://ndiing.myddns.me/api/v1/outbox-callback
Content-Type: application/json

{}

###
POST http://ndiing.myddns.me/api/v1/inbox
Content-Type: application/json

{
    "pengirim": "+6281935155404",
    "pesan": "sal.1234"
}

###
GET http://ndiing.myddns.me/api/v1/inbox?pengirim=%2B6281935155404&pesan=sal.1234

###
GET http://ndiing.myddns.me/api/v1/format

###
GET http://ndiing.myddns.me/api/v1/reseller?pengirim=%2B6281935155409

###
GET http://ndiing.myddns.me/api/v1/reseller?pengirim=%2B6281935155404&kode_reseller=ox0009

###
GET http://ndiing.myddns.me/api/v1/pengirim?pengirim=%2B6281935155404

###
GET http://ndiing.myddns.me/api/v1/pengirim?pengirim=%2B6281935155404&kode_reseller=ox0004

###
GET http://ndiing.myddns.me/api/v1/downline?pengirim=%2B6281935155404

###
GET http://ndiing.myddns.me/api/v1/downline?pengirim=%2B6281935155404&kode_reseller=ox0004

###
GET http://ndiing.myddns.me/api/v1/operator?pengirim=%2B6281935155404
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.ODRiMjVmNzdhYzg2YTdmOTU4NGU4NGYxOWJjZjlkYzgxNTM5ZWU2OGU2ZWQ1YzQyYjM2ZTdiZTE3ODc3MjA3MWIxNTUxNWM0NjcxMzhkZGJkNTM3MGE1YmNlYjE5NzA5NDk4ODRkNGQ1ODViODJkMjgwYjgzZjJkNDM2NWY2NzVkOGI0ZWMwOTYyNTVhNTNiYTI4M2UzOWE2NjVmYmE0MDk3MDExN2EzZDNhZDJlNmYxZjc3MzU4MmY3ZWY1M2NjYjU0YzEzNTM1NDIzYjA4ZjY3M2QzZGJhNThkOWI2MjgzOWFkMTBjZWY2NTgzZWNiMDA4ZmEyOWNlOTQxMzVjOGMwYTNiZWMzNTJiOWZkM2RmYWY2ODJiYWU0N2NjNTNlMGQ5ODE5MWRkOWUyOTJhYmRiYzRjZjc5NzMzYjQ5MjNmM2E3MmE1NGI2YjdiYjNmYmVmMjA0MGY0YzlkMzdkOWYwZTAyZThiZTNlNTg5Njc3MGZmNDMzMjEyOTk2NTE3MTRmODg1YzFhNDJiZGViMmJlMjIzNzk3ZDEyZWIzNGQ1NGNmZmNkOTEyYTc1MmM4MTY5MDgyNmExMzUzNTk2Nw==.MWYyNjI3ZTYxNGY1MjdkZDlmMjg1M2QzNzkwMWE1ZGU3MTFlNThiNjE1YWZkZjhjOGQ0NDM2YTFiMTg4NjljNA==

###
GET http://ndiing.myddns.me/api/v1/operator?pengirim=%2B6281935155404&kode_reseller=ox0004

###
GET http://ndiing.myddns.me/api/v1/produk?pengirim=%2B6281935155404&kode_operator=TEST
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.ODRiMjVmNzdhYzg2YTdmOTU4NGU4NGYxOWJjZjlkYzgxNTM5ZWU2OGU2ZWQ1YzQyYjM2ZTdiZTE3ODc3MjA3MWIxNTUxNWM0NjcxMzhkZGJkNTM3MGE1YmNlYjE5NzA5NDk4ODRkNGQ1ODViODJkMjgwYjgzZjJkNDM2NWY2NzVkOGI0ZWMwOTYyNTVhNTNiYTI4M2UzOWE2NjVmYmE0MDk3MDExN2EzZDNhZDJlNmYxZjc3MzU4MmY3ZWY1M2NjYjU0YzEzNTM1NDIzYjA4ZjY3M2QzZGJhNThkOWI2MjgzOWFkMTBjZWY2NTgzZWNiMDA4ZmEyOWNlOTQxMzVjOGMwYTNiZWMzNTJiOWZkM2RmYWY2ODJiYWU0N2NjNTNlMGQ5ODE5MWRkOWUyOTJhYmRiYzRjZjc5NzMzYjQ5MjNmM2E3MmE1NGI2YjdiYjNmYmVmMjA0MGY0YzlkMzdkOWYwZTAyZThiZTNlNTg5Njc3MGZmNDMzMjEyOTk2NTE3MTRmODg1YzFhNDJiZGViMmJlMjIzNzk3ZDEyZWIzNGQ1NGNmZmNkOTEyYTc1MmM4MTY5MDgyNmExMzUzNTk2Nw==.MWYyNjI3ZTYxNGY1MjdkZDlmMjg1M2QzNzkwMWE1ZGU3MTFlNThiNjE1YWZkZjhjOGQ0NDM2YTFiMTg4NjljNA==

###
GET http://ndiing.myddns.me/api/v1/produk?pengirim=%2B6281935155404&kode_operator=TEST&kode_reseller=ox0004

###
GET http://ndiing.myddns.me/api/v1/mutasi?pengirim=%2B6281935155409&tanggal_awal=2021-10-01+00%3A00%3A00&tanggal_akhir=2021-10-31+23%3A59%3A59&jenis=T
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.ODRiMjVmNzdhYzg2YTdmOTU4NGU4NGYxOWJjZjlkYzgxNTM5ZWU2OGU2ZWQ1YzQyYjM2ZTdiZTE3ODc3MjA3MWIxNTUxNWM0NjcxMzhkZGJkNTM3MGE1YmNlYjE5NzA5NDk4ODRkNGQ1ODViODJkMjgwYjgzZjJkNDM2NWY2NzVkOGI0ZWMwOTYyNTVhNTNiYTI4M2UzOWE2NjVmYmE0MDk3MDExN2EzZDNhZDJlNmYxZjc3MzU4MmY3ZWY1M2NjYjU0YzEzNTM1NDIzYjA4ZjY3M2QzZGJhNThkOWI2MjgzOWFkMTBjZWY2NTgzZWNiMDA4ZmEyOWNlOTQxMzVjOGMwYTNiZWMzNTJiOWZkM2RmYWY2ODJiYWU0N2NjNTNlMGQ5ODE5MWRkOWUyOTJhYmRiYzRjZjc5NzMzYjQ5MjNmM2E3MmE1NGI2YjdiYjNmYmVmMjA0MGY0YzlkMzdkOWYwZTAyZThiZTNlNTg5Njc3MGZmNDMzMjEyOTk2NTE3MTRmODg1YzFhNDJiZGViMmJlMjIzNzk3ZDEyZWIzNGQ1NGNmZmNkOTEyYTc1MmM4MTY5MDgyNmExMzUzNTk2Nw==.MWYyNjI3ZTYxNGY1MjdkZDlmMjg1M2QzNzkwMWE1ZGU3MTFlNThiNjE1YWZkZjhjOGQ0NDM2YTFiMTg4NjljNA==

###
GET http://ndiing.myddns.me/api/v1/mutasi?pengirim=%2B6281935155409&tanggal_awal=2021-10-01+00%3A00%3A00&tanggal_akhir=2021-10-31+23%3A59%3A59&jenis=T&kode_reseller=ox0004

###
POST http://ndiing.myddns.me/api/v1/sign
Content-Type: application/json

{
    "pengirim": "+6281935155404"
}

###
POST http://ndiing.myddns.me/api/v1/verify
Content-Type: application/json

{
    "_id": "00aa0098-00c1-4003-8011-00000072008d",
    "token": "044388"
}

###
POST http://ndiing.myddns.me/api/v1/refresh
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.OTlmY2MwMmVlYWQ0YWM3MjEyNTdhOGY1NWQ5OGNjN2NmN2M2NDQ3OWMwZWRkYTBiOTgxMTRhN2Q3MGQ2OWIwYTZiYzVlZjZiZDBhNzFhYjBkOWQ4YjQxMDU5ZWQxY2I0ODYxNmQ3ZmQ1ZGI0NzAyMGYwMjhhNTIwZmJiNzBkMjAxMTE5NWRlNTViMzMzZjVhZjYxMjRiZDAxZDkyN2Y1NTU0NzVkN2NkM2IxZGRjOTU3YzJjMGRlNzk4YjAzZTdmYjA4YjMwYTg4ZDdhNWM5MzAxNjU3MWVhOTQxODg0MGZhOTY5NmNkM2VlM2YyNWFlNmIzMTE4ZTJjZmUyMWVhN2FiODYyMTUxNmJlM2QyNzlkMmY0YjBlOWJkMjEzOGRkNTk0N2QyYzY2OGNkMTM0NzE4MDYyMjkyZGY2ODNiMjUxNGRiMWE2MzhmZDhjOWI0ZjEwZWJjOWQyY2IzYTZkZDc2NzU1NGZhMWIzYzY3MmQyYzZhNjQ2MTRkMzAwYjAwNjg3ODNjYWQwNGYzZmE3YmFjZDM0YTQ0MjY1ZTMwMWQ=.ODA1NzI0YWZiMzk1YmU2YWJjMWFhM2Y2ZTE3MmM0MjlmNDI5YTExN2RjM2M1YWYyMTVmZWU0YTcxMGY1ZTU2OA==

{
    "token": "YzBjNzAxMWVlYjE5ZjkwMDhhNmNmMGU0ZmJlODZhOTUwMDQyMzFjNGZiODVmOGM1NDAyZTdmN2RjMzk1MTUzMQ=="
}

###
POST http://ndiing.myddns.me/api/v1/generate
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.OTlmY2MwMmVlYWQ0YWM3MjEyNTdhOGY1NWQ5OGNjN2NmN2M2NDQ3OWMwZWRkYTBiOTgxMTRhN2Q3MGQ2OWIwYTZiYzVlZjZiZDBhNzFhYjBkOWQ4YjQxMDU5ZWQxY2I0ODYxNmQ3ZmQ1ZGI0NzAyMGYwMjhhNTIwZmJiNzBkMjAxMTE5NWRlNTViMzMzZjVhZjYxMjRiZDAxZDkyN2Y1NTU0NzVkN2NkM2IxZGRjOTU3YzJjMGRlNzk4YjAzZTdmYjA4YjMwYTg4ZDdhNWM5MzAxNjU3MWVhOTQxODg0MGZhOTY5NmNkM2VlM2YyNWFlNmIzMTE4ZTJjZmUyMWVhN2FiODYyMTUxNmJlM2QyNzlkMmY0YjBlOWJkMjEzOGRkNTk0N2QyYzY2OGNkMTM0NzE4MDYyMjkyZGY2ODNiMjUxNGRiMWE2MzhmZDhjOWI0ZjEwZWJjOWQyY2IzYTZkZDc2NzU1NGZhMWIzYzY3MmQyYzZhNjQ2MTRkMzAwYjAwNjg3ODNjYWQwNGYzZmE3YmFjZDM0YTQ0MjY1ZTMwMWQ=.ODA1NzI0YWZiMzk1YmU2YWJjMWFhM2Y2ZTE3MmM0MjlmNDI5YTExN2RjM2M1YWYyMTVmZWU0YTcxMGY1ZTU2OA==

{
    "remoteAddress":".*",
    "audience": [
        "otomaxOperator",
        "otomaxProduk"
    ],
    "expires_in": 31104000000
}
