### POST
POST http://localhost/api/v1/
Content-Type: application/json

{}

### GET
GET http://localhost/api/v1/

### PATCH
PATCH http://localhost/api/v1/1

### DELETE
DELETE http://localhost/api/v1/1






### reseller
GET http://localhost/api/v1/reseller?pengirim=%2B6281935155404

### reseller
GET http://localhost/api/v1/reseller?pengirim=%2B6281935155404&kode_reseller=OX0004






### pengirim
GET http://localhost/api/v1/pengirim?pengirim=%2B6281935155404

### pengirim
GET http://localhost/api/v1/pengirim?pengirim=%2B6281935155404&kode_reseller=OX0004






### level
GET http://localhost/api/v1/level?pengirim=%2B6281935155404

### level
GET http://localhost/api/v1/level?pengirim=%2B6281935155404&kode_reseller=OX0004






### downline
GET http://localhost/api/v1/downline?pengirim=%2B6281935155404

### downline
GET http://localhost/api/v1/downline?pengirim=%2B6281935155404&kode_reseller=OX0004






### operator
GET http://localhost/api/v1/operator?pengirim=%2B6281935155404

### operator
GET http://localhost/api/v1/operator?pengirim=%2B6281935155404&kode_reseller=OX0004






### produk
GET http://localhost/api/v1/produk?pengirim=%2B6281935155404&kode_operator=test

### produk
GET http://localhost/api/v1/produk?pengirim=%2B6281935155404&kode_operator=test&kode_reseller=OX0004






### mutasi
GET http://localhost/api/v1/mutasi?pengirim=%2B6281935155404

### mutasi
GET http://localhost/api/v1/mutasi?pengirim=%2B6281935155404&kode_reseller=OX0004






### format
GET http://localhost/api/v1/format?pengirim=%2B6281935155404






### inbox
GET http://localhost/api/v1/inbox?pengirim=%2B6281935155404&pesan=sal.1234

### inbox temp
GET http://localhost/api/v1/inbox-temp?pengirim=127.0.0.1&pesan=ok

### outbox
GET http://localhost/api/v1/outbox?penerima=%2B6281935155404&pesan=ok

### outbox callback
POST http://localhost/api/v1/outbox-callback?penerima=%2B6281935155404

### ussd
POST http://localhost/api/v1/ussd?pengirim=%2B6281935155404
Content-Type: application/json

{"pesan":"format"}
