### connect
POST http://localhost/api/telegram/v1/connect
Content-Type: application/json

{
    "label": "ndiing_bot",
    "password": "1938532379:AAEedETbB6AbfavfTi7iyam0SrLPqWStlR0"
}

### connect
POST http://localhost/api/telegram/v1/connect
Content-Type: application/json

{
    "label": "ndiing_center_1_bot",
    "password": "2049378584:AAH0mEAeNWYSNSQe7flTTwYAwej5im1nJb4"
}
### connect
POST http://localhost/api/telegram/v1/connect
Content-Type: application/json

{
    "label": "api_otomax_bot",
    "password": "2049367740:AAFl5EPPT9D-EBFhuzxqlbf67Yn6tdQAfms"
}

### disconnect
POST http://localhost/api/telegram/v1/disconnect
Content-Type: application/json

{
    "kode_terminal": 23
}

### send
POST http://localhost/api/telegram/v1/send
Content-Type: application/json

{
    "penerima": "1344008938",
    "pesan": "pesan",
    "kode_terminal": 1
}

### send
GET http://localhost/api/telegram/v1/send?penerima=1344008938&pesan=pesan&kode_terminal=1

### send
POST http://localhost/api/telegram/v1/send
Content-Type: application/json

{
    "penerima": "1344008938",
    "pesan": "pesan"
}

### telegram
GET http://localhost/api/telegram/v1/

### telegram
GET http://localhost/api/telegram/v1/1

### telegram
DELETE http://localhost/api/telegram/v1/23
