### POST /connect
POST http://localhost/api/jabber/v1/connect
Content-Type: application/json

{
    "username": "ndiing@jabb.im",
    "password": "S2N#Wcm8rnKbpsg"
}

### POST /connect
POST http://localhost/api/jabber/v1/connect
Content-Type: application/json

{
    "username": "ndiing_center_1@jabb.im",
    "password": "@8d.yAkRiMA7Qpj"
}

### POST /disconnect
POST http://localhost/api/jabber/v1/disconnect
Content-Type: application/json

{
    "kode_terminal": 25
}

### POST /send
POST http://localhost/api/jabber/v1/send
Content-Type: application/json

{
    "penerima": "ndiing2@jabb.im",
    "pesan": "pesan",
    "kode_terminal": 1
}

### GET /send
GET http://localhost/api/jabber/v1/send?penerima=ndiing2%40jabb.im&pesan=pesan&kode_terminal=1

### POST /send
POST http://localhost/api/jabber/v1/send
Content-Type: application/json

{
    "penerima": "ndiing2@jabb.im",
    "pesan": "pesan"
}

### GET
GET http://localhost/api/jabber/v1/

### GET
GET http://localhost/api/jabber/v1/1

### DELETE
DELETE http://localhost/api/jabber/v1/26
