### POST
POST http://localhost/api/jabber/v1/

### GET
GET http://localhost/api/jabber/v1/

### PATCH
PATCH http://localhost/api/jabber/v1/1

### DELETE
DELETE http://localhost/api/jabber/v1/ndiing






### connect
POST http://localhost/api/jabber/v1/connect
Content-Type: application/json

{
"pengirim": "ndiing",
"jid": "ndiing@jabb.im",
"password": "S2N#Wcm8rnKbpsg",
"host": "jabb.im"
}

### connect
POST http://localhost/api/jabber/v1/connect
Content-Type: application/json

{
"pengirim": "ndiing_center_1",
"jid": "ndiing_center_1@jabb.im",
"password": "@8d.yAkRiMA7Qpj",
"host": "jabb.im"
}






### disconnect
POST http://localhost/api/jabber/v1/disconnect
Content-Type: application/json

{
"pengirim": "ndiing"
}

### disconnect
POST http://localhost/api/jabber/v1/disconnect
Content-Type: application/json

{
"pengirim": "ndiing_center_1"
}






### outbox
GET http://localhost/api/jabber/v1/outbox?penerima=ndiing2%40jabb.im&pesan=pesan

### outbox
POST http://localhost/api/jabber/v1/outbox
Content-Type: application/json

{
"penerima": "ndiing2@jabb.im",
"pesan": "pesan"
}
