### connect
POST http://localhost/api/whatsapp/v1/connect
Content-Type: application/json

{
    "label": "6281938064470"
}
### connect
POST http://localhost/api/whatsapp/v1/connect
Content-Type: application/json

{
    "label": "6281938064470",
    "beta": true
}

### connect
POST http://localhost/api/whatsapp/v1/connect
Content-Type: application/json

{
    "label": "6283845311393"
}

### disconnect
POST http://localhost/api/whatsapp/v1/disconnect
Content-Type: application/json

{
    "kode_terminal": 12
}

### send
POST http://localhost/api/whatsapp/v1/send
Content-Type: application/json

{
    "penerima": "6281935155404",
    "pesan": "pesan",
    "kode_terminal": 1
}

### send
GET http://localhost/api/whatsapp/v1/send?penerima=6281935155404&pesan=pesan&kode_terminal=1

### send
POST http://localhost/api/whatsapp/v1/send
Content-Type: application/json

{
    "penerima": "6281935155404",
    "pesan": "pesan"
}

### whatsapp
GET http://localhost/api/whatsapp/v1/

### whatsapp
GET http://localhost/api/whatsapp/v1/12

### whatsapp
DELETE http://localhost/api/whatsapp/v1/12
